package pages

// Page copy and display formats.
const (
	WordQueued             string = "queued"
	WordRunning            string = "running"
	WordExited             string = "exited "
	WordTimedOut           string = "timed out"
	WordKilled             string = "killed"
	WordFailed             string = "failed"
	KindInfo               string = "info"
	KindOK                 string = "ok"
	KindWarn               string = "warn"
	KindErr                string = "err"
	NoticeQueued           string = "Queued"
	NoticeRunning          string = "Running"
	TitleRepositoryMissing string = "The repository is unavailable"
	TitleCommitMissing     string = "The ref did not resolve"
	TitleTooLarge          string = "The tree is too large"
	TitleGitFailed         string = "git failed"
	TitleTimedOut          string = "git took too long"
	TitleStartFailed       string = "The script could not start"
	TitleQueueAbandoned    string = "The run never left the queue"
	TextRepositoryMissing  string = "The repository %s is not there. The script was not started."
	TextCommitMissing      string = "'%s' names no commit in the repository %s. The script was not started."
	TextTooLarge           string = "The commit's files add up to more than %d bytes. The script was not started."
	TextGitFailed          string = "git could not read the repository %s. The script was not started."
	TextTimedOut           string = "git took longer than %d seconds. The script was not started."
	TextStartFailed        string = "The script's process could not be launched. The script was not started."
	TextQueueAbandoned     string = "The run was waiting for a slot when scripts stopped. The script was not started."
	MinuteLayout           string = "2006-01-02 15:04"
	CardLayout             string = "2006-01-02 15:04 UTC"
	SecondLayout           string = "2006-01-02 15:04:05 UTC"
	UnitSecond             string = "s"
	UnitMinute             string = "m "
	UnitByte               string = " B"
	UnitKilobyte           string = " kB"
	UnitMegabyte           string = " MB"
)
