-- migration: 20260811015546_create_artifacts_uploads
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

CREATE TABLE artifacts (
    id             TEXT PRIMARY KEY,
    owner_id       TEXT NOT NULL,
    owner_email    TEXT NOT NULL,
    filename       TEXT NOT NULL,
    description    TEXT NOT NULL DEFAULT '',
    visibility     TEXT NOT NULL CHECK (visibility IN ('public','private')),
    size           INTEGER NOT NULL,
    content_hash   TEXT NOT NULL,
    download_count INTEGER NOT NULL DEFAULT 0,
    created_at     TEXT NOT NULL,
    updated_at     TEXT NOT NULL
);

CREATE TABLE uploads (
    token       TEXT PRIMARY KEY,
    owner_id    TEXT NOT NULL,
    owner_email TEXT NOT NULL,
    filename    TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    visibility  TEXT NOT NULL CHECK (visibility IN ('public','private')),
    created_at  TEXT NOT NULL,
    expires_at  TEXT NOT NULL,
    consumed_at TEXT,
    artifact_id TEXT
);
