-- migration: 20260811011742_initial
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- TODO: write the forward-only schema change below.
