-- migration: 20260715203123_purge_auth_and_enforce_owner_id
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- Purge the complete auth and identity graph. Children are deleted before their
-- parents so this migration works with foreign-key enforcement enabled.
DELETE FROM oauth_tokens;
DELETE FROM oauth_authcodes;
DELETE FROM oauth_chains;
DELETE FROM personal_tokens;
DELETE FROM web_sessions;
DELETE FROM oauth_state;
DELETE FROM dcr_clients;
DELETE FROM identities;

-- Rebuild each owner_id carrier with the invariant enforced by SQLite. There is
-- deliberately no row copy: the clean-slate purge above emptied these tables.
CREATE TABLE web_sessions_new (
    id           TEXT PRIMARY KEY,
    owner_email  TEXT NOT NULL,
    cookie_hash  TEXT NOT NULL UNIQUE,
    issued_at    TEXT NOT NULL,
    expires_at   TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    revoked_at   TEXT NULL,
    owner_id     TEXT NOT NULL
);
DROP TABLE web_sessions;
ALTER TABLE web_sessions_new RENAME TO web_sessions;
CREATE INDEX idx_web_sessions_owner_email ON web_sessions(owner_email);

CREATE TABLE oauth_authcodes_new (
    id                    TEXT PRIMARY KEY,
    code_hash             TEXT NOT NULL UNIQUE,
    client_id             TEXT NOT NULL,
    owner_email           TEXT NOT NULL,
    code_challenge        TEXT NOT NULL,
    code_challenge_method TEXT NOT NULL,
    redirect_uri          TEXT NOT NULL,
    resource              TEXT NOT NULL,
    original_state        TEXT NOT NULL,
    issued_at             TEXT NOT NULL,
    expires_at            TEXT NOT NULL,
    used_at               TEXT NULL,
    chain_id              TEXT NULL,
    owner_id              TEXT NOT NULL
);
DROP TABLE oauth_authcodes;
ALTER TABLE oauth_authcodes_new RENAME TO oauth_authcodes;

CREATE TABLE oauth_chains_new (
    id          TEXT PRIMARY KEY,
    public_id   TEXT NOT NULL UNIQUE,
    client_id   TEXT NOT NULL,
    owner_email TEXT NOT NULL,
    resource    TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    revoked_at  TEXT NULL,
    owner_id    TEXT NOT NULL
);
DROP TABLE oauth_chains;
ALTER TABLE oauth_chains_new RENAME TO oauth_chains;
CREATE INDEX idx_oauth_chains_owner_email ON oauth_chains(owner_email);
CREATE INDEX idx_oauth_chains_client_id ON oauth_chains(client_id);

CREATE TABLE personal_tokens_new (
    id           TEXT PRIMARY KEY,
    public_id    TEXT NOT NULL UNIQUE,
    owner_email  TEXT NOT NULL,
    label        TEXT NOT NULL,
    token_hash   TEXT NOT NULL UNIQUE,
    created_at   TEXT NOT NULL,
    last_used_at TEXT NULL,
    expires_at   TEXT NULL,
    revoked_at   TEXT NULL,
    owner_id     TEXT NOT NULL
);
DROP TABLE personal_tokens;
ALTER TABLE personal_tokens_new RENAME TO personal_tokens;
CREATE INDEX idx_personal_tokens_owner ON personal_tokens(owner_email);
