-- migration: 20260609011053_add_personal_tokens
-- Generated by bin/new-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

-- Personal Access Tokens: owner-minted, cross-service bearer tokens. A PAT is a
-- sibling of the OAuth access token at the auth gate, not part of the OAuth
-- chain model. token_hash is the SHA-256 hex of the plaintext; the plaintext
-- (prefix ms_pat_) is never stored. last_used_at and expires_at exist but are
-- not written in v1 (see ADR §D6/§D7) — revocation is the v1 kill switch.
CREATE TABLE personal_tokens (
    id           TEXT PRIMARY KEY,        -- internal PK (audit + rate-limit key)
    public_id    TEXT NOT NULL UNIQUE,    -- user-facing id for the revoke URL
    owner_email  TEXT NOT NULL,
    label        TEXT NOT NULL,           -- required; identifies where it's used
    token_hash   TEXT NOT NULL UNIQUE,    -- SHA-256 hex; plaintext never stored
    created_at   TEXT NOT NULL,
    last_used_at TEXT NULL,               -- present but NOT written in v1 (see D7)
    expires_at   TEXT NULL,               -- present but always NULL in v1 (see D6)
    revoked_at   TEXT NULL
);
CREATE INDEX idx_personal_tokens_owner ON personal_tokens(owner_email);
