-- migration: 20260719195525_add_owner_id_foreign_keys
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- Dropping oauth_chains temporarily removes the parent table named by
-- oauth_tokens. Defer the check until the rebuilt table has its original name.
PRAGMA defer_foreign_keys = ON;

CREATE TABLE web_sessions_new (
    id           TEXT PRIMARY KEY,
    owner_email  TEXT NOT NULL,
    cookie_hash  TEXT NOT NULL UNIQUE,
    issued_at    TEXT NOT NULL,
    expires_at   TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    revoked_at   TEXT NULL,
    owner_id     TEXT NOT NULL REFERENCES identities(id)
);
INSERT INTO web_sessions_new (
    id, owner_email, cookie_hash, issued_at, expires_at, last_seen_at, revoked_at, owner_id
)
SELECT id, owner_email, cookie_hash, issued_at, expires_at, last_seen_at, revoked_at, owner_id
FROM web_sessions;
DROP TABLE web_sessions;
ALTER TABLE web_sessions_new RENAME TO web_sessions;
CREATE INDEX idx_web_sessions_owner_email ON web_sessions(owner_email);

CREATE TABLE oauth_authcodes_new (
    id                    TEXT PRIMARY KEY,
    code_hash             TEXT NOT NULL UNIQUE,
    client_id             TEXT NOT NULL,
    owner_email           TEXT NOT NULL,
    code_challenge        TEXT NOT NULL,
    code_challenge_method TEXT NOT NULL,
    redirect_uri          TEXT NOT NULL,
    resource              TEXT NOT NULL,
    original_state        TEXT NOT NULL,
    issued_at             TEXT NOT NULL,
    expires_at            TEXT NOT NULL,
    used_at               TEXT NULL,
    chain_id              TEXT NULL,
    owner_id              TEXT NOT NULL REFERENCES identities(id)
);
INSERT INTO oauth_authcodes_new (
    id, code_hash, client_id, owner_email, code_challenge,
    code_challenge_method, redirect_uri, resource, original_state, issued_at,
    expires_at, used_at, chain_id, owner_id
)
SELECT
    id, code_hash, client_id, owner_email, code_challenge,
    code_challenge_method, redirect_uri, resource, original_state, issued_at,
    expires_at, used_at, chain_id, owner_id
FROM oauth_authcodes;
DROP TABLE oauth_authcodes;
ALTER TABLE oauth_authcodes_new RENAME TO oauth_authcodes;

CREATE TABLE oauth_chains_new (
    id          TEXT PRIMARY KEY,
    public_id   TEXT NOT NULL UNIQUE,
    client_id   TEXT NOT NULL,
    owner_email TEXT NOT NULL,
    resource    TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    revoked_at  TEXT NULL,
    owner_id    TEXT NOT NULL REFERENCES identities(id)
);
INSERT INTO oauth_chains_new (
    id, public_id, client_id, owner_email, resource, created_at, revoked_at, owner_id
)
SELECT id, public_id, client_id, owner_email, resource, created_at, revoked_at, owner_id
FROM oauth_chains;
-- oauth_tokens has ON DELETE CASCADE to oauth_chains, and SQLite performs that
-- action when the old parent table is dropped even with deferred FK checks.
-- Preserve the dependent rows across the parent-table rebuild.
CREATE TEMP TABLE oauth_tokens_owner_fk_backup AS
SELECT id, chain_id, kind, token_hash, issued_at, expires_at, used_at, revoked_at
FROM oauth_tokens;
DROP TABLE oauth_chains;
ALTER TABLE oauth_chains_new RENAME TO oauth_chains;
CREATE INDEX idx_oauth_chains_owner_email ON oauth_chains(owner_email);
CREATE INDEX idx_oauth_chains_client_id ON oauth_chains(client_id);
INSERT INTO oauth_tokens (
    id, chain_id, kind, token_hash, issued_at, expires_at, used_at, revoked_at
)
SELECT id, chain_id, kind, token_hash, issued_at, expires_at, used_at, revoked_at
FROM oauth_tokens_owner_fk_backup;
DROP TABLE oauth_tokens_owner_fk_backup;

CREATE TABLE personal_tokens_new (
    id           TEXT PRIMARY KEY,
    public_id    TEXT NOT NULL UNIQUE,
    owner_email  TEXT NOT NULL,
    label        TEXT NOT NULL,
    token_hash   TEXT NOT NULL UNIQUE,
    created_at   TEXT NOT NULL,
    last_used_at TEXT NULL,
    expires_at   TEXT NULL,
    revoked_at   TEXT NULL,
    owner_id     TEXT NOT NULL REFERENCES identities(id)
);
INSERT INTO personal_tokens_new (
    id, public_id, owner_email, label, token_hash, created_at,
    last_used_at, expires_at, revoked_at, owner_id
)
SELECT
    id, public_id, owner_email, label, token_hash, created_at,
    last_used_at, expires_at, revoked_at, owner_id
FROM personal_tokens;
DROP TABLE personal_tokens;
ALTER TABLE personal_tokens_new RENAME TO personal_tokens;
CREATE INDEX idx_personal_tokens_owner ON personal_tokens(owner_email);
