-- migration: 20260720193046_add_oauth_state_provider
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- Existing in-flight handshakes were all minted for Google. New handshakes
-- explicitly persist their provider after this migration.
ALTER TABLE oauth_state ADD COLUMN provider TEXT NOT NULL DEFAULT 'google';
