-- migration: 20260712185110_outbox_routing_columns
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- eventplane/outbox now routes events by kind and subject. Preserve existing
-- rows while forward-migrating the original outbox table from its legacy type
-- column; the empty default keeps all historical events valid.
ALTER TABLE outbox RENAME COLUMN type TO kind;
ALTER TABLE outbox ADD COLUMN subject TEXT NOT NULL DEFAULT '';
