-- migration: 20260720001925_owner_id_keying
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

DROP INDEX IF EXISTS idx_webhooks_owner;
DROP TABLE webhooks;

CREATE TABLE webhooks (
    name              TEXT PRIMARY KEY,
    owner_id          TEXT NOT NULL,
    owner_email       TEXT NOT NULL,
    secret_hash       TEXT NOT NULL,
    created_at        TEXT NOT NULL,
    last_triggered_at TEXT,
    verification      TEXT NOT NULL DEFAULT 'bearer',
    secret            TEXT
);
CREATE INDEX idx_webhooks_owner ON webhooks(owner_id);
