// Package nginx provides nginx generation and application.
package nginx

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ikigenba/ikigenba/opsctl/internal/apps"
	"github.com/ikigenba/ikigenba/opsctl/internal/host"
)

const configurationHeader = "# Generated by opsctl. Do not edit; run 'opsctl nginx apply'.\n\n" +
	"log_format ikigenba '$remote_addr - $remote_user [$time_local] \"$request\" '\n" +
	"                    '$status $body_bytes_sent \"$http_referer\" '\n" +
	"                    '\"$http_user_agent\" $request_id';\n\n" +
	"server {\n" +
	"    listen      80 default_server;\n" +
	"    listen      [::]:80 default_server;\n" +
	"    server_name _;\n" +
	"    access_log  /var/log/nginx/access.log ikigenba;\n" +
	"    return      301 https://$host$request_uri;\n" +
	"}\n\n" +
	"server {\n" +
	"    listen              443 ssl default_server;\n" +
	"    listen              [::]:443 ssl default_server;\n" +
	"    ssl_reject_handshake on;\n" +
	"}\n\n"

const configurationPath = "etc/nginx/conf.d/ikigenba.conf"

const authenticatorServiceName = "auth"

// Render generates the nginx configuration for the services below env.Root.
func Render(ctx context.Context, env host.Env, hostName, apexApp string) ([]byte, error) {
	apexName, err := deriveApexName(hostName, apexApp)
	if err != nil {
		return nil, err
	}
	routed, defaultService, err := discoverRoutedServices(env.Root)
	if err != nil {
		return nil, err
	}

	var output strings.Builder
	writeHeaderBlock(&output, hostName, apexApp, apexName, defaultService, routed)
	disabled := make(map[string]bool, len(routed))
	for _, service := range routed {
		isDisabled, err := apps.Disabled(ctx, env, service.Name)
		if err != nil {
			return nil, fmt.Errorf("service %q disabled state: %w", service.Name, err)
		}
		disabled[service.Name] = isDisabled
	}
	writeServiceBlocks(&output, hostName, apexApp, apexName, routed, disabled)
	return []byte(output.String()), nil
}

// Apply publishes and activates the generated nginx configuration.
func Apply(ctx context.Context, env host.Env, hostName, apexApp string) error {
	candidate, err := Render(ctx, env, hostName, apexApp)
	if err != nil {
		return err
	}
	return applyCandidate(ctx, env, candidate)
}

func applyCandidate(ctx context.Context, env host.Env, candidate []byte) error {
	if env.Execute == nil {
		return errors.New("apply nginx configuration: host execution is not configured")
	}

	previous, err := publish(env.Root, candidate)
	if err != nil {
		return fmt.Errorf("publish nginx configuration: %w", err)
	}

	if err := execute(ctx, env, "nginx -t", "nginx", "-t"); err != nil {
		if restoreErr := previous.restore(); restoreErr != nil {
			return errors.Join(err, fmt.Errorf("restore previous nginx configuration: %w", restoreErr))
		}
		return err
	}
	if err := execute(ctx, env, "systemctl reload-or-restart nginx", "systemctl", "reload-or-restart", "nginx"); err != nil {
		return err
	}
	return nil
}

// Update publishes and activates the configuration only when its bytes changed.
func Update(ctx context.Context, env host.Env, hostName, apexApp string) (bool, error) {
	candidate, err := Render(ctx, env, hostName, apexApp)
	if err != nil {
		return false, err
	}
	rootFS, err := os.OpenRoot(env.Root)
	if err != nil {
		return false, fmt.Errorf("read nginx configuration: %w", err)
	}
	current, readErr := rootFS.ReadFile(configurationPath)
	closeErr := rootFS.Close()
	if closeErr != nil {
		return false, fmt.Errorf("read nginx configuration: %w", closeErr)
	}
	err = readErr
	if err == nil && bytes.Equal(current, candidate) {
		return false, nil
	}
	if err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("read nginx configuration: %w", err)
	}
	if err := applyCandidate(ctx, env, candidate); err != nil {
		return false, err
	}
	return true, nil
}

// Write publishes the generated nginx configuration without activating it.
func Write(ctx context.Context, env host.Env, hostName, apexApp string) error {
	candidate, err := Render(ctx, env, hostName, apexApp)
	if err != nil {
		return err
	}
	if _, err := publish(env.Root, candidate); err != nil {
		return fmt.Errorf("publish nginx configuration: %w", err)
	}
	return nil
}

type publishedConfiguration struct {
	path     string
	existed  bool
	contents []byte
	mode     os.FileMode
}

func publish(root string, candidate []byte) (publishedConfiguration, error) {
	path := filepath.Join(root, configurationPath)
	previous := publishedConfiguration{path: path}
	info, err := os.Stat(path)
	switch {
	case err == nil:
		previous.existed = true
		previous.mode = info.Mode().Perm()
		rootFS, openErr := os.OpenRoot(root)
		if openErr != nil {
			return publishedConfiguration{}, openErr
		}
		previous.contents, err = rootFS.ReadFile(configurationPath)
		closeErr := rootFS.Close()
		if err != nil {
			return publishedConfiguration{}, err
		}
		if closeErr != nil {
			return publishedConfiguration{}, closeErr
		}
	case !os.IsNotExist(err):
		return publishedConfiguration{}, err
	}

	if err := replaceFile(path, candidate, 0o644); err != nil {
		return publishedConfiguration{}, err
	}
	return previous, nil
}

func (previous publishedConfiguration) restore() error {
	if !previous.existed {
		return os.Remove(previous.path)
	}
	return replaceFile(previous.path, previous.contents, previous.mode)
}

func replaceFile(path string, contents []byte, mode os.FileMode) (returnErr error) {
	temporary, err := os.CreateTemp(filepath.Dir(path), ".ikigenba.conf-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer func() {
		if err := os.Remove(temporaryPath); err != nil && !os.IsNotExist(err) && returnErr == nil {
			returnErr = err
		}
	}()

	if _, err := temporary.Write(contents); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Chmod(mode); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}

func execute(ctx context.Context, env host.Env, label, name string, args ...string) error {
	result, err := env.Execute(ctx, host.Command{Name: name, Args: args})
	if err != nil {
		var commandErr *host.CommandError
		if errors.As(err, &commandErr) {
			return err
		}
		return &host.CommandError{Label: label, Result: result, Err: err}
	}
	if result.ExitCode != 0 {
		return &host.CommandError{Label: label, Result: result, Err: err}
	}
	return nil
}

func discoverRoutedServices(root string) ([]apps.Service, string, error) {
	services, err := apps.Discover(root)
	if err != nil {
		return nil, "", fmt.Errorf("render nginx configuration: %w", err)
	}

	var routed []apps.Service
	var defaultService string
	for _, service := range services {
		if service.ManifestError != nil {
			return nil, "", fmt.Errorf("service %q manifest: %w", service.Name, service.ManifestError)
		}
		if service.Manifest == nil || service.Manifest.App == "" {
			continue
		}
		if service.Manifest.Default {
			if defaultService != "" {
				return nil, "", fmt.Errorf("conflicting default services %q and %q", defaultService, service.Name)
			}
			defaultService = service.Name
		}
		routed = append(routed, service)
	}
	return routed, defaultService, nil
}

func deriveApexName(hostName, apexApp string) (string, error) {
	if apexApp == "" {
		return "", nil
	}
	return host.Apex(hostName)
}

func writeHeaderBlock(output *strings.Builder, hostName, apexApp, apexName, defaultService string, routed []apps.Service) {
	output.WriteString(configurationHeader)
	output.WriteString("server {\n")
	output.WriteString("    listen              443 ssl;\n")
	output.WriteString("    server_name         ")
	if defaultService == "" {
		output.WriteString(hostName)
		output.WriteByte(' ')
	}
	output.WriteString("*.")
	output.WriteString(hostName)
	if apexApp != "" && !isRouted(apexApp, routed) {
		output.WriteByte(' ')
		output.WriteString(apexName)
	}
	output.WriteString(";\n")
	writeCertificate(output, hostName)
	output.WriteString("    access_log          /var/log/nginx/access.log ikigenba;\n")
	output.WriteString("    return              404;\n")
	output.WriteString("}\n")
}

func writeServiceBlocks(output *strings.Builder, hostName, apexApp, apexName string, routed []apps.Service, disabled map[string]bool) {
	authenticated := isRouted(authenticatorServiceName, routed)
	for _, service := range routed {
		writeServerPreamble(output, service, hostName, apexApp, apexName)
		switch {
		case disabled[service.Name]:
			output.WriteString("    return              503;\n")
		case !authenticated:
			writeInclude(output, service.Name)
			writeUpstreamLocation(output, service.Name)
		case service.Name == authenticatorServiceName:
			writeInclude(output, service.Name)
			writeUnwiredLocations(output, service.Name)
		default:
			writeInclude(output, service.Name)
			writeWiredLocations(output, service.Name, hostName)
		}
		output.WriteString("}\n")
	}
}

func writeServerPreamble(output *strings.Builder, service apps.Service, hostName, apexApp, apexName string) {
	output.WriteString("\nserver {\n")
	output.WriteString("    listen              443 ssl;\n")
	output.WriteString("    server_name         ")
	output.WriteString(service.Name)
	output.WriteByte('.')
	output.WriteString(hostName)
	if service.Manifest.Default {
		output.WriteByte(' ')
		output.WriteString(hostName)
	}
	if service.Name == apexApp {
		output.WriteByte(' ')
		output.WriteString(apexName)
	}
	output.WriteString(";\n")
	writeCertificate(output, hostName)
	output.WriteString("    access_log          /var/log/nginx/access.log ikigenba;\n")
}

func writeInclude(output *strings.Builder, name string) {
	output.WriteString("\n    include /opt/")
	output.WriteString(name)
	output.WriteString("/etc/nginx.conf*;\n\n")
}

func writeUnwiredLocations(output *strings.Builder, name string) {
	output.WriteString("    location = /check {\n")
	output.WriteString("        return 404;\n")
	output.WriteString("    }\n\n")
	writeUpstreamLocation(output, name)
}

func writeUpstreamLocation(output *strings.Builder, name string) {
	output.WriteString("    location / {\n")
	writeProxy(output, name)
	output.WriteString("        proxy_set_header Host              $host;\n")
	output.WriteString("        proxy_set_header X-Real-IP         $remote_addr;\n")
	output.WriteString("        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;\n")
	output.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	output.WriteString("        proxy_set_header X-Request-Id      $request_id;\n")
	output.WriteString("    }\n")
}

func writeProxy(output *strings.Builder, name string) {
	output.WriteString("        proxy_pass       http://unix:/run/ikigenba/")
	output.WriteString(name)
	output.WriteString(".sock:;\n")
}

func writeWiredLocations(output *strings.Builder, name, hostName string) {
	output.WriteString("    location = /_ikigenba/check {\n")
	output.WriteString("        internal;\n")
	output.WriteString("        proxy_pass              http://unix:/run/ikigenba/auth.sock:/check;\n")
	output.WriteString("        proxy_pass_request_body off;\n")
	output.WriteString("        proxy_set_header        Content-Length \"\";\n")
	output.WriteString("        proxy_set_header        X-User-Id    \"\";\n")
	output.WriteString("        proxy_set_header        X-User-Email \"\";\n")
	output.WriteString("        proxy_set_header        X-Request-Id $request_id;\n")
	output.WriteString("    }\n\n")
	output.WriteString("    location @auth_redirect {\n")
	output.WriteString("        return 302 https://auth.")
	output.WriteString(hostName)
	output.WriteString("/?return=$scheme://$host$request_uri;\n")
	output.WriteString("    }\n\n")
	output.WriteString("    location / {\n")
	output.WriteString("        auth_request     /_ikigenba/check;\n")
	output.WriteString("        auth_request_set $auth_user_id    $upstream_http_x_user_id;\n")
	output.WriteString("        auth_request_set $auth_user_email $upstream_http_x_user_email;\n")
	output.WriteString("        error_page       401 = @auth_redirect;\n\n")
	writeProxy(output, name)
	output.WriteString("        proxy_set_header Host              $host;\n")
	output.WriteString("        proxy_set_header X-Real-IP         $remote_addr;\n")
	output.WriteString("        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;\n")
	output.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	output.WriteString("        proxy_set_header X-Request-Id      $request_id;\n")
	output.WriteString("        proxy_set_header X-User-Id         $auth_user_id;\n")
	output.WriteString("        proxy_set_header X-User-Email      $auth_user_email;\n")
	output.WriteString("    }\n")
}

func isRouted(name string, routed []apps.Service) bool {
	for _, service := range routed {
		if service.Name == name {
			return true
		}
	}
	return false
}

func writeCertificate(output *strings.Builder, hostName string) {
	output.WriteString("    ssl_certificate     /etc/letsencrypt/live/")
	output.WriteString(hostName)
	output.WriteString("/fullchain.pem;\n")
	output.WriteString("    ssl_certificate_key /etc/letsencrypt/live/")
	output.WriteString(hostName)
	output.WriteString("/privkey.pem;\n")
}
