// Package nginx provides nginx generation and application.
package nginx

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ikigenba/ikigenba/opsctl/internal/apps"
	"github.com/ikigenba/ikigenba/opsctl/internal/host"
)

const configurationHeader = "# Generated by opsctl. Do not edit; run 'opsctl nginx apply'.\n\n" +
	"log_format ikigenba '$remote_addr - $remote_user [$time_local] \"$request\" '\n" +
	"                    '$status $body_bytes_sent \"$http_referer\" '\n" +
	"                    '\"$http_user_agent\" $request_id';\n\n"

const defaultServers = "server {\n" +
	"    listen      80 default_server;\n" +
	"    listen      [::]:80 default_server;\n" +
	"    server_name _;\n" +
	"    access_log  /var/log/nginx/access.log ikigenba;\n" +
	"    return      301 https://$host$request_uri;\n" +
	"}\n\n" +
	"server {\n" +
	"    listen              443 ssl default_server;\n" +
	"    listen              [::]:443 ssl default_server;\n" +
	"    ssl_reject_handshake on;\n" +
	"}\n\n"

const configurationPath = "etc/nginx/conf.d/ikigenba.conf"

const authenticatorServiceName = "auth"

// Render generates the nginx configuration for the services below env.Root.
func Render(ctx context.Context, env host.Env, hostName, apexApp string) ([]byte, error) {
	apexName, err := deriveApexName(hostName, apexApp)
	if err != nil {
		return nil, err
	}
	routed, defaultService, err := discoverRoutedServices(env.Root)
	if err != nil {
		return nil, err
	}

	var output strings.Builder
	writeHeaderBlock(&output, hostName, apexApp, apexName, defaultService, routed)
	disabled := make(map[string]bool, len(routed))
	for _, service := range routed {
		isDisabled, err := apps.Disabled(ctx, env, service.Name)
		if err != nil {
			return nil, fmt.Errorf("service %q disabled state: %w", service.Name, err)
		}
		disabled[service.Name] = isDisabled
	}
	writeServiceBlocks(&output, hostName, apexApp, apexName, routed, disabled)
	return []byte(output.String()), nil
}

// Apply publishes and activates the generated nginx configuration.
func Apply(ctx context.Context, env host.Env, hostName, apexApp string) error {
	candidate, err := Render(ctx, env, hostName, apexApp)
	if err != nil {
		return err
	}
	return applyCandidate(ctx, env, candidate)
}

func applyCandidate(ctx context.Context, env host.Env, candidate []byte) error {
	if env.Execute == nil {
		return errors.New("apply nginx configuration: host execution is not configured")
	}

	previous, err := publish(env.Root, candidate)
	if err != nil {
		return fmt.Errorf("publish nginx configuration: %w", err)
	}

	if err := execute(ctx, env, "nginx -t", "nginx", "-t"); err != nil {
		if restoreErr := previous.restore(); restoreErr != nil {
			return errors.Join(err, fmt.Errorf("restore previous nginx configuration: %w", restoreErr))
		}
		return err
	}
	if err := execute(ctx, env, "systemctl reload-or-restart nginx", "systemctl", "reload-or-restart", "nginx"); err != nil {
		return err
	}
	return nil
}

// Update publishes and activates the configuration only when its bytes changed.
func Update(ctx context.Context, env host.Env, hostName, apexApp string) (bool, error) {
	candidate, err := Render(ctx, env, hostName, apexApp)
	if err != nil {
		return false, err
	}
	rootFS, err := os.OpenRoot(env.Root)
	if err != nil {
		return false, fmt.Errorf("read nginx configuration: %w", err)
	}
	current, readErr := rootFS.ReadFile(configurationPath)
	closeErr := rootFS.Close()
	if closeErr != nil {
		return false, fmt.Errorf("read nginx configuration: %w", closeErr)
	}
	err = readErr
	if err == nil && bytes.Equal(current, candidate) {
		return false, nil
	}
	if err != nil && !os.IsNotExist(err) {
		return false, fmt.Errorf("read nginx configuration: %w", err)
	}
	if err := applyCandidate(ctx, env, candidate); err != nil {
		return false, err
	}
	return true, nil
}

// Write publishes the generated nginx configuration without activating it.
func Write(ctx context.Context, env host.Env, hostName, apexApp string) error {
	candidate, err := Render(ctx, env, hostName, apexApp)
	if err != nil {
		return err
	}
	if _, err := publish(env.Root, candidate); err != nil {
		return fmt.Errorf("publish nginx configuration: %w", err)
	}
	return nil
}

type publishedConfiguration struct {
	path     string
	existed  bool
	contents []byte
	mode     os.FileMode
}

func publish(root string, candidate []byte) (publishedConfiguration, error) {
	path := filepath.Join(root, configurationPath)
	previous := publishedConfiguration{path: path}
	info, err := os.Stat(path)
	switch {
	case err == nil:
		previous.existed = true
		previous.mode = info.Mode().Perm()
		rootFS, openErr := os.OpenRoot(root)
		if openErr != nil {
			return publishedConfiguration{}, openErr
		}
		previous.contents, err = rootFS.ReadFile(configurationPath)
		closeErr := rootFS.Close()
		if err != nil {
			return publishedConfiguration{}, err
		}
		if closeErr != nil {
			return publishedConfiguration{}, closeErr
		}
	case !os.IsNotExist(err):
		return publishedConfiguration{}, err
	}

	if err := replaceFile(path, candidate, 0o644); err != nil {
		return publishedConfiguration{}, err
	}
	return previous, nil
}

func (previous publishedConfiguration) restore() error {
	if !previous.existed {
		return os.Remove(previous.path)
	}
	return replaceFile(previous.path, previous.contents, previous.mode)
}

func replaceFile(path string, contents []byte, mode os.FileMode) (returnErr error) {
	temporary, err := os.CreateTemp(filepath.Dir(path), ".ikigenba.conf-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer func() {
		if err := os.Remove(temporaryPath); err != nil && !os.IsNotExist(err) && returnErr == nil {
			returnErr = err
		}
	}()

	if _, err := temporary.Write(contents); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Chmod(mode); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}

func execute(ctx context.Context, env host.Env, label, name string, args ...string) error {
	result, err := env.Execute(ctx, host.Command{Name: name, Args: args})
	if err != nil {
		var commandErr *host.CommandError
		if errors.As(err, &commandErr) {
			return err
		}
		return &host.CommandError{Label: label, Result: result, Err: err}
	}
	if result.ExitCode != 0 {
		return &host.CommandError{Label: label, Result: result, Err: err}
	}
	return nil
}

func discoverRoutedServices(root string) ([]apps.Service, string, error) {
	services, err := apps.Discover(root)
	if err != nil {
		return nil, "", fmt.Errorf("render nginx configuration: discover services: %w", err)
	}

	for _, service := range services {
		if service.ManifestError != nil {
			return nil, "", fmt.Errorf("%s: etc/manifest.toml: %w", service.Name, service.ManifestError)
		}
	}
	var routed []apps.Service
	var defaultService string
	for _, service := range services {
		if service.Manifest == nil || service.Manifest.App == "" {
			continue
		}
		if service.Manifest.Default {
			if defaultService != "" {
				return nil, "", fmt.Errorf("conflicting default services %q and %q", defaultService, service.Name)
			}
			defaultService = service.Name
		}
		routed = append(routed, service)
	}
	return routed, defaultService, nil
}

func deriveApexName(hostName, apexApp string) (string, error) {
	if apexApp == "" {
		return "", nil
	}
	return host.Apex(hostName)
}

func writeHeaderBlock(output *strings.Builder, hostName, apexApp, apexName, defaultService string, routed []apps.Service) {
	output.WriteString(configurationHeader)
	writeCORSMaps(output, hostName)
	output.WriteString(defaultServers)
	output.WriteString("server {\n")
	output.WriteString("    listen              443 ssl;\n")
	output.WriteString("    server_name         ")
	if defaultService == "" {
		output.WriteString(hostName)
		output.WriteByte(' ')
	}
	output.WriteString("*.")
	output.WriteString(hostName)
	if apexApp != "" && !isRouted(apexApp, routed) {
		output.WriteByte(' ')
		output.WriteString(apexName)
	}
	output.WriteString(";\n")
	writeCertificate(output, hostName)
	output.WriteString("    access_log          /var/log/nginx/access.log ikigenba;\n")
	output.WriteString("    return              404;\n")
	output.WriteString("}\n")
}

func writeServiceBlocks(output *strings.Builder, hostName, apexApp, apexName string, routed []apps.Service, disabled map[string]bool) {
	authenticated := isRouted(authenticatorServiceName, routed)
	for _, service := range routed {
		writeServerPreamble(output, service, hostName, apexApp, apexName)
		writeCORSHeaders(output, "    add_header          ", true)
		output.WriteString("\n    if ($request_method = OPTIONS) {\n        return 204;\n    }\n")
		switch {
		case disabled[service.Name]:
			output.WriteString("\n    return              503;\n")
		case !authenticated:
			writeInclude(output, service.Dir)
			writeUpstreamLocation(output, service.Name)
		case service.Name == authenticatorServiceName:
			writeInclude(output, service.Dir)
			writeUnwiredLocations(output, service.Name)
		default:
			writeInclude(output, service.Dir)
			writeWiredLocations(output, service.Name, hostName, service.Manifest.Guests)
		}
		output.WriteString("}\n")
	}
}

func writeServerPreamble(output *strings.Builder, service apps.Service, hostName, apexApp, apexName string) {
	output.WriteString("\nserver {\n")
	output.WriteString("    listen              443 ssl;\n")
	output.WriteString("    server_name         ")
	output.WriteString(service.Name)
	output.WriteByte('.')
	output.WriteString(hostName)
	if service.Manifest.Default {
		output.WriteByte(' ')
		output.WriteString(hostName)
	}
	if service.Name == apexApp {
		output.WriteByte(' ')
		output.WriteString(apexName)
	}
	output.WriteString(";\n")
	writeCertificate(output, hostName)
	output.WriteString("    access_log          /var/log/nginx/access.log ikigenba;\n")
}

func writeInclude(output *strings.Builder, name string) {
	output.WriteString("\n    include ")
	output.WriteString(name)
	output.WriteString("/etc/nginx.conf*;\n\n")
}

func writeUnwiredLocations(output *strings.Builder, name string) {
	output.WriteString("    location = /check {\n")
	output.WriteString("        return 404;\n")
	output.WriteString("    }\n\n")
	output.WriteString("    location = /check/open {\n")
	output.WriteString("        return 404;\n")
	output.WriteString("    }\n\n")
	writeUpstreamLocation(output, name)
}

func writeUpstreamLocation(output *strings.Builder, name string) {
	output.WriteString("    location / {\n")
	writeProxy(output, name)
	output.WriteString("        proxy_set_header Host              $host;\n")
	output.WriteString("        proxy_set_header X-Real-IP         $remote_addr;\n")
	output.WriteString("        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;\n")
	output.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	output.WriteString("        proxy_set_header X-Request-Id      $request_id;\n")
	if name != authenticatorServiceName {
		output.WriteString("        proxy_set_header Origin            $ikigenba_upstream_origin;\n")
	}
	output.WriteString("    }\n")
}

func writeProxy(output *strings.Builder, name string) {
	output.WriteString("        proxy_pass       http://unix:/run/ikigenba/")
	output.WriteString(name)
	output.WriteString(".sock:;\n")
}

func writeAuthCheck(output *strings.Builder, open bool) {
	suffix := ""
	if open {
		suffix = "/open"
	}
	output.WriteString("    location = /_ikigenba/check" + suffix + " {\n")
	output.WriteString("        internal;\n")
	output.WriteString("        proxy_pass              http://unix:/run/ikigenba/auth.sock:/check" + suffix + ";\n")
	output.WriteString("        proxy_pass_request_body off;\n")
	output.WriteString("        proxy_set_header        Content-Length \"\";\n")
	output.WriteString("        proxy_set_header        X-User-Id    \"\";\n")
	output.WriteString("        proxy_set_header        X-User-Email \"\";\n")
	output.WriteString("        proxy_set_header        X-Request-Id $request_id;\n")
	output.WriteString("        proxy_set_header        X-Original-Method $request_method;\n")
	output.WriteString("        proxy_set_header        X-Original-Host   $host;\n")
	output.WriteString("        proxy_set_header        X-Original-URI    $request_uri;\n")
	output.WriteString("        proxy_set_header        Origin            $ikigenba_upstream_origin;\n")
	output.WriteString("    }\n\n")
}

func writeWiredLocations(output *strings.Builder, name, hostName string, guests bool) {
	writeAuthCheck(output, false)
	if guests {
		writeAuthCheck(output, true)
	}
	output.WriteString("    location @auth_redirect {\n")
	output.WriteString("        return 302 https://auth.")
	output.WriteString(hostName)
	output.WriteString("/?return=$scheme://$host$request_uri;\n")
	output.WriteString("    }\n\n")
	output.WriteString("    location @mcp_unauthorized {\n")
	output.WriteString("        default_type text/plain;\n")
	output.WriteString("        add_header   WWW-Authenticate                 'Bearer realm=\"ikigenba\", resource_metadata=\"https://mcp." + hostName + "/.well-known/oauth-protected-resource\"' always;\n")
	writeCORSHeaders(output, "        add_header   ", false)
	output.WriteString("        return       401 \"authentication required: send Authorization: Bearer <token>\\n\";\n")
	output.WriteString("    }\n\n")
	output.WriteString("    location @mcp_invalid_token {\n")
	output.WriteString("        default_type text/plain;\n")
	output.WriteString("        add_header   WWW-Authenticate                 'Bearer error=\"invalid_token\", resource_metadata=\"https://mcp." + hostName + "/.well-known/oauth-protected-resource\"' always;\n")
	writeCORSHeaders(output, "        add_header   ", false)
	output.WriteString("        return       401 \"authentication required: send Authorization: Bearer <token>\\n\";\n")
	output.WriteString("    }\n\n")
	output.WriteString("    location @api_unauthorized {\n")
	output.WriteString("        default_type text/plain;\n")
	output.WriteString("        add_header   WWW-Authenticate                 'Bearer realm=\"ikigenba\"' always;\n")
	writeCORSHeaders(output, "        add_header   ", false)
	output.WriteString("        return       401 \"authentication required: sign in or send Authorization: Bearer <token>\\n\";\n")
	output.WriteString("    }\n\n")
	output.WriteString("    location @git_unauthorized {\n")
	output.WriteString("        default_type text/plain;\n")
	output.WriteString("        add_header   WWW-Authenticate                 'Basic realm=\"ikigenba\"' always;\n")
	writeCORSHeaders(output, "        add_header   ", false)
	output.WriteString("        return       401 \"authentication required: send your token as the password\\n\";\n")
	output.WriteString("    }\n\n")
	writeAuthenticatedLocation(output, name, "= /mcp", "@mcp_unauthorized", false)
	output.WriteByte('\n')
	writeAuthenticatedLocation(output, name, "^~ /mcp/", "@mcp_unauthorized", false)
	output.WriteByte('\n')
	writeAuthenticatedLocation(output, name, "= /api", "@api_unauthorized", false)
	output.WriteByte('\n')
	writeAuthenticatedLocation(output, name, "^~ /api/", "@api_unauthorized", false)
	output.WriteByte('\n')
	writeAuthenticatedLocation(output, name, "~ /(info/refs|git-upload-pack|git-receive-pack)$", "@git_unauthorized", false)
	output.WriteByte('\n')
	writeAuthenticatedLocation(output, name, "/", "@auth_redirect", guests)
}

func writeAuthenticatedLocation(output *strings.Builder, name, location, unauthorized string, open bool) {
	suffix := ""
	if open {
		suffix = "/open"
	}
	output.WriteString("    location " + location + " {\n")
	output.WriteString("        auth_request     /_ikigenba/check" + suffix + ";\n")
	output.WriteString("        auth_request_set $auth_user_id    $upstream_http_x_user_id;\n")
	output.WriteString("        auth_request_set $auth_user_email $upstream_http_x_user_email;\n")
	if !open {
		output.WriteString("        error_page       401 = " + unauthorized + ";\n")
		if unauthorized == "@mcp_unauthorized" {
			output.WriteString("        error_page       403 = @mcp_invalid_token;\n")
		}
	}
	output.WriteByte('\n')
	writeProxy(output, name)
	output.WriteString("        proxy_set_header Host              $host;\n")
	output.WriteString("        proxy_set_header X-Real-IP         $remote_addr;\n")
	output.WriteString("        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;\n")
	output.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	output.WriteString("        proxy_set_header X-Request-Id      $request_id;\n")
	output.WriteString("        proxy_set_header Origin            $ikigenba_upstream_origin;\n")
	output.WriteString("        proxy_set_header X-User-Id         $auth_user_id;\n")
	output.WriteString("        proxy_set_header X-User-Email      $auth_user_email;\n")
	output.WriteString("    }\n")
}

func isRouted(name string, routed []apps.Service) bool {
	for _, service := range routed {
		if service.Name == name {
			return true
		}
	}
	return false
}

func writeCertificate(output *strings.Builder, hostName string) {
	output.WriteString("    ssl_certificate     /etc/letsencrypt/live/")
	output.WriteString(hostName)
	output.WriteString("/fullchain.pem;\n")
	output.WriteString("    ssl_certificate_key /etc/letsencrypt/live/")
	output.WriteString(hostName)
	output.WriteString("/privkey.pem;\n")
}

func writeCORSMaps(output *strings.Builder, hostName string) {
	origin := strings.ReplaceAll("https://sites."+hostName, ".", `\.`)
	output.WriteString("map $http_origin $ikigenba_cors_origin {\n    default")
	output.WriteString(strings.Repeat(" ", len(origin)-2))
	output.WriteString("\"\";\n    \"~^" + origin + "$\" $http_origin;\n}\n\n")
	output.WriteString(`map $ikigenba_cors_origin $ikigenba_cors_credentials {
    ""      "";
    default "true";
}

map "$request_method $ikigenba_cors_credentials" $ikigenba_cors_methods {
    default        "";
    "OPTIONS true" "GET, POST, PUT, PATCH, DELETE, OPTIONS";
}

map "$request_method $ikigenba_cors_credentials" $ikigenba_cors_headers {
    default        "";
    "OPTIONS true" "Content-Type, Accept, Mcp-Session-Id, Mcp-Protocol-Version, Last-Event-ID";
}

map "$request_method $ikigenba_cors_credentials" $ikigenba_cors_max_age {
    default        "";
    "OPTIONS true" "600";
}

map "$request_method $ikigenba_cors_credentials" $ikigenba_cors_expose {
    default        "";
    "OPTIONS true" "";
    "~ true$"      "Mcp-Session-Id, WWW-Authenticate";
}

map $ikigenba_cors_origin $ikigenba_upstream_origin {
    ""      $http_origin;
    default "";
}

`)
}

func writeCORSHeaders(output *strings.Builder, prefix string, preflight bool) {
	output.WriteString(prefix + "Access-Control-Allow-Origin      $ikigenba_cors_origin always;\n")
	output.WriteString(prefix + "Access-Control-Allow-Credentials $ikigenba_cors_credentials always;\n")
	if preflight {
		output.WriteString(prefix + "Access-Control-Allow-Methods     $ikigenba_cors_methods always;\n")
		output.WriteString(prefix + "Access-Control-Allow-Headers     $ikigenba_cors_headers always;\n")
		output.WriteString(prefix + "Access-Control-Max-Age           $ikigenba_cors_max_age always;\n")
	}
	output.WriteString(prefix + "Access-Control-Expose-Headers    $ikigenba_cors_expose always;\n")
	output.WriteString(prefix + "Vary                             Origin always;\n")
}
