// Package nginx provides nginx generation and application.
package nginx

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/ikigenba/ikigenba/opsctl/internal/apps"
	"github.com/ikigenba/ikigenba/opsctl/internal/host"
)

const configurationHeader = "# Generated by opsctl. Do not edit; run 'opsctl nginx apply'.\n\n" +
	"server {\n" +
	"    listen      80 default_server;\n" +
	"    listen      [::]:80 default_server;\n" +
	"    server_name _;\n" +
	"    return      301 https://$host$request_uri;\n" +
	"}\n\n" +
	"server {\n" +
	"    listen              443 ssl default_server;\n" +
	"    listen              [::]:443 ssl default_server;\n" +
	"    ssl_reject_handshake on;\n" +
	"}\n\n"

// Render generates the nginx configuration for the services below env.Root.
func Render(_ context.Context, env host.Env, hostName string) ([]byte, error) {
	routed, defaultService, err := discoverRoutedServices(env.Root)
	if err != nil {
		return nil, err
	}

	var output strings.Builder
	writeHeaderBlock(&output, hostName, defaultService)
	writeServiceBlocks(&output, hostName, routed)
	return []byte(output.String()), nil
}

func discoverRoutedServices(root string) ([]apps.Service, string, error) {
	services, err := apps.Discover(root)
	if err != nil {
		return nil, "", fmt.Errorf("render nginx configuration: %w", err)
	}

	var routed []apps.Service
	var defaultService string
	for _, service := range services {
		if service.ManifestError != nil {
			return nil, "", fmt.Errorf("service %q manifest: %w", service.Name, service.ManifestError)
		}
		if service.Manifest == nil || service.Manifest.Port == 0 {
			continue
		}
		if service.Manifest.Default {
			if defaultService != "" {
				return nil, "", fmt.Errorf("conflicting default services %q and %q", defaultService, service.Name)
			}
			defaultService = service.Name
		}
		routed = append(routed, service)
	}
	return routed, defaultService, nil
}

func writeHeaderBlock(output *strings.Builder, hostName, defaultService string) {
	output.WriteString(configurationHeader)
	output.WriteString("server {\n")
	output.WriteString("    listen              443 ssl;\n")
	output.WriteString("    server_name         ")
	if defaultService == "" {
		output.WriteString(hostName)
		output.WriteByte(' ')
	}
	output.WriteString("*.")
	output.WriteString(hostName)
	output.WriteString(";\n")
	writeCertificate(output, hostName)
	output.WriteString("    return              404;\n")
	output.WriteString("}\n")
}

func writeServiceBlocks(output *strings.Builder, hostName string, routed []apps.Service) {
	for _, service := range routed {
		output.WriteString("\nserver {\n")
		output.WriteString("    listen              443 ssl;\n")
		output.WriteString("    server_name         ")
		output.WriteString(service.Name)
		output.WriteByte('.')
		output.WriteString(hostName)
		if service.Manifest.Default {
			output.WriteByte(' ')
			output.WriteString(hostName)
		}
		output.WriteString(";\n")
		writeCertificate(output, hostName)
		output.WriteString("\n    include /opt/")
		output.WriteString(service.Name)
		output.WriteString("/etc/nginx.conf*;\n\n")
		output.WriteString("    location / {\n")
		output.WriteString("        proxy_pass       http://127.0.0.1:")
		output.WriteString(strconv.Itoa(service.Manifest.Port))
		output.WriteString(";\n")
		output.WriteString("        proxy_set_header Host              $host;\n")
		output.WriteString("        proxy_set_header X-Real-IP         $remote_addr;\n")
		output.WriteString("        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;\n")
		output.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
		output.WriteString("    }\n")
		output.WriteString("}\n")
	}
}

func writeCertificate(output *strings.Builder, hostName string) {
	output.WriteString("    ssl_certificate     /etc/letsencrypt/live/")
	output.WriteString(hostName)
	output.WriteString("/fullchain.pem;\n")
	output.WriteString("    ssl_certificate_key /etc/letsencrypt/live/")
	output.WriteString(hostName)
	output.WriteString("/privkey.pem;\n")
}
