package nginx_test

import (
	"context"
	"encoding/binary"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strconv"
	"strings"
	"syscall"
	"testing"

	"github.com/ikigenba/ikigenba/opsctl/internal/host"
	"github.com/ikigenba/ikigenba/opsctl/internal/nginx"
)

const baseWithoutDefault = "# Generated by opsctl. Do not edit; run 'opsctl nginx apply'.\n\n" +
	"log_format ikigenba '$remote_addr - $remote_user [$time_local] \"$request\" '\n" +
	"                    '$status $body_bytes_sent \"$http_referer\" '\n" +
	"                    '\"$http_user_agent\" $request_id';\n\n" +
	"server {\n" +
	"    listen      80 default_server;\n" +
	"    listen      [::]:80 default_server;\n" +
	"    server_name _;\n" +
	"    access_log  /var/log/nginx/access.log ikigenba;\n" +
	"    return      301 https://$host$request_uri;\n" +
	"}\n\n" +
	"server {\n" +
	"    listen              443 ssl default_server;\n" +
	"    listen              [::]:443 ssl default_server;\n" +
	"    ssl_reject_handshake on;\n" +
	"}\n\n" +
	"server {\n" +
	"    listen              443 ssl;\n" +
	"    server_name         example.test *.example.test;\n" +
	"    ssl_certificate     /etc/letsencrypt/live/example.test/fullchain.pem;\n" +
	"    ssl_certificate_key /etc/letsencrypt/live/example.test/privkey.pem;\n" +
	"    access_log          /var/log/nginx/access.log ikigenba;\n" +
	"    return              404;\n" +
	"}\n"

const temporaryConfigurationPrefix = ".ikigenba.conf-"

func enabledEnv(root string) host.Env {
	return host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
		if command.Name != "systemctl" || len(command.Args) != 4 || command.Args[0] != "show" {
			return host.Result{}, errors.New("unexpected command")
		}
		return host.Result{Stdout: []byte("LoadState=loaded\nUnitFileState=enabled\n")}, nil
	}}
}

func TestRenderHasExportedContract(t *testing.T) {
	// R-NH7K-2R1K
	t.Parallel()
	assertRenderSignature(t, nginx.Render)
}

// R-WILI-A3EP
func TestRenderExactBaseConfigurationWithoutDefault(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	mkdir(t, filepath.Join(root, "opt", "state-only", "state"))
	writeManifest(t, root, "disabled", "default = false\n")

	got, err := nginx.Render(context.Background(), enabledEnv(root), "example.test", "")
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if string(got) != baseWithoutDefault {
		t.Fatalf("configuration mismatch\ngot:\n%s\nwant:\n%s", got, baseWithoutDefault)
	}

	apexHostName := "space.example.test"
	got, err = nginx.Render(context.Background(), enabledEnv(root), apexHostName, "missing")
	if err != nil {
		t.Fatalf("Render with unrouted apex: %v", err)
	}
	want := strings.ReplaceAll(baseWithoutDefault, "example.test", apexHostName)
	want = strings.Replace(want,
		"server_name         space.example.test *.space.example.test;",
		"server_name         space.example.test *.space.example.test example.test;", 1)
	if string(got) != want {
		t.Fatalf("configuration with unrouted apex mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

// R-WILI-A3EP
func TestRenderAppendsUnroutedApexTo404WithRoutedDefault(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	hostName := "space.example.test"
	writeManifest(t, root, "alpha", "app = \"alpha\"\ndefault = true\n")

	got, err := nginx.Render(context.Background(), enabledEnv(root), hostName, "missing")
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	want := strings.ReplaceAll(baseWithoutDefault, "example.test", hostName)
	want = strings.Replace(want,
		"server_name         space.example.test *.space.example.test;",
		"server_name         *.space.example.test example.test;", 1)
	want += serviceBlock("alpha", 4100, true, hostName, "")
	if string(got) != want {
		t.Fatalf("configuration with routed default and unrouted apex mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

// R-78QR-PFQ3
// R-WILI-A3EP
// R-EKHF-6EW1
// R-WOP0-6Y46
func TestRenderRoutesServicesInDiscoveryOrderWithoutSideEffects(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	hostName := "space.example.test"
	writeManifest(t, root, "zeta", "app = \"zeta\"\n")
	writeManifest(t, root, "alpha", "app = \"alpha\"\ndefault = true\n")
	writeManifest(t, root, "ignored", "default = false\n")
	mkdir(t, filepath.Join(root, "opt", "manifestless", "state"))
	before := snapshotTree(t, root)
	executions := 0
	env := host.Env{Root: root, Execute: func(context.Context, host.Command) (host.Result, error) {
		executions++
		return host.Result{}, nil
	}}

	got, err := nginx.Render(context.Background(), env, hostName, "zeta")
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if executions != 2 {
		t.Fatalf("Render executed %d commands, want two read-only state queries", executions)
	}
	if after := snapshotTree(t, root); !reflect.DeepEqual(after, before) {
		t.Fatalf("Render changed files under root\nbefore: %#v\nafter:  %#v", before, after)
	}

	want := strings.ReplaceAll(baseWithoutDefault, "example.test", hostName)
	want = strings.Replace(want, "server_name         space.example.test *.space.example.test;", "server_name         *.space.example.test;", 1) +
		serviceBlock("alpha", 4100, true, hostName, "") + serviceBlock("zeta", 9200, false, hostName, "example.test")
	if string(got) != want {
		t.Fatalf("configuration mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
	for _, unrouted := range []string{"ignored", "manifestless"} {
		if strings.Contains(string(got), unrouted) {
			t.Fatalf("unrouted service %q was rendered", unrouted)
		}
	}
}

// R-EKHF-6EW1
// R-WOP0-6Y46
func TestRenderKeepsPlainBlocksWhenAuthIsNotRouted(t *testing.T) {
	t.Parallel()
	hostName := "space.example.test"
	apexName := "example.test"
	services := []struct {
		name string
		port int
		def  bool
		apex string
	}{
		{name: "beta", port: 5200},
		{name: "notes", port: 8100, def: true},
		{name: "web", port: 9100, apex: apexName},
	}
	want := baseForHost(hostName, true)
	for _, service := range services {
		want += serviceBlock(service.name, service.port, service.def, hostName, service.apex)
	}

	for _, test := range []struct {
		name  string
		setup func(*testing.T, string)
	}{
		{name: "state directory", setup: func(t *testing.T, root string) {
			t.Helper()
			mkdir(t, filepath.Join(root, "opt", "auth", "state"))
		}},
		{name: "manifest without app", setup: func(t *testing.T, root string) {
			t.Helper()
			writeManifest(t, root, "auth", "default = false\n")
		}},
	} {
		t.Run(test.name, func(t *testing.T) {
			withAuth := t.TempDir()
			withoutAuth := t.TempDir()
			for _, root := range []string{withAuth, withoutAuth} {
				for _, service := range services {
					manifest := "app = \"" + service.name + "\"\n"
					if service.def {
						manifest += "default = true\n"
					}
					writeManifest(t, root, service.name, manifest)
					fragment := filepath.Join(root, "opt", service.name, "etc", "nginx.conf")
					if _, err := os.Stat(fragment); !os.IsNotExist(err) {
						t.Fatalf("fixture nginx fragment for %s: %v", service.name, err)
					}
				}
			}
			test.setup(t, withAuth)

			gotWith, err := nginx.Render(context.Background(), enabledEnv(withAuth), hostName, "web")
			if err != nil {
				t.Fatalf("Render with unrouted auth: %v", err)
			}
			gotWithout, err := nginx.Render(context.Background(), enabledEnv(withoutAuth), hostName, "web")
			if err != nil {
				t.Fatalf("Render without auth: %v", err)
			}
			if string(gotWith) != string(gotWithout) {
				t.Fatalf("unrouted auth changed plain configuration\nwith:\n%s\nwithout:\n%s", gotWith, gotWithout)
			}
			if string(gotWith) != want {
				t.Fatalf("plain configuration mismatch\ngot:\n%s\nwant:\n%s", gotWith, want)
			}
			if strings.Contains(string(gotWith), "auth") {
				t.Fatalf("unrouted auth was treated as the authenticator:\n%s", gotWith)
			}
		})
	}
}

// R-EKHF-6EW1
// R-EPD0-PHUT
// R-ET0P-UT2W
func TestRenderUsesUnwiredAuthenticatorAndWiredServices(t *testing.T) {
	t.Parallel()
	hostName := "space.example.test"
	apexName := "example.test"

	t.Run("default and apex do not opt out", func(t *testing.T) {
		got := renderAuthenticatedServices(t, hostName, "web", false)
		for _, name := range []string{"auth", "beta", "notes", "web"} {
			if strings.Count(got, "include /opt/"+name+"/etc/nginx.conf*;") != 1 {
				t.Fatalf("missing unconditional include for %s\n%s", name, got)
			}
		}
		want := baseForHost(hostName, true) +
			unwiredServiceBlock(false, hostName, "") +
			wiredServiceBlock("beta", 5200, false, hostName, "", 4401) +
			wiredServiceBlock("notes", 8100, true, hostName, "", 4401) +
			wiredServiceBlock("web", 9100, false, hostName, apexName, 4401)
		if got != want {
			t.Fatalf("configuration mismatch\ngot:\n%s\nwant:\n%s", got, want)
		}
		authBlock := serverBlockFor(t, got, "auth."+hostName)
		for _, forbidden := range []string{"auth_request", "/_ikigenba/check", "@auth_redirect", "X-User-Id", "X-User-Email"} {
			if strings.Contains(authBlock, forbidden) {
				t.Fatalf("unwired authenticator block contains %q:\n%s", forbidden, authBlock)
			}
		}
		if !strings.Contains(authBlock, "    location = /check {\n        return 404;\n    }\n") {
			t.Fatalf("authenticator block missing public /check 404:\n%s", authBlock)
		}
		for _, name := range []string{"beta." + hostName, "notes." + hostName, "web." + hostName} {
			block := serverBlockFor(t, got, name)
			if !strings.Contains(block, "auth_request     /_ikigenba/check;") || strings.Contains(block, "location = /check {") {
				t.Fatalf("%s was not the wired block:\n%s", name, block)
			}
		}
	})

	t.Run("authenticator may be default and apex", func(t *testing.T) {
		got := renderAuthenticatedServices(t, hostName, "auth", true)
		want := baseForHost(hostName, true) +
			unwiredServiceBlock(true, hostName, apexName) +
			wiredServiceBlock("beta", 5200, false, hostName, "", 3307)
		if got != want {
			t.Fatalf("configuration mismatch\ngot:\n%s\nwant:\n%s", got, want)
		}
	})

	t.Run("authenticator alone stays unwired", func(t *testing.T) {
		root := t.TempDir()
		writeManifest(t, root, "auth", "app = \"auth\"\n")
		got, err := nginx.Render(context.Background(), enabledEnv(root), hostName, "")
		if err != nil {
			t.Fatalf("Render: %v", err)
		}
		want := baseForHost(hostName, false) + unwiredServiceBlock(false, hostName, "")
		if string(got) != want {
			t.Fatalf("configuration mismatch\ngot:\n%s\nwant:\n%s", got, want)
		}
	})
}

// R-EO54-BQ44
func TestRenderNamesAuthenticatorHostAndCheckEndpoint(t *testing.T) {
	t.Parallel()
	hostName := "space.example.test"
	got := renderAuthenticatedServices(t, hostName, "web", false)
	publicHost := "auth." + hostName
	endpoint := "http://unix:/run/ikigenba/auth.sock:/check"
	wiredServices := 3
	redirect := "return 302 https://" + publicHost + "/?return=$scheme://$host$request_uri;"
	if strings.Count(got, redirect) != wiredServices {
		t.Fatalf("public host redirects = %d, want %d\n%s", strings.Count(got, redirect), wiredServices, got)
	}
	if strings.Count(got, "proxy_pass              "+endpoint+";") != wiredServices {
		t.Fatalf("check endpoint proxies = %d, want %d\n%s", strings.Count(got, "proxy_pass              "+endpoint+";"), wiredServices, got)
	}

	if strings.Count(got, publicHost) != wiredServices+1 {
		t.Fatalf("public host occurrences = %d, want %d", strings.Count(got, publicHost), wiredServices+1)
	}

	endpointCount := 0
	searchFrom := 0
	needle := "http://unix:/run/ikigenba/auth.sock:"
	for {
		rel := strings.Index(got[searchFrom:], needle)
		if rel < 0 {
			break
		}
		at := searchFrom + rel
		rest := got[at+len(needle):]
		switch {
		case strings.HasPrefix(rest, "/check;"):
			endpointCount++
		case strings.HasPrefix(rest, ";"):
		default:
			end := min(at+len(needle)+16, len(got))
			t.Fatalf("loopback check endpoint spelled %q", got[at:end])
		}
		searchFrom = at + len(needle)
	}
	if endpointCount != wiredServices {
		t.Fatalf("check endpoint occurrences = %d, want %d", endpointCount, wiredServices)
	}
}

// R-EZ47-RNSD
func TestRenderWiredBlockSubrequestsAndBlanksClientIdentity(t *testing.T) {
	got := renderAuthenticatedServices(t, "space.example.test", "web", false)
	for _, name := range []string{"beta", "notes", "web"} {
		block := serverBlockFor(t, got, name+".space.example.test")
		for _, location := range []string{"= /mcp", "^~ /mcp/", "~ /(info/refs|git-upload-pack|git-receive-pack)$", "/"} {
			section := locationFor(t, block, location)
			for _, directive := range []string{
				"auth_request     /_ikigenba/check;",
				"auth_request_set $auth_user_id    $upstream_http_x_user_id;",
				"auth_request_set $auth_user_email $upstream_http_x_user_email;",
				"proxy_set_header X-User-Id         $auth_user_id;",
				"proxy_set_header X-User-Email      $auth_user_email;",
			} {
				if strings.Count(section, directive) != 1 {
					t.Fatalf("%s %s missing unique %q: %s", name, location, directive, section)
				}
			}
			if strings.Contains(section, "$http_x_user_") {
				t.Fatal("client identity forwarded")
			}
			if strings.Index(section, "auth_request ") > strings.Index(section, "proxy_pass ") {
				t.Fatal("proxy before auth")
			}
		}
		browser := locationFor(t, block, "/")
		if strings.Count(browser, "error_page") != 1 || !strings.Contains(browser, "error_page       401 = @auth_redirect;") {
			t.Fatalf("browser status mapping: %s", browser)
		}
		check := locationFor(t, block, "= /_ikigenba/check")
		for _, directive := range []string{"proxy_pass_request_body off;", "proxy_set_header        X-User-Id    \"\";", "proxy_set_header        X-User-Email \"\";"} {
			if !strings.Contains(check, directive) {
				t.Fatalf("missing %q: %s", directive, check)
			}
		}
	}
}

// R-F1K0-J79R
func TestRenderOriginalRequestHeadersOnlyInAuthenticatorSubrequest(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeManifest(t, root, "auth", "app = \"auth\"\n")
	writeManifest(t, root, "notes", "app = \"notes\"\ndefault = true\n")
	writeManifest(t, root, "web", "app = \"web\"\n")
	writeManifest(t, root, "disabled", "app = \"disabled\"\n")
	env := host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
		if command.Args[3] == "ikigenba-disabled.socket" {
			return host.Result{Stdout: []byte("LoadState=loaded\nUnitFileState=disabled\n")}, nil
		}
		return host.Result{}, nil
	}}
	got, err := nginx.Render(context.Background(), env, "space.example.test", "web")
	if err != nil {
		t.Fatal(err)
	}
	headers := map[string]string{
		"X-Original-Method": "        proxy_set_header        X-Original-Method $request_method;\n",
		"X-Original-Host":   "        proxy_set_header        X-Original-Host   $host;\n",
		"X-Original-URI":    "        proxy_set_header        X-Original-URI    $request_uri;\n",
	}
	for _, name := range []string{"notes", "web"} {
		block := serverBlockFor(t, string(got), name+".space.example.test")
		check := locationFor(t, block, "= /_ikigenba/check")
		for header, directive := range headers {
			if strings.Count(check, header) != 1 || !strings.Contains(check, directive) || strings.Count(block, header) != 1 {
				t.Fatalf("%s must set %s solely from the original request variable in its check subrequest: %s", name, header, block)
			}
		}
	}
	for _, name := range []string{"auth", "disabled"} {
		assertNoOriginalRequestHeaders(t, serverBlockFor(t, string(got), name+".space.example.test"), headers)
	}
	if err := os.RemoveAll(filepath.Join(root, "opt", "auth")); err != nil {
		t.Fatal(err)
	}
	plain, err := nginx.Render(context.Background(), env, "space.example.test", "web")
	if err != nil {
		t.Fatal(err)
	}
	assertNoOriginalRequestHeaders(t, string(plain), headers)
}

func assertNoOriginalRequestHeaders(t *testing.T, configuration string, headers map[string]string) {
	t.Helper()
	for header := range headers {
		if strings.Contains(configuration, header) {
			t.Fatalf("non-wired configuration names %s: %s", header, configuration)
		}
	}
}

func locationFor(t *testing.T, block, location string) string {
	t.Helper()
	needle := "    location " + location + " {\n"
	start := strings.Index(block, needle)
	if start < 0 {
		t.Fatalf("missing location %s: %s", location, block)
	}
	end := strings.Index(block[start:], "    }\n")
	if end < 0 {
		t.Fatalf("unclosed location %s", location)
	}
	return block[start : start+end+6]
}

func renderAuthenticatedServices(t *testing.T, hostName, apexApp string, authDefault bool) string {
	t.Helper()
	root := t.TempDir()
	authManifest := "app = \"auth\"\n"
	if authDefault {
		authManifest += "default = true\n"
	}
	writeManifest(t, root, "auth", authManifest)
	writeManifest(t, root, "beta", "app = \"beta\"\n")
	names := []string{"auth", "beta"}
	if !authDefault {
		writeManifest(t, root, "notes", "app = \"notes\"\ndefault = true\n")
		writeManifest(t, root, "web", "app = \"web\"\n")
		names = append(names, "notes", "web")
	}
	for _, name := range names {
		fragment := filepath.Join(root, "opt", name, "etc", "nginx.conf")
		if _, err := os.Stat(fragment); !os.IsNotExist(err) {
			t.Fatalf("fixture nginx fragment for %s: %v", name, err)
		}
	}
	got, err := nginx.Render(context.Background(), enabledEnv(root), hostName, apexApp)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	return string(got)
}

func baseForHost(hostName string, defaultRouted bool) string {
	want := strings.ReplaceAll(baseWithoutDefault, "example.test", hostName)
	if !defaultRouted {
		return want
	}
	return strings.Replace(want,
		"server_name         "+hostName+" *."+hostName+";",
		"server_name         *."+hostName+";",
		1)
}

func serverBlockFor(t *testing.T, config, serverNamePrefix string) string {
	t.Helper()
	needle := "    server_name         " + serverNamePrefix
	nameAt := strings.Index(config, needle)
	if nameAt < 0 {
		t.Fatalf("missing server_name %q\n%s", serverNamePrefix, config)
	}
	start := strings.LastIndex(config[:nameAt], "server {")
	if start < 0 {
		t.Fatalf("missing server block for %q", serverNamePrefix)
	}
	endRel := strings.Index(config[start:], "\n}\n")
	if endRel < 0 {
		t.Fatalf("unterminated server block for %q", serverNamePrefix)
	}
	return config[start : start+endRel+3]
}

// R-NVUC-NZXW
func TestRenderingOperationsRejectInvalidApexBeforeHostWork(t *testing.T) {
	t.Parallel()
	hostName := "localhost"
	apexApp := "alpha"
	_, apexErr := host.Apex(hostName)
	if apexErr == nil {
		t.Fatalf("host.Apex(%q) succeeded", hostName)
	}

	missingRoot := filepath.Join(t.TempDir(), "missing")
	executions := 0
	env := host.Env{Root: missingRoot, Execute: func(context.Context, host.Command) (host.Result, error) {
		executions++
		return host.Result{}, nil
	}}
	candidate, err := nginx.Render(context.Background(), env, hostName, apexApp)
	if candidate != nil || err == nil || err.Error() != apexErr.Error() {
		t.Fatalf("Render = (%q, %v), want (nil, %q)", candidate, err, apexErr)
	}
	for name, operation := range map[string]func() error{
		"Apply": func() error { return nginx.Apply(context.Background(), env, hostName, apexApp) },
		"Write": func() error { return nginx.Write(context.Background(), env, hostName, apexApp) },
	} {
		if err := operation(); err == nil || err.Error() != apexErr.Error() {
			t.Errorf("%s error = %v, want %q", name, err, apexErr)
		}
	}
	if executions != 0 {
		t.Fatalf("invalid apex executed %d commands", executions)
	}
	if _, err := os.Stat(missingRoot); !os.IsNotExist(err) {
		t.Fatalf("invalid apex changed host state: %v", err)
	}
}

func TestRenderReturnsNoCandidateOnDiscoveryFailure(t *testing.T) {
	// R-G0B8-HTXJ
	t.Parallel()
	missingRoot := filepath.Join(t.TempDir(), "missing")
	got, err := nginx.Render(context.Background(), host.Env{Root: missingRoot}, "example.test", "")
	if err == nil || !strings.Contains(err.Error(), "discover services") {
		t.Fatalf("Render error = %v, want discovery failure", err)
	}
	if got != nil {
		t.Fatalf("Render returned candidate %q on failure", got)
	}
}

func TestRenderRejectsManifestFailuresAndConflictingDefaults(t *testing.T) {
	// R-G1J4-VLO8
	t.Parallel()
	tests := []struct {
		name      string
		manifests map[string]string
		contains  []string
	}{
		{name: "malformed manifest", manifests: map[string]string{"broken": "default = [\n"}, contains: []string{"broken", "manifest"}},
		{name: "conflicting defaults", manifests: map[string]string{
			"alpha": "app = \"alpha\"\ndefault = true\n",
			"zeta":  "app = \"zeta\"\ndefault = true\n",
		}, contains: []string{"alpha", "zeta", "default"}},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			for name, manifest := range test.manifests {
				writeManifest(t, root, name, manifest)
			}
			executions := 0
			got, err := nginx.Render(context.Background(), host.Env{Root: root, Execute: func(context.Context, host.Command) (host.Result, error) {
				executions++
				return host.Result{}, nil
			}}, "example.test", "")
			if err == nil {
				t.Fatal("Render succeeded")
			}
			for _, substring := range test.contains {
				if !strings.Contains(err.Error(), substring) {
					t.Errorf("error %q does not identify %q", err, substring)
				}
			}
			if got != nil {
				t.Fatalf("Render returned candidate %q", got)
			}
			if executions != 0 {
				t.Fatalf("Render executed %d commands", executions)
			}
			if _, statErr := os.Stat(filepath.Join(root, "etc")); !os.IsNotExist(statErr) {
				t.Fatalf("Render changed /etc: %v", statErr)
			}
		})
	}
}

func TestApplyPropagatesRenderAndPublicationFailuresWithoutHostWork(t *testing.T) {
	// R-G0B8-HTXJ
	// R-G1J4-VLO8
	t.Parallel()

	for _, test := range []struct {
		name      string
		manifests map[string]string
		contains  []string
	}{
		{name: "malformed manifest", manifests: map[string]string{"broken": "default = [\n"}, contains: []string{"broken", "manifest"}},
		{name: "conflicting defaults", manifests: map[string]string{
			"alpha": "app = \"alpha\"\ndefault = true\n",
			"zeta":  "app = \"zeta\"\ndefault = true\n",
		}, contains: []string{"conflicting default services", "alpha", "zeta"}},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			configurationDirectory := filepath.Join(root, "etc", "nginx", "conf.d")
			mkdir(t, configurationDirectory)
			destination := filepath.Join(configurationDirectory, "ikigenba.conf")
			if err := os.WriteFile(destination, []byte("previous\n"), 0o600); err != nil {
				t.Fatal(err)
			}
			for name, manifest := range test.manifests {
				writeManifest(t, root, name, manifest)
			}
			before := snapshotTree(t, root)
			executions := 0
			err := nginx.Apply(context.Background(), host.Env{Root: root, Execute: func(context.Context, host.Command) (host.Result, error) {
				executions++
				return host.Result{}, nil
			}}, "example.test", "")
			if err == nil {
				t.Fatal("Apply succeeded")
			}
			for _, part := range test.contains {
				if !strings.Contains(err.Error(), part) {
					t.Errorf("error %q does not contain %q", err, part)
				}
			}
			if executions != 0 {
				t.Fatalf("Apply executed %d commands", executions)
			}
			if after := snapshotTree(t, root); !reflect.DeepEqual(after, before) {
				t.Fatalf("Apply changed host state\nbefore: %#v\nafter:  %#v", before, after)
			}
		})
	}

	t.Run("discovery failure", func(t *testing.T) {
		root := filepath.Join(t.TempDir(), "missing")
		executions := 0
		err := nginx.Apply(context.Background(), host.Env{Root: root, Execute: func(context.Context, host.Command) (host.Result, error) {
			executions++
			return host.Result{}, nil
		}}, "example.test", "")
		if err == nil || !strings.Contains(err.Error(), "discover services") || executions != 0 {
			t.Fatalf("Apply error = %v, executions = %d", err, executions)
		}
		if _, statErr := os.Stat(root); !os.IsNotExist(statErr) {
			t.Fatalf("Apply changed missing root: %v", statErr)
		}
	})

	t.Run("preparation failure", func(t *testing.T) {
		root := t.TempDir()
		before := snapshotTree(t, root)
		executions := 0
		err := nginx.Apply(context.Background(), host.Env{Root: root, Execute: func(context.Context, host.Command) (host.Result, error) {
			executions++
			return host.Result{}, nil
		}}, "example.test", "")
		if err == nil || !strings.Contains(err.Error(), "publish nginx configuration") || executions != 0 {
			t.Fatalf("Apply error = %v, executions = %d", err, executions)
		}
		if after := snapshotTree(t, root); !reflect.DeepEqual(after, before) {
			t.Fatalf("Apply preparation failure changed state\nbefore: %#v\nafter:  %#v", before, after)
		}
	})

	t.Run("publication failure", func(t *testing.T) {
		root := t.TempDir()
		configurationDirectory := filepath.Join(root, "etc", "nginx", "conf.d")
		mkdir(t, configurationDirectory)
		destination := filepath.Join(configurationDirectory, "ikigenba.conf")
		previous := []byte("previous configuration\n")
		if err := os.WriteFile(destination, previous, 0o600); err != nil {
			t.Fatal(err)
		}
		injectedFailure := observeNextTemporaryConfiguration(t, configurationDirectory, os.Remove)
		executions := 0
		err := nginx.Apply(context.Background(), host.Env{Root: root, Execute: func(context.Context, host.Command) (host.Result, error) {
			executions++
			return host.Result{}, nil
		}}, strings.Repeat("h", 8<<20), "")
		if injectErr := <-injectedFailure; injectErr != nil {
			t.Fatalf("inject publication failure: %v", injectErr)
		}
		if err == nil || !strings.Contains(err.Error(), "publish nginx configuration") || executions != 0 {
			t.Fatalf("Apply error = %v, executions = %d", err, executions)
		}
		assertPublishedConfiguration(t, configurationDirectory, previous, 0o600)
	})
}

// R-AMEV-4J2G
func TestApplyRejectsMissingExecutionDependencyWithoutPublishing(t *testing.T) {
	root := t.TempDir()
	configurationDirectory := filepath.Join(root, "etc", "nginx", "conf.d")
	mkdir(t, configurationDirectory)
	destination := filepath.Join(configurationDirectory, "ikigenba.conf")
	if err := os.WriteFile(destination, []byte("previous\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	err := nginx.Apply(context.Background(), host.Env{Root: root}, "example.test", "")
	if err == nil || err.Error() != "apply nginx configuration: host execution is not configured" {
		t.Fatalf("Apply error = %v", err)
	}
	assertPublishedConfiguration(t, configurationDirectory, []byte("previous\n"), 0o600)
}

// R-NIFG-GIS9
// R-NJNC-UAIY
func TestPublicationFunctionsHaveExportedContracts(t *testing.T) {
	t.Parallel()
	assertApplySignature(t, nginx.Apply)
	assertApplySignature(t, nginx.Write)
}

// R-QDHG-I39H
// R-WZO3-MVSF
func TestWritePublishesExactConfigurationWithoutCommands(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	configurationDirectory := filepath.Join(root, "etc", "nginx", "conf.d")
	mkdir(t, configurationDirectory)
	seedNginxSentinels(t, root)
	writeManifest(t, root, "service", "app = \"service\"\n")
	before := snapshotUnrelatedNginxFiles(t, root)
	executions := 0
	env := host.Env{Root: root, Execute: func(context.Context, host.Command) (host.Result, error) {
		executions++
		return host.Result{}, nil
	}}

	want := []byte(baseWithoutDefault + serviceBlock("service", 4100, false, "example.test", ""))
	createdTemporary := observeNextTemporaryConfiguration(t, configurationDirectory, nil)
	if err := nginx.Write(context.Background(), env, "example.test", ""); err != nil {
		t.Fatalf("Write call 1: %v", err)
	}
	if err := <-createdTemporary; err != nil {
		t.Fatalf("observe Write temporary file: %v", err)
	}
	assertPublishedConfiguration(t, configurationDirectory, want, 0o644)
	firstFile, err := openPublishedConfiguration(configurationDirectory)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = firstFile.Close() })
	first, err := firstFile.Stat()
	if err != nil {
		t.Fatal(err)
	}
	createdTemporary = observeNextTemporaryConfiguration(t, configurationDirectory, nil)
	if err := nginx.Write(context.Background(), env, "example.test", ""); err != nil {
		t.Fatalf("Write call 2: %v", err)
	}
	if err := <-createdTemporary; err != nil {
		t.Fatalf("observe repeated Write temporary file: %v", err)
	}
	assertPublishedConfiguration(t, configurationDirectory, want, 0o644)
	second, err := os.Stat(filepath.Join(configurationDirectory, "ikigenba.conf"))
	if err != nil {
		t.Fatal(err)
	}
	if os.SameFile(first, second) {
		t.Fatal("equal configuration was not republished")
	}
	if executions != 2 {
		t.Fatalf("Write executed %d commands, want two read-only state queries", executions)
	}
	if after := snapshotUnrelatedNginxFiles(t, root); !reflect.DeepEqual(after, before) {
		t.Fatalf("Write changed unrelated files under /etc/nginx\nbefore: %#v\nafter:  %#v", before, after)
	}
}

// R-QFX9-9MQV
func TestWriteFailuresPreserveHostStateAndCleanTemporaryFiles(t *testing.T) {
	t.Parallel()
	t.Run("render failure", func(t *testing.T) {
		root := t.TempDir()
		configurationDirectory := filepath.Join(root, "etc", "nginx", "conf.d")
		mkdir(t, configurationDirectory)
		seedNginxSentinels(t, root)
		destination := filepath.Join(configurationDirectory, "ikigenba.conf")
		if err := os.WriteFile(destination, []byte("previous"), 0o600); err != nil {
			t.Fatal(err)
		}
		writeManifest(t, root, "broken", "default = [\n")
		before := snapshotTree(t, root)
		executions := 0
		err := nginx.Write(context.Background(), host.Env{Root: root, Execute: func(context.Context, host.Command) (host.Result, error) {
			executions++
			return host.Result{}, nil
		}}, "example.test", "")
		if err == nil || !strings.Contains(err.Error(), "broken") {
			t.Fatalf("Write error = %v, want malformed service", err)
		}
		if executions != 0 {
			t.Fatalf("Write executed %d commands", executions)
		}
		if after := snapshotTree(t, root); !reflect.DeepEqual(after, before) {
			t.Fatalf("Write changed host state\nbefore: %#v\nafter:  %#v", before, after)
		}
	})

	t.Run("post-creation publication failure", func(t *testing.T) {
		root := t.TempDir()
		configurationDirectory := filepath.Join(root, "etc", "nginx", "conf.d")
		mkdir(t, configurationDirectory)
		seedNginxSentinels(t, root)
		destination := filepath.Join(configurationDirectory, "ikigenba.conf")
		before := snapshotUnrelatedNginxFiles(t, root)
		injectedFailure := observeNextTemporaryConfiguration(t, configurationDirectory, func(string) error {
			if err := os.Mkdir(destination, 0o750); err != nil {
				return err
			}
			return os.WriteFile(filepath.Join(destination, "blocks-rename"), []byte("injected"), 0o600)
		})
		// A large rendered value keeps the temporary file open long enough for the
		// watcher to install a non-file destination before the atomic rename. The
		// staged file remains in place for Write's cleanup path to remove.
		hostName := strings.Repeat("h", 8<<20)
		err := nginx.Write(context.Background(), host.Env{Root: root, Execute: func(context.Context, host.Command) (host.Result, error) {
			t.Fatal("Write executed a command")
			return host.Result{}, nil
		}}, hostName, "")
		if injectErr := <-injectedFailure; injectErr != nil {
			t.Fatalf("inject publication failure: %v", injectErr)
		}
		if err == nil || !strings.Contains(err.Error(), "publish nginx configuration") {
			t.Fatalf("Write error = %v, want publication failure", err)
		}
		assertNoTemporaryConfigurations(t, configurationDirectory)
		destinationInfo, statErr := os.Stat(destination)
		if statErr != nil {
			t.Fatalf("stat injected destination: %v", statErr)
		}
		if !destinationInfo.IsDir() || destinationInfo.Mode().Perm() != 0o750 {
			t.Fatalf("injected destination mode = %v, want directory 0750", destinationInfo.Mode())
		}
		marker := filepath.Join(destination, "blocks-rename")
		destinationRoot, openErr := os.OpenRoot(destination)
		if openErr != nil {
			t.Fatalf("open injected destination: %v", openErr)
		}
		markerContents, readErr := destinationRoot.ReadFile("blocks-rename")
		closeErr := destinationRoot.Close()
		if readErr != nil {
			t.Fatalf("read injected destination marker: %v", readErr)
		}
		if closeErr != nil {
			t.Fatalf("close injected destination: %v", closeErr)
		}
		if string(markerContents) != "injected" {
			t.Fatalf("injected destination marker = %q, want %q", markerContents, "injected")
		}
		markerInfo, statErr := os.Stat(marker)
		if statErr != nil {
			t.Fatalf("stat injected destination marker: %v", statErr)
		}
		if markerInfo.Mode().Perm() != 0o600 {
			t.Fatalf("injected destination marker mode = %04o, want 0600", markerInfo.Mode().Perm())
		}
		if after := snapshotUnrelatedNginxFiles(t, root); !reflect.DeepEqual(after, before) {
			t.Fatalf("failed Write changed unrelated files under /etc/nginx\nbefore: %#v\nafter:  %#v", before, after)
		}
	})

	t.Run("existing destination survives publication failure", func(t *testing.T) {
		root := t.TempDir()
		configurationDirectory := filepath.Join(root, "etc", "nginx", "conf.d")
		mkdir(t, configurationDirectory)
		seedNginxSentinels(t, root)
		destination := filepath.Join(configurationDirectory, "ikigenba.conf")
		previous := []byte("previous configuration\n")
		if err := os.WriteFile(destination, previous, 0o600); err != nil {
			t.Fatal(err)
		}
		before := snapshotUnrelatedNginxFiles(t, root)
		injectedFailure := observeNextTemporaryConfiguration(t, configurationDirectory, os.Remove)
		hostName := strings.Repeat("h", 8<<20)
		err := nginx.Write(context.Background(), host.Env{Root: root, Execute: func(context.Context, host.Command) (host.Result, error) {
			t.Fatal("Write executed a command")
			return host.Result{}, nil
		}}, hostName, "")
		if injectErr := <-injectedFailure; injectErr != nil {
			t.Fatalf("inject publication failure: %v", injectErr)
		}
		if err == nil || !strings.Contains(err.Error(), "publish nginx configuration") {
			t.Fatalf("Write error = %v, want publication failure", err)
		}
		assertPublishedConfiguration(t, configurationDirectory, previous, 0o600)
		if after := snapshotUnrelatedNginxFiles(t, root); !reflect.DeepEqual(after, before) {
			t.Fatalf("failed Write changed unrelated files under /etc/nginx\nbefore: %#v\nafter:  %#v", before, after)
		}
	})

	t.Run("discovery failure", func(t *testing.T) {
		root := filepath.Join(t.TempDir(), "missing")
		err := nginx.Write(context.Background(), enabledEnv(root), "example.test", "")
		if err == nil || !strings.Contains(err.Error(), "discover services") {
			t.Fatalf("Write error = %v, want discovery failure", err)
		}
		if _, statErr := os.Stat(root); !os.IsNotExist(statErr) {
			t.Fatalf("Write changed missing root: %v", statErr)
		}
	})

	t.Run("conflicting defaults", func(t *testing.T) {
		root := t.TempDir()
		configurationDirectory := filepath.Join(root, "etc", "nginx", "conf.d")
		mkdir(t, configurationDirectory)
		writeManifest(t, root, "alpha", "app = \"alpha\"\ndefault = true\n")
		writeManifest(t, root, "zeta", "app = \"zeta\"\ndefault = true\n")
		before := snapshotTree(t, root)
		err := nginx.Write(context.Background(), enabledEnv(root), "example.test", "")
		if err == nil || !strings.Contains(err.Error(), "conflicting default services") {
			t.Fatalf("Write error = %v, want conflicting defaults", err)
		}
		if after := snapshotTree(t, root); !reflect.DeepEqual(after, before) {
			t.Fatalf("Write changed host state\nbefore: %#v\nafter:  %#v", before, after)
		}
	})
}

// R-5I4M-D78O
// R-2NUY-GTYW
func TestApplyPublishesTestsAndReloadsOnEveryCall(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	configurationDirectory := filepath.Join(root, "etc", "nginx", "conf.d")
	mkdir(t, configurationDirectory)
	seedNginxSentinels(t, root)
	writeManifest(t, root, "service", "app = \"service\"\n")
	before := snapshotUnrelatedNginxFiles(t, root)
	want := []byte(baseWithoutDefault + serviceBlock("service", 4100, false, "example.test", ""))
	var commands []host.Command
	var publicationFiles []*os.File
	env := host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
		commands = append(commands, command)
		if command.Name == "systemctl" && len(command.Args) > 0 && command.Args[0] == "show" {
			return host.Result{Stdout: []byte("LoadState=loaded\nUnitFileState=enabled\n")}, nil
		}
		assertPublishedConfiguration(t, configurationDirectory, want, 0o644)
		if current := snapshotUnrelatedNginxFiles(t, root); !reflect.DeepEqual(current, before) {
			t.Fatalf("Apply changed unrelated files under /etc/nginx\nbefore: %#v\nafter:  %#v", before, current)
		}
		if command.Name == "nginx" {
			file, openErr := openPublishedConfiguration(configurationDirectory)
			if openErr != nil {
				t.Fatal(openErr)
			}
			publicationFiles = append(publicationFiles, file)
		}
		return host.Result{Stdout: []byte("successful stdout"), Stderr: []byte("successful stderr")}, nil
	}}

	for call := 1; call <= 2; call++ {
		createdTemporary := observeNextTemporaryConfiguration(t, configurationDirectory, nil)
		if err := nginx.Apply(context.Background(), env, "example.test", ""); err != nil {
			t.Fatalf("Apply call %d: %v", call, err)
		}
		if err := <-createdTemporary; err != nil {
			t.Fatalf("observe Apply temporary file on call %d: %v", call, err)
		}
	}
	wantCommands := []host.Command{
		{Name: "systemctl", Args: []string{"show", "--property=LoadState", "--property=UnitFileState", "ikigenba-service.socket"}},
		{Name: "nginx", Args: []string{"-t"}},
		{Name: "systemctl", Args: []string{"reload-or-restart", "nginx"}},
		{Name: "systemctl", Args: []string{"show", "--property=LoadState", "--property=UnitFileState", "ikigenba-service.socket"}},
		{Name: "nginx", Args: []string{"-t"}},
		{Name: "systemctl", Args: []string{"reload-or-restart", "nginx"}},
	}
	if !reflect.DeepEqual(commands, wantCommands) {
		t.Fatalf("commands = %#v, want %#v", commands, wantCommands)
	}
	if len(publicationFiles) != 2 {
		t.Fatalf("publication count = %d, want 2", len(publicationFiles))
	}
	for _, file := range publicationFiles {
		t.Cleanup(func() { _ = file.Close() })
	}
	firstPublication, err := publicationFiles[0].Stat()
	if err != nil {
		t.Fatal(err)
	}
	secondPublication, err := publicationFiles[1].Stat()
	if err != nil {
		t.Fatal(err)
	}
	if os.SameFile(firstPublication, secondPublication) {
		t.Fatal("equal configuration was not republished on every Apply")
	}
	assertPublishedConfiguration(t, configurationDirectory, want, 0o644)
	if after := snapshotUnrelatedNginxFiles(t, root); !reflect.DeepEqual(after, before) {
		t.Fatalf("Apply changed unrelated files under /etc/nginx\nbefore: %#v\nafter:  %#v", before, after)
	}
}

// R-5KKF-4QQ2
func TestApplyRestoresPreviousConfigurationWhenNginxTestFails(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		name         string
		previous     bool
		executionErr error
		exitCode     int
	}{
		{name: "previous file and nonzero status", previous: true, exitCode: 23},
		{name: "previous absence and execution error", executionErr: errors.New("cannot execute")},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			configurationDirectory := filepath.Join(root, "etc", "nginx", "conf.d")
			mkdir(t, configurationDirectory)
			destination := filepath.Join(configurationDirectory, "ikigenba.conf")
			if test.previous {
				if err := os.WriteFile(destination, []byte("previous bytes"), 0o600); err != nil {
					t.Fatal(err)
				}
			}
			var commands []host.Command
			env := host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
				commands = append(commands, command)
				return host.Result{ExitCode: test.exitCode, Stdout: []byte("test output")}, test.executionErr
			}}

			err := nginx.Apply(context.Background(), env, "example.test", "")
			if err == nil {
				t.Fatal("Apply succeeded")
			}
			var commandErr *host.CommandError
			if !errors.As(err, &commandErr) || commandErr.Label != "nginx -t" || commandErr.Result.ExitCode != test.exitCode || !errors.Is(commandErr.Err, test.executionErr) {
				t.Fatalf("error = %#v, want preserved nginx CommandError", err)
			}
			if !reflect.DeepEqual(commands, []host.Command{{Name: "nginx", Args: []string{"-t"}}}) {
				t.Fatalf("commands = %#v", commands)
			}
			if test.previous {
				assertPublishedConfiguration(t, configurationDirectory, []byte("previous bytes"), 0o600)
			} else if _, statErr := os.Stat(destination); !os.IsNotExist(statErr) {
				t.Fatalf("destination after rollback: %v", statErr)
			}
			assertNoTemporaryConfigurations(t, configurationDirectory)
		})
	}
}

func TestApplyReturnsCommandErrorsAndReportsRestorationFailure(t *testing.T) {
	// R-2P2U-ULPL R-YBI2-GUY1
	t.Parallel()
	t.Run("reload", func(t *testing.T) {
		root := t.TempDir()
		configurationDirectory := filepath.Join(root, "etc", "nginx", "conf.d")
		mkdir(t, configurationDirectory)
		cause := errors.New("reload unavailable")
		err := nginx.Apply(context.Background(), host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
			if command.Name == "nginx" && reflect.DeepEqual(command.Args, []string{"-t"}) {
				return host.Result{}, nil
			}
			if command.Name == "systemctl" && reflect.DeepEqual(command.Args, []string{"reload-or-restart", "nginx"}) {
				return host.Result{Stdout: []byte("reload output"), ExitCode: 19}, cause
			}
			t.Fatalf("unexpected command: %#v", command)
			return host.Result{}, nil
		}}, "example.test", "")
		var commandErr *host.CommandError
		if !errors.As(err, &commandErr) {
			t.Fatalf("error = %T %v, want CommandError", err, err)
		}
		if commandErr.Label != "systemctl reload-or-restart nginx" || commandErr.Result.ExitCode != 19 || string(commandErr.Result.Stdout) != "reload output" || !errors.Is(commandErr.Err, cause) {
			t.Fatalf("CommandError = %#v", commandErr)
		}
	})

	t.Run("nginx test and restoration", func(t *testing.T) {
		root := t.TempDir()
		configurationDirectory := filepath.Join(root, "etc", "nginx", "conf.d")
		mkdir(t, configurationDirectory)
		err := nginx.Apply(context.Background(), host.Env{Root: root, Execute: func(_ context.Context, _ host.Command) (host.Result, error) {
			if removeErr := os.RemoveAll(configurationDirectory); removeErr != nil {
				t.Fatal(removeErr)
			}
			if writeErr := os.WriteFile(configurationDirectory, []byte("blocks restoration"), 0o600); writeErr != nil {
				t.Fatal(writeErr)
			}
			return host.Result{ExitCode: 7, Stderr: []byte("invalid configuration")}, nil
		}}, "example.test", "")
		var commandErr *host.CommandError
		if !errors.As(err, &commandErr) || commandErr.Label != "nginx -t" || commandErr.Result.ExitCode != 7 {
			t.Fatalf("error = %#v, want nginx CommandError", err)
		}
		if !strings.Contains(err.Error(), "restore previous nginx configuration") {
			t.Fatalf("error %q does not identify restoration failure", err)
		}
	})
}

// R-YBI2-GUY1
func TestApplyPreservesExistingCommandErrorIdentity(t *testing.T) {
	existing := &host.CommandError{
		Label:  "remote nginx test",
		Result: host.Result{Stdout: []byte("captured output"), Stderr: []byte("captured detail"), ExitCode: 73},
		Err:    errors.New("remote nginx failed"),
	}
	for _, returned := range []host.Result{
		{},
		{Stdout: []byte("different output"), Stderr: []byte("different detail"), ExitCode: 19},
	} {
		t.Run(strconv.Itoa(returned.ExitCode), func(t *testing.T) {
			root := t.TempDir()
			mkdir(t, filepath.Join(root, "etc", "nginx", "conf.d"))
			env := host.Env{Root: root, Execute: func(context.Context, host.Command) (host.Result, error) {
				return returned, existing
			}}
			err := nginx.Apply(context.Background(), env, "example.test", "")
			var got *host.CommandError
			if !errors.As(err, &got) || got != existing {
				t.Fatalf("error = %#v, want original CommandError %#v", err, existing)
			}
		})
	}
}

func assertRenderSignature(t *testing.T, _ func(context.Context, host.Env, string, string) ([]byte, error)) {
	t.Helper()
}

func assertApplySignature(t *testing.T, _ func(context.Context, host.Env, string, string) error) {
	t.Helper()
}

func assertPublishedConfiguration(t *testing.T, directory string, contents []byte, mode os.FileMode) {
	t.Helper()
	destination := filepath.Join(directory, "ikigenba.conf")
	directoryFS, err := os.OpenRoot(directory)
	if err != nil {
		t.Fatalf("open configuration directory: %v", err)
	}
	got, err := directoryFS.ReadFile("ikigenba.conf")
	closeErr := directoryFS.Close()
	if err != nil {
		t.Fatalf("read published configuration: %v", err)
	}
	if closeErr != nil {
		t.Fatalf("close configuration directory: %v", closeErr)
	}
	if string(got) != string(contents) {
		t.Fatalf("published configuration = %q, want %q", got, contents)
	}
	info, err := os.Stat(destination)
	if err != nil {
		t.Fatalf("stat published configuration: %v", err)
	}
	if info.Mode().Perm() != mode {
		t.Fatalf("published mode = %04o, want %04o", info.Mode().Perm(), mode)
	}
	assertNoTemporaryConfigurations(t, directory)
}

func assertNoTemporaryConfigurations(t *testing.T, directory string) {
	t.Helper()
	entries, err := os.ReadDir(directory)
	if err != nil {
		t.Fatalf("read configuration directory: %v", err)
	}
	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), temporaryConfigurationPrefix) {
			t.Errorf("temporary configuration remains: %q", entry.Name())
		}
	}
}

func openPublishedConfiguration(directory string) (*os.File, error) {
	directoryFS, err := os.OpenRoot(directory)
	if err != nil {
		return nil, err
	}
	file, openErr := directoryFS.Open("ikigenba.conf")
	closeErr := directoryFS.Close()
	if openErr != nil {
		return nil, openErr
	}
	if closeErr != nil {
		_ = file.Close()
		return nil, closeErr
	}
	return file, nil
}

func serviceBlock(name string, _ int, defaultService bool, hostName, apexName string) string {
	return serverBlockPrefix(name, defaultService, hostName, apexName) + proxyLocation(name) + "}\n"
}

func unwiredServiceBlock(defaultService bool, hostName, apexName string) string {
	const name = "auth"
	return serverBlockPrefix(name, defaultService, hostName, apexName) +
		"    location = /check {\n        return 404;\n    }\n\n" +
		"    location = /check/open {\n        return 404;\n    }\n\n" + proxyLocation(name) + "}\n"
}

func wiredServiceBlock(name string, _ int, defaultService bool, hostName, apexName string, _ int) string {
	return serverBlockPrefix(name, defaultService, hostName, apexName) +
		"    location = /_ikigenba/check {\n" +
		"        internal;\n" +
		"        proxy_pass              http://unix:/run/ikigenba/auth.sock:/check;\n" +
		"        proxy_pass_request_body off;\n" +
		"        proxy_set_header        Content-Length \"\";\n" +
		"        proxy_set_header        X-User-Id    \"\";\n" +
		"        proxy_set_header        X-User-Email \"\";\n" +
		"        proxy_set_header        X-Request-Id $request_id;\n" +
		"        proxy_set_header        X-Original-Method $request_method;\n" +
		"        proxy_set_header        X-Original-Host   $host;\n" +
		"        proxy_set_header        X-Original-URI    $request_uri;\n" +
		"    }\n\n" +
		"    location @auth_redirect {\n" +
		"        return 302 https://auth." + hostName + "/?return=$scheme://$host$request_uri;\n" +
		"    }\n\n" +
		"    location @mcp_unauthorized {\n" +
		"        default_type text/plain;\n" +
		"        add_header   WWW-Authenticate 'Bearer realm=\"ikigenba\"' always;\n" +
		"        return       401 \"authentication required: send Authorization: Bearer <token>\\n\";\n" +
		"    }\n\n" +
		"    location @git_unauthorized {\n" +
		"        default_type text/plain;\n" +
		"        add_header   WWW-Authenticate 'Basic realm=\"ikigenba\"' always;\n" +
		"        return       401 \"authentication required: send your token as the password\\n\";\n" +
		"    }\n\n" +
		wiredProxyLocation(name, "= /mcp", "@mcp_unauthorized") + "\n" +
		wiredProxyLocation(name, "^~ /mcp/", "@mcp_unauthorized") + "\n" +
		wiredProxyLocation(name, "~ /(info/refs|git-upload-pack|git-receive-pack)$", "@git_unauthorized") + "\n" +
		wiredProxyLocation(name, "/", "@auth_redirect") + "}\n"
}

func wiredProxyLocation(name, location, unauthorized string) string {
	return "    location " + location + " {\n" +
		"        auth_request     /_ikigenba/check;\n" +
		"        auth_request_set $auth_user_id    $upstream_http_x_user_id;\n" +
		"        auth_request_set $auth_user_email $upstream_http_x_user_email;\n" +
		"        error_page       401 = " + unauthorized + ";\n\n" +
		"        proxy_pass       http://unix:/run/ikigenba/" + name + ".sock:;\n" +
		"        proxy_set_header Host              $host;\n" +
		"        proxy_set_header X-Real-IP         $remote_addr;\n" +
		"        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;\n" +
		"        proxy_set_header X-Forwarded-Proto $scheme;\n" +
		"        proxy_set_header X-Request-Id      $request_id;\n" +
		"        proxy_set_header X-User-Id         $auth_user_id;\n" +
		"        proxy_set_header X-User-Email      $auth_user_email;\n" +
		"    }\n"
}

func disabledServiceBlock(name, apexName string) string {
	const hostName = "space.example.test"
	names := name + "." + hostName
	if apexName != "" {
		names += " " + apexName
	}
	return "\nserver {\n" +
		"    listen              443 ssl;\n" +
		"    server_name         " + names + ";\n" +
		"    ssl_certificate     /etc/letsencrypt/live/" + hostName + "/fullchain.pem;\n" +
		"    ssl_certificate_key /etc/letsencrypt/live/" + hostName + "/privkey.pem;\n" +
		"    access_log          /var/log/nginx/access.log ikigenba;\n" +
		"    return              503;\n}\n"
}

func serverBlockPrefix(name string, defaultService bool, hostName, apexName string) string {
	names := name + "." + hostName
	if defaultService {
		names += " " + hostName
	}
	if apexName != "" {
		names += " " + apexName
	}
	return "\nserver {\n" +
		"    listen              443 ssl;\n" +
		"    server_name         " + names + ";\n" +
		"    ssl_certificate     /etc/letsencrypt/live/" + hostName + "/fullchain.pem;\n" +
		"    ssl_certificate_key /etc/letsencrypt/live/" + hostName + "/privkey.pem;\n" +
		"    access_log          /var/log/nginx/access.log ikigenba;\n\n" +
		"    include /opt/" + name + "/etc/nginx.conf*;\n\n"
}

func proxyLocation(name string) string {
	return "    location / {\n" +
		"        proxy_pass       http://unix:/run/ikigenba/" + name + ".sock:;\n" +
		"        proxy_set_header Host              $host;\n" +
		"        proxy_set_header X-Real-IP         $remote_addr;\n" +
		"        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;\n" +
		"        proxy_set_header X-Forwarded-Proto $scheme;\n" +
		"        proxy_set_header X-Request-Id      $request_id;\n" +
		"    }\n"
}

func writeManifest(t *testing.T, root, name, contents string) {
	t.Helper()
	path := filepath.Join(root, "opt", name, "etc", "manifest.toml")
	mkdir(t, filepath.Dir(path))
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatalf("write manifest: %v", err)
	}
}

func mkdir(t *testing.T, path string) {
	t.Helper()
	if err := os.MkdirAll(path, 0o750); err != nil {
		t.Fatalf("create directory: %v", err)
	}
}

func seedNginxSentinels(t *testing.T, root string) {
	t.Helper()
	for relative, contents := range map[string]string{
		"etc/nginx/nginx.conf":                 "main sentinel\n",
		"etc/nginx/conf.d/unrelated.conf":      "conf.d sentinel\n",
		"etc/nginx/sites-enabled/example.conf": "site sentinel\n",
	} {
		path := filepath.Join(root, relative)
		mkdir(t, filepath.Dir(path))
		if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
			t.Fatalf("write nginx sentinel %s: %v", relative, err)
		}
	}
}

func snapshotUnrelatedNginxFiles(t *testing.T, root string) map[string]treeEntry {
	t.Helper()
	nginxRoot := filepath.Join(root, "etc", "nginx")
	all := snapshotTree(t, nginxRoot)
	files := make(map[string]treeEntry)
	destination := filepath.Join("conf.d", "ikigenba.conf")
	for path, entry := range all {
		if entry.Mode.IsDir() || path == destination || strings.HasPrefix(path, destination+string(filepath.Separator)) {
			continue
		}
		files[path] = entry
	}
	return files
}

func observeNextTemporaryConfiguration(t *testing.T, directory string, inject func(string) error) <-chan error {
	t.Helper()
	fd, err := syscall.InotifyInit1(syscall.IN_CLOEXEC)
	if err != nil {
		t.Fatalf("initialize inotify: %v", err)
	}
	if _, err := syscall.InotifyAddWatch(fd, directory, syscall.IN_CREATE); err != nil {
		_ = syscall.Close(fd)
		t.Fatalf("watch configuration directory: %v", err)
	}
	result := make(chan error, 1)
	go func() {
		defer func() { _ = syscall.Close(fd) }()
		buffer := make([]byte, syscall.SizeofInotifyEvent+256)
		for {
			count, readErr := syscall.Read(fd, buffer)
			if readErr != nil {
				result <- readErr
				return
			}
			for offset := 0; offset+syscall.SizeofInotifyEvent <= count; {
				nameLength := int(binary.NativeEndian.Uint32(buffer[offset+12 : offset+16]))
				eventEnd := offset + syscall.SizeofInotifyEvent + nameLength
				if eventEnd > count {
					result <- errors.New("truncated inotify event")
					return
				}
				name := strings.TrimRight(string(buffer[offset+syscall.SizeofInotifyEvent:eventEnd]), "\x00")
				if strings.HasPrefix(name, temporaryConfigurationPrefix) {
					if inject != nil {
						result <- inject(filepath.Join(directory, name))
						return
					}
					result <- nil
					return
				}
				offset = eventEnd
			}
		}
	}()
	return result
}

type treeEntry struct {
	Mode    os.FileMode
	ModTime int64
	Data    string
}

func snapshotTree(t *testing.T, root string) map[string]treeEntry {
	t.Helper()
	rootFS, err := os.OpenRoot(root)
	if err != nil {
		t.Fatalf("open root: %v", err)
	}
	t.Cleanup(func() {
		if err := rootFS.Close(); err != nil {
			t.Errorf("close root: %v", err)
		}
	})
	snapshot := make(map[string]treeEntry)
	err = filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		item := treeEntry{Mode: info.Mode(), ModTime: info.ModTime().UnixNano()}
		if info.Mode().IsRegular() {
			contents, err := rootFS.ReadFile(relative)
			if err != nil {
				return err
			}
			item.Data = string(contents)
		}
		snapshot[relative] = item
		return nil
	})
	if err != nil {
		t.Fatalf("snapshot root: %v", err)
	}
	return snapshot
}

// R-7B6K-GZ7H R-EKHF-6EW1 R-78QR-PFQ3
func TestRenderDisabledBlocksKeepNamesAndAuthWiring(t *testing.T) {
	root := t.TempDir()
	writeManifest(t, root, "auth", "app = \"auth\"\n")
	writeManifest(t, root, "notes", "app = \"notes\"\ndefault = true\n")
	writeManifest(t, root, "web", "app = \"web\"\n")
	var queried []string
	env := host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
		if command.Name != "systemctl" || !reflect.DeepEqual(command.Args[:3], []string{"show", "--property=LoadState", "--property=UnitFileState"}) {
			t.Fatalf("unexpected command: %#v", command)
		}
		queried = append(queried, command.Args[3])
		if command.Args[3] == "ikigenba-auth.socket" || command.Args[3] == "ikigenba-web.socket" {
			return host.Result{Stdout: []byte("LoadState=loaded\nUnitFileState=disabled\n")}, nil
		}
		return host.Result{Stdout: []byte("LoadState=loaded\nUnitFileState=enabled\n")}, nil
	}}
	got, err := nginx.Render(context.Background(), env, "space.example.test", "web")
	if err != nil {
		t.Fatal(err)
	}
	want := baseForHost("space.example.test", true) +
		disabledServiceBlock("auth", "") +
		wiredServiceBlock("notes", 0, true, "space.example.test", "", 0) +
		disabledServiceBlock("web", "example.test")
	if string(got) != want {
		t.Fatalf("configuration mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
	if !reflect.DeepEqual(queried, []string{"ikigenba-auth.socket", "ikigenba-notes.socket", "ikigenba-web.socket"}) {
		t.Fatalf("query order = %#v", queried)
	}
}

// R-78QR-PFQ3 R-WUSI-3STN
func TestRenderAndUpdatePropagateDisabledQueryFailure(t *testing.T) {
	root := t.TempDir()
	writeManifest(t, root, "notes", "app = \"notes\"\n")
	mkdir(t, filepath.Join(root, "etc", "nginx", "conf.d"))
	destination := filepath.Join(root, "etc", "nginx", "conf.d", "ikigenba.conf")
	if err := os.WriteFile(destination, []byte("previous"), 0o600); err != nil {
		t.Fatal(err)
	}
	cause := errors.New("systemd unavailable")
	var commands []host.Command
	env := host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
		commands = append(commands, command)
		return host.Result{}, cause
	}}
	candidate, err := nginx.Render(context.Background(), env, "example.test", "")
	if candidate != nil || !errors.Is(err, cause) {
		t.Fatalf("Render = (%q, %v)", candidate, err)
	}
	changed, err := nginx.Update(context.Background(), env, "example.test", "")
	if changed || !errors.Is(err, cause) {
		t.Fatalf("Update = (%v, %v)", changed, err)
	}
	if len(commands) != 2 || commands[0].Name != "systemctl" || commands[1].Name != "systemctl" {
		t.Fatalf("commands = %#v", commands)
	}
	assertPublishedConfiguration(t, filepath.Dir(destination), []byte("previous"), 0o600)
}

// R-F57P-OIHU
func TestRenderSetsRequestIDAndLogsEveryAnsweringServer(t *testing.T) {
	for _, authenticated := range []bool{false, true} {
		root := t.TempDir()
		writeManifest(t, root, "notes", "app = \"notes\"\n")
		writeManifest(t, root, "disabled", "app = \"disabled\"\n")
		if authenticated {
			writeManifest(t, root, "auth", "app = \"auth\"\n")
		}
		env := host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
			if command.Args[3] == "ikigenba-disabled.socket" {
				return host.Result{Stdout: []byte("LoadState=loaded\nUnitFileState=disabled\n")}, nil
			}
			return host.Result{}, nil
		}}
		bytes, err := nginx.Render(context.Background(), env, "space.example.test", "")
		if err != nil {
			t.Fatal(err)
		}
		got := string(bytes)
		if !strings.Contains(got, "\"$http_user_agent\" $request_id';") || strings.Contains(got, "$http_x_request_id") {
			t.Fatalf("request ID log format: %s", got)
		}
		blocks := strings.Split(got, "server {\n")[1:]
		for _, block := range blocks {
			if strings.Contains(block, "ssl_reject_handshake on;") {
				if strings.Contains(block, "access_log") {
					t.Fatalf("handshake block logged: %s", block)
				}
			} else if strings.Count(block, "/var/log/nginx/access.log ikigenba;") != 1 {
				t.Fatalf("answering block missing unique access log: %s", block)
			}
		}
		notes := serverBlockFor(t, got, "notes.space.example.test")
		locations := []string{"/"}
		if authenticated {
			locations = append(locations, "= /mcp", "^~ /mcp/", "~ /(info/refs|git-upload-pack|git-receive-pack)$", "= /_ikigenba/check")
		}
		for _, location := range locations {
			section := locationFor(t, notes, location)
			want := "proxy_set_header X-Request-Id      $request_id;"
			if location == "= /_ikigenba/check" {
				want = "proxy_set_header        X-Request-Id $request_id;"
			}
			if strings.Count(section, "X-Request-Id") != 1 || !strings.Contains(section, want) {
				t.Fatalf("request ID relay: %s", section)
			}
		}
		if authenticated {
			auth := locationFor(t, serverBlockFor(t, got, "auth.space.example.test"), "/")
			if strings.Count(auth, "proxy_set_header X-Request-Id      $request_id;") != 1 {
				t.Fatalf("auth request ID relay: %s", auth)
			}
		}
	}
}

// R-WTKL-Q12Y R-WUSI-3STN
func TestUpdateChangesOnlyWhenCandidateDiffers(t *testing.T) {
	root := t.TempDir()
	mkdir(t, filepath.Join(root, "etc", "nginx", "conf.d"))
	var commands []host.Command
	env := host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
		commands = append(commands, command)
		return host.Result{}, nil
	}}
	changed, err := nginx.Update(context.Background(), env, "example.test", "")
	if err != nil || !changed {
		t.Fatalf("first Update = (%v, %v)", changed, err)
	}
	if !reflect.DeepEqual(commands, []host.Command{{Name: "nginx", Args: []string{"-t"}}, {Name: "systemctl", Args: []string{"reload-or-restart", "nginx"}}}) {
		t.Fatalf("commands = %#v", commands)
	}
	before, err := os.Stat(filepath.Join(root, "etc", "nginx", "conf.d", "ikigenba.conf"))
	if err != nil {
		t.Fatal(err)
	}
	commands = nil
	changed, err = nginx.Update(context.Background(), env, "example.test", "")
	if err != nil || changed || len(commands) != 0 {
		t.Fatalf("same Update = (%v, %v), commands %#v", changed, err, commands)
	}
	after, err := os.Stat(filepath.Join(root, "etc", "nginx", "conf.d", "ikigenba.conf"))
	if err != nil || !os.SameFile(before, after) {
		t.Fatalf("unchanged file was republished: %v", err)
	}
}

// R-WUSI-3STN
func TestUpdateRestoresOnFailedNginxTest(t *testing.T) {
	root := t.TempDir()
	directory := filepath.Join(root, "etc", "nginx", "conf.d")
	mkdir(t, directory)
	previous := []byte("previous configuration")
	if err := os.WriteFile(filepath.Join(directory, "ikigenba.conf"), previous, 0o600); err != nil {
		t.Fatal(err)
	}
	var commands []host.Command
	env := host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
		commands = append(commands, command)
		return host.Result{ExitCode: 7, Stderr: []byte("invalid nginx")}, nil
	}}
	changed, err := nginx.Update(context.Background(), env, "example.test", "")
	var commandErr *host.CommandError
	if changed || !errors.As(err, &commandErr) || commandErr.Label != "nginx -t" || commandErr.Result.ExitCode != 7 {
		t.Fatalf("Update = (%v, %v), want failed nginx test", changed, err)
	}
	if !reflect.DeepEqual(commands, []host.Command{{Name: "nginx", Args: []string{"-t"}}}) {
		t.Fatalf("commands = %#v", commands)
	}
	assertPublishedConfiguration(t, directory, previous, 0o600)
}

// R-WUSI-3STN
func TestUpdateRejectsInvalidApexBeforeHostWork(t *testing.T) {
	root := t.TempDir()
	var commands []host.Command
	env := host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
		commands = append(commands, command)
		return host.Result{}, nil
	}}
	changed, err := nginx.Update(context.Background(), env, "localhost", "notes")
	if changed || err == nil || err.Error() != "host.apex is set but host.name 'localhost' has no parent domain" || len(commands) != 0 {
		t.Fatalf("Update = (%v, %v), commands = %#v", changed, err, commands)
	}
}

// R-F7NI-G1Z8
func TestRenderMCPAndGitReservationsIgnoreManifestMCP(t *testing.T) {
	for _, manifestMCP := range []string{"", "mcp = false\n", "mcp = true\ndescription = \"Offers app tools\"\n"} {
		t.Run(strings.TrimSpace(manifestMCP), func(t *testing.T) {
			root := t.TempDir()
			writeManifest(t, root, "auth", "app = \"auth\"\n")
			writeManifest(t, root, "notes", "app = \"notes\"\n"+manifestMCP)
			writeManifest(t, root, "disabled", "app = \"disabled\"\n"+manifestMCP)
			env := host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
				if command.Args[3] == "ikigenba-disabled.socket" {
					return host.Result{Stdout: []byte("LoadState=loaded\nUnitFileState=disabled\n")}, nil
				}
				return host.Result{}, nil
			}}
			got, err := nginx.Render(context.Background(), env, "space.example.test", "")
			if err != nil {
				t.Fatal(err)
			}
			wired := serverBlockFor(t, string(got), "notes.space.example.test")
			for _, location := range []string{"@mcp_unauthorized", "@git_unauthorized", "= /mcp", "^~ /mcp/", "~ /(info/refs|git-upload-pack|git-receive-pack)$"} {
				locationFor(t, wired, location)
			}
			for _, name := range []string{"auth", "disabled"} {
				block := serverBlockFor(t, string(got), name+".space.example.test")
				for _, reserved := range []string{"/mcp", "@mcp_unauthorized", "@git_unauthorized", "info/refs", "git-upload-pack", "git-receive-pack"} {
					if strings.Contains(block, reserved) {
						t.Fatalf("%s carries reserved %q: %s", name, reserved, block)
					}
				}
			}
			if err := os.RemoveAll(filepath.Join(root, "opt", "auth")); err != nil {
				t.Fatal(err)
			}
			plain, err := nginx.Render(context.Background(), env, "space.example.test", "")
			if err != nil {
				t.Fatal(err)
			}
			for _, reserved := range []string{"/mcp", "@mcp_unauthorized", "@git_unauthorized", "info/refs", "git-upload-pack", "git-receive-pack"} {
				if strings.Contains(string(plain), reserved) {
					t.Fatalf("plain config carries reserved %q: %s", reserved, plain)
				}
			}
		})
	}
}

// R-L0DL-6GWV
func TestRenderMCP401MappingAndPathBoundaries(t *testing.T) {
	got := renderAuthenticatedServices(t, "space.example.test", "web", false)
	for _, name := range []string{"beta", "notes", "web"} {
		block := serverBlockFor(t, got, name+".space.example.test")
		for _, location := range []string{"= /mcp", "^~ /mcp/"} {
			section := locationFor(t, block, location)
			if strings.Count(section, "error_page") != 1 || !strings.Contains(section, "error_page       401 = @mcp_unauthorized;") || strings.Contains(section, "@auth_redirect") {
				t.Fatalf("MCP status mapping: %s", section)
			}
		}
		// R-ET0P-UT2W: the complete wired shape adds the two git locations.
		if strings.Count(block, "    location ") != 8 {
			t.Fatalf("unexpected location overrides: %s", block)
		}
		browser := locationFor(t, block, "/")
		if !strings.Contains(browser, "error_page       401 = @auth_redirect;") {
			t.Fatalf("ordinary paths must redirect: %s", browser)
		}
	}
}

// R-7JPV-5DEC
func TestRenderMCPUnauthorizedExactResponse(t *testing.T) {
	got := renderAuthenticatedServices(t, "space.example.test", "web", false)
	want := "    location @mcp_unauthorized {\n" +
		"        default_type text/plain;\n" +
		"        add_header   WWW-Authenticate 'Bearer realm=\"ikigenba\"' always;\n" +
		"        return       401 \"authentication required: send Authorization: Bearer <token>\\n\";\n" +
		"    }\n"
	for _, name := range []string{"beta", "notes", "web"} {
		block := serverBlockFor(t, got, name+".space.example.test")
		if section := locationFor(t, block, "@mcp_unauthorized"); section != want {
			t.Fatalf("unauthorized response = %q, want %q", section, want)
		}
	}
}

// R-7LHT-SIPW
func TestRenderGitLocationBoundariesAndCredentialRelay(t *testing.T) {
	got := renderAuthenticatedServices(t, "space.example.test", "web", false)
	for _, name := range []string{"beta", "notes", "web"} {
		block := serverBlockFor(t, got, name+".space.example.test")
		location := "~ /(info/refs|git-upload-pack|git-receive-pack)$"
		section := locationFor(t, block, location)
		if strings.Count(section, "error_page") != 1 || !strings.Contains(section, "error_page       401 = @git_unauthorized;") || strings.Contains(section, "@auth_redirect") || strings.Contains(section, "@mcp_unauthorized") {
			t.Fatalf("git status mapping: %s", section)
		}
		if !strings.Contains(section, "auth_request     /_ikigenba/check;") || !strings.Contains(section, "proxy_pass       http://unix:/run/ikigenba/"+name+".sock:;") {
			t.Fatalf("git must check and proxy the original target: %s", section)
		}
		for _, forbidden := range []string{"proxy_set_header Authorization", "proxy_pass_request_headers off", "rewrite "} {
			if strings.Contains(block, forbidden) {
				t.Fatalf("git request altered by %q: %s", forbidden, block)
			}
		}
		include := strings.Index(block, "include /opt/"+name+"/etc/nginx.conf*;")
		if include < 0 || include > strings.Index(block, "    location "+location) {
			t.Fatal("app fragment must precede generated regular expressions")
		}
		// R-ET0P-UT2W: these generated locations have this exact order.
		mcpExact := strings.Index(block, "    location = /mcp {\n")
		mcpPrefix := strings.Index(block, "    location ^~ /mcp/ {\n")
		git := strings.Index(block, "    location "+location+" {\n")
		browser := strings.Index(block, "    location / {\n")
		if mcpExact < 0 || mcpPrefix < mcpExact || git < mcpPrefix || browser < git {
			t.Fatalf("MCP exact and protected prefix must precede git, then browser: %s", block)
		}
		pattern, _, _ := strings.Cut(strings.TrimPrefix(section, "    location ~ "), " {\n")
		matcher, err := regexp.Compile(pattern)
		if err != nil {
			t.Fatalf("generated git expression: %v", err)
		}
		for _, test := range []struct {
			target string
			match  bool
		}{
			{"/notes.git/info/refs?service=git-upload-pack", true},
			{"/notes.git/git-upload-pack", true},
			{"/notes.git/git-receive-pack", true},
			{"/notes/info/refs", true},
			{"/info/refs", true},
			{"/notes.git/info/refsx", false},
			{"/notes.git/info/refs/", false},
			{"/mcpx", false},
		} {
			uriPath, _, _ := strings.Cut(test.target, "?")
			if actual := matcher.MatchString(uriPath); actual != test.match {
				t.Fatalf("git expression matches %q = %v, want %v", test.target, actual, test.match)
			}
		}
	}
}

// R-7MPQ-6AGL
func TestRenderGitUnauthorizedExactResponse(t *testing.T) {
	got := renderAuthenticatedServices(t, "space.example.test", "web", false)
	want := "    location @git_unauthorized {\n" +
		"        default_type text/plain;\n" +
		"        add_header   WWW-Authenticate 'Basic realm=\"ikigenba\"' always;\n" +
		"        return       401 \"authentication required: send your token as the password\\n\";\n" +
		"    }\n"
	for _, name := range []string{"beta", "notes", "web"} {
		block := serverBlockFor(t, got, name+".space.example.test")
		if section := locationFor(t, block, "@git_unauthorized"); section != want {
			t.Fatalf("git unauthorized response = %q, want %q", section, want)
		}
	}
}

// R-7NXM-K27A
func TestRenderLeavesUploadLimitsAndBufferingToAppFragments(t *testing.T) {
	directives := []string{"client_max_body_size", "client_body_timeout", "proxy_read_timeout", "proxy_send_timeout", "proxy_request_buffering", "proxy_buffering"}
	for _, authenticated := range []bool{false, true} {
		root := t.TempDir()
		writeManifest(t, root, "notes", "app = \"notes\"\n")
		writeManifest(t, root, "disabled", "app = \"disabled\"\n")
		if authenticated {
			writeManifest(t, root, "auth", "app = \"auth\"\n")
		}
		fragment := filepath.Join(root, "opt", "notes", "etc", "nginx.conf")
		if err := os.WriteFile(fragment, []byte("client_max_body_size 0;\nproxy_read_timeout 3600s;\nproxy_request_buffering off;\n"), 0o600); err != nil {
			t.Fatal(err)
		}
		env := host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
			if command.Args[3] == "ikigenba-disabled.socket" {
				return host.Result{Stdout: []byte("LoadState=loaded\nUnitFileState=disabled\n")}, nil
			}
			return host.Result{}, nil
		}}
		got, err := nginx.Render(context.Background(), env, "space.example.test", "")
		if err != nil {
			t.Fatal(err)
		}
		for _, directive := range directives {
			if strings.Contains(string(got), directive) {
				t.Fatalf("generated configuration sets %s: %s", directive, got)
			}
		}
	}
}

// R-78QR-PFQ3
func TestRenderOnlyQueriesRoutedSocketsReadOnly(t *testing.T) {
	root := t.TempDir()
	writeManifest(t, root, "zeta", "app = \"zeta\"\n")
	writeManifest(t, root, "alpha", "app = \"alpha\"\n")
	writeManifest(t, root, "unrouted", "default = false\n")
	before := snapshotTree(t, root)
	var commands []host.Command
	env := host.Env{Root: root, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
		commands = append(commands, command)
		return host.Result{Stdout: []byte("LoadState=not-found\nUnitFileState=\n")}, nil
	}}
	got, err := nginx.Render(context.Background(), env, "space.example.test", "")
	if err != nil {
		t.Fatal(err)
	}
	wantCommands := []host.Command{
		{Name: "systemctl", Args: []string{"show", "--property=LoadState", "--property=UnitFileState", "ikigenba-alpha.socket"}},
		{Name: "systemctl", Args: []string{"show", "--property=LoadState", "--property=UnitFileState", "ikigenba-zeta.socket"}},
	}
	if !reflect.DeepEqual(commands, wantCommands) {
		t.Fatalf("commands = %#v", commands)
	}
	if string(got) != baseForHost("space.example.test", false)+serviceBlock("alpha", 0, false, "space.example.test", "")+serviceBlock("zeta", 0, false, "space.example.test", "") {
		t.Fatalf("missing sockets should remain routed and enabled: %s", got)
	}
	if after := snapshotTree(t, root); !reflect.DeepEqual(before, after) {
		t.Fatal("Render changed files")
	}
}
