package nginx_test

import (
	"context"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"testing"

	"github.com/ikigenba/ikigenba/opsctl/internal/host"
	"github.com/ikigenba/ikigenba/opsctl/internal/nginx"
)

const baseWithoutDefault = "# Generated by opsctl. Do not edit; run 'opsctl nginx apply'.\n\n" +
	"server {\n" +
	"    listen      80 default_server;\n" +
	"    listen      [::]:80 default_server;\n" +
	"    server_name _;\n" +
	"    return      301 https://$host$request_uri;\n" +
	"}\n\n" +
	"server {\n" +
	"    listen              443 ssl default_server;\n" +
	"    listen              [::]:443 ssl default_server;\n" +
	"    ssl_reject_handshake on;\n" +
	"}\n\n" +
	"server {\n" +
	"    listen              443 ssl;\n" +
	"    server_name         example.test *.example.test;\n" +
	"    ssl_certificate     /etc/letsencrypt/live/example.test/fullchain.pem;\n" +
	"    ssl_certificate_key /etc/letsencrypt/live/example.test/privkey.pem;\n" +
	"    return              404;\n" +
	"}\n"

// R-54PQ-5Q31
func TestNginxPackageOwnsRenderingWithOnlyApprovedInternalDependencies(t *testing.T) {
	t.Parallel()
	_, currentFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("locate nginx package")
	}
	directory := filepath.Dir(currentFile)
	entries, err := os.ReadDir(directory)
	if err != nil {
		t.Fatalf("read nginx package: %v", err)
	}
	var files []*ast.File
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		file, parseErr := parser.ParseFile(token.NewFileSet(), filepath.Join(directory, entry.Name()), nil, 0)
		if parseErr != nil {
			t.Fatalf("parse %s: %v", entry.Name(), parseErr)
		}
		if file.Name.Name != "nginx" {
			t.Fatalf("%s declares package %s", entry.Name(), file.Name.Name)
		}
		files = append(files, file)
	}
	if len(files) == 0 {
		t.Fatal("internal/nginx contains no source files")
	}
	for _, file := range files {
		for _, spec := range file.Imports {
			path := strings.Trim(spec.Path.Value, `"`)
			if strings.Contains(path, "/internal/") && path != "github.com/ikigenba/ikigenba/opsctl/internal/apps" && path != "github.com/ikigenba/ikigenba/opsctl/internal/host" {
				t.Errorf("unapproved internal dependency %q", path)
			}
		}
	}
	if !filesDeclareFunction(files, "Render") {
		t.Error("internal/nginx does not own Render")
	}
}

// R-55XM-JHTQ
func TestRenderHasExportedContract(t *testing.T) {
	t.Parallel()
	assertRenderSignature(t, nginx.Render)
}

// R-5D90-U49W
func TestRenderExactBaseConfigurationWithoutDefault(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	mkdir(t, filepath.Join(root, "opt", "state-only", "state"))
	writeManifest(t, root, "disabled", "app = \"disabled\"\n")

	got, err := nginx.Render(context.Background(), host.Env{Root: root}, "example.test")
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if string(got) != baseWithoutDefault {
		t.Fatalf("configuration mismatch\ngot:\n%s\nwant:\n%s", got, baseWithoutDefault)
	}
}

// R-5C14-GCJ7
// R-5EGX-7W0L
func TestRenderRoutesServicesInDiscoveryOrderWithoutSideEffects(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeManifest(t, root, "zeta", "app = \"zeta\"\nport = 9200\n")
	writeManifest(t, root, "alpha", "app = \"alpha\"\nport = 4100\ndefault = true\n")
	writeManifest(t, root, "ignored", "app = \"ignored\"\n")
	executions := 0
	env := host.Env{Root: root, Execute: func(context.Context, host.Command) (host.Result, error) {
		executions++
		return host.Result{}, nil
	}}

	got, err := nginx.Render(context.Background(), env, "example.test")
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if executions != 0 {
		t.Fatalf("Render executed %d commands", executions)
	}
	if _, err := os.Stat(filepath.Join(root, "etc")); !os.IsNotExist(err) {
		t.Fatalf("Render changed /etc: %v", err)
	}

	want := strings.Replace(baseWithoutDefault, "server_name         example.test *.example.test;", "server_name         *.example.test;", 1) +
		serviceBlock("alpha", 4100, true) + serviceBlock("zeta", 9200, false)
	if string(got) != want {
		t.Fatalf("configuration mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
	if strings.Contains(string(got), "ignored") {
		t.Fatal("unrouted service was rendered")
	}
}

// R-G0B8-HTXJ
func TestRenderReturnsNoCandidateOnDiscoveryFailure(t *testing.T) {
	t.Parallel()
	missingRoot := filepath.Join(t.TempDir(), "missing")
	got, err := nginx.Render(context.Background(), host.Env{Root: missingRoot}, "example.test")
	if err == nil || !strings.Contains(err.Error(), "discover services") {
		t.Fatalf("Render error = %v, want discovery failure", err)
	}
	if got != nil {
		t.Fatalf("Render returned candidate %q on failure", got)
	}
}

// R-G1J4-VLO8
func TestRenderRejectsManifestFailuresAndConflictingDefaults(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name      string
		manifests map[string]string
		contains  []string
	}{
		{name: "malformed manifest", manifests: map[string]string{"broken": "port = [\n"}, contains: []string{"broken", "manifest"}},
		{name: "conflicting defaults", manifests: map[string]string{
			"alpha": "app = \"alpha\"\nport = 4100\ndefault = true\n",
			"zeta":  "app = \"zeta\"\nport = 9200\ndefault = true\n",
		}, contains: []string{"alpha", "zeta", "default"}},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			for name, manifest := range test.manifests {
				writeManifest(t, root, name, manifest)
			}
			executions := 0
			got, err := nginx.Render(context.Background(), host.Env{Root: root, Execute: func(context.Context, host.Command) (host.Result, error) {
				executions++
				return host.Result{}, nil
			}}, "example.test")
			if err == nil {
				t.Fatal("Render succeeded")
			}
			for _, substring := range test.contains {
				if !strings.Contains(err.Error(), substring) {
					t.Errorf("error %q does not identify %q", err, substring)
				}
			}
			if got != nil {
				t.Fatalf("Render returned candidate %q", got)
			}
			if executions != 0 {
				t.Fatalf("Render executed %d commands", executions)
			}
			if _, statErr := os.Stat(filepath.Join(root, "etc")); !os.IsNotExist(statErr) {
				t.Fatalf("Render changed /etc: %v", statErr)
			}
		})
	}
}

func filesDeclareFunction(files []*ast.File, name string) bool {
	for _, file := range files {
		for _, declaration := range file.Decls {
			function, ok := declaration.(*ast.FuncDecl)
			if ok && function.Name.Name == name {
				return true
			}
		}
	}
	return false
}

func assertRenderSignature(t *testing.T, _ func(context.Context, host.Env, string) ([]byte, error)) {
	t.Helper()
}

func serviceBlock(name string, port int, defaultService bool) string {
	serverNames := name + ".example.test"
	if defaultService {
		serverNames += " example.test"
	}
	return "\nserver {\n" +
		"    listen              443 ssl;\n" +
		"    server_name         " + serverNames + ";\n" +
		"    ssl_certificate     /etc/letsencrypt/live/example.test/fullchain.pem;\n" +
		"    ssl_certificate_key /etc/letsencrypt/live/example.test/privkey.pem;\n\n" +
		"    include /opt/" + name + "/etc/nginx.conf*;\n\n" +
		"    location / {\n" +
		"        proxy_pass       http://127.0.0.1:" + strconv.Itoa(port) + ";\n" +
		"        proxy_set_header Host              $host;\n" +
		"        proxy_set_header X-Real-IP         $remote_addr;\n" +
		"        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;\n" +
		"        proxy_set_header X-Forwarded-Proto $scheme;\n" +
		"    }\n" +
		"}\n"
}

func writeManifest(t *testing.T, root, name, contents string) {
	t.Helper()
	path := filepath.Join(root, "opt", name, "etc", "manifest.toml")
	mkdir(t, filepath.Dir(path))
	if err := os.WriteFile(path, []byte(contents), 0o600); err != nil {
		t.Fatalf("write manifest: %v", err)
	}
}

func mkdir(t *testing.T, path string) {
	t.Helper()
	if err := os.MkdirAll(path, 0o750); err != nil {
		t.Fatalf("create directory: %v", err)
	}
}
