-- migration: 20260808223524_allow_archived_key_reuse
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE repositories RENAME TO repositories_single_key;

CREATE TABLE repositories (
    id             INTEGER PRIMARY KEY,
    kind           TEXT NOT NULL,
    name           TEXT NOT NULL,
    owner_id       TEXT NOT NULL,
    owner_email    TEXT NOT NULL,
    default_branch TEXT NOT NULL,
    archived_at    TEXT,
    archived_path  TEXT,
    created_at     TEXT NOT NULL
);

INSERT INTO repositories
    (kind, name, owner_id, owner_email, default_branch, archived_at, archived_path, created_at)
SELECT kind, name, owner_id, owner_email, default_branch, archived_at, archived_path, created_at
FROM repositories_single_key;

DROP TABLE repositories_single_key;

CREATE UNIQUE INDEX idx_repositories_live_key
    ON repositories(kind, name) WHERE archived_at IS NULL;
CREATE INDEX idx_repositories_owner ON repositories(owner_id);
CREATE INDEX idx_repositories_archived_key ON repositories(kind, name, archived_at);

-- TODO: write the forward-only schema change below.
