-- migration: 20260808212146_rebuild_v2_store
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

DROP TABLE sessions;
DROP TABLE repos;
DROP TABLE feed_offset;

CREATE TABLE repositories (
    kind           TEXT NOT NULL,
    name           TEXT NOT NULL,
    owner_id       TEXT NOT NULL,
    owner_email    TEXT NOT NULL,
    default_branch TEXT NOT NULL,
    archived_at    TEXT,
    archived_path  TEXT,
    created_at     TEXT NOT NULL,
    PRIMARY KEY (kind, name)
);
CREATE INDEX idx_repositories_owner ON repositories(owner_id);

CREATE TABLE statuses (
    kind       TEXT NOT NULL,
    name       TEXT NOT NULL,
    sha        TEXT NOT NULL,
    check_name TEXT NOT NULL,
    state      TEXT NOT NULL,
    detail     TEXT,
    actor      TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (kind, name, sha, check_name)
);
CREATE INDEX idx_statuses_sha ON statuses(kind, name, sha);

CREATE TABLE run_tokens (
    token_sha256 TEXT PRIMARY KEY,
    kind         TEXT NOT NULL,
    name         TEXT NOT NULL,
    expires_at   TEXT NOT NULL,
    created_at   TEXT NOT NULL
);
CREATE INDEX idx_run_tokens_expiry ON run_tokens(expires_at);
