-- migration: 20260809000257_repos_consumer_cursor
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- Event-plane cursor state for the repos upstream. The table shape is the
-- eventplane/consumer SchemaSQL contract applied by sites' migration authority.
CREATE TABLE feed_offset (
  source     TEXT    PRIMARY KEY,
  cursor     TEXT,
  subscribed INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT    NOT NULL
);
