-- migration: 20260722212955_visibility_enum
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

CREATE TABLE sites_new (
    name        TEXT PRIMARY KEY,
    visibility  TEXT NOT NULL CHECK (visibility IN ('public', 'private', 'unlisted')),
    owner_id    TEXT NOT NULL,
    owner_email TEXT NOT NULL,
    source_path TEXT,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
) STRICT;

INSERT INTO sites_new (name, visibility, owner_id, owner_email, source_path, created_at, updated_at)
SELECT name,
       CASE public WHEN 1 THEN 'public' ELSE 'private' END,
       owner_id,
       owner_email,
       source_path,
       created_at,
       updated_at
FROM sites;

DROP TABLE sites;
ALTER TABLE sites_new RENAME TO sites;

CREATE INDEX idx_sites_owner ON sites(owner_id);
