-- migration: 20260609135943_add_source_path
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

-- Record the originating Dropbox subtree on each site row for the sites `sync`
-- verb (ADR Decision 2: provenance/symmetry — a site is owned by its subtree).
-- No unique index: the slug PK is already the key (unlike scripts/prompts whose
-- names repeat). The `sites` table is STRICT; a nullable TEXT add is fine.
ALTER TABLE sites ADD COLUMN source_path TEXT;
