-- migration: 20260720020849_owner_id
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

DROP TABLE sites;

CREATE TABLE sites (
    name        TEXT    PRIMARY KEY,
    public      INTEGER NOT NULL DEFAULT 0,
    owner_id    TEXT    NOT NULL,
    owner_email TEXT    NOT NULL,
    source_path TEXT,
    created_at  TEXT    NOT NULL,
    updated_at  TEXT    NOT NULL
) STRICT;

CREATE INDEX idx_sites_owner ON sites(owner_id);
