-- migration: 20260808231017_add_repo_sha_repo_seeded
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE sites ADD COLUMN repo_sha TEXT NOT NULL DEFAULT '';
ALTER TABLE sites ADD COLUMN repo_seeded INTEGER NOT NULL DEFAULT 0;
