-- migration: 20260723002205_name_slug_split
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

DROP TABLE sites;
CREATE TABLE sites (
    slug        TEXT    PRIMARY KEY,
    name        TEXT    NOT NULL,
    visibility  TEXT    NOT NULL CHECK (visibility IN ('public','private','unlisted')),
    owner_id    TEXT    NOT NULL,
    owner_email TEXT    NOT NULL,
    source_path TEXT,
    created_at  TEXT    NOT NULL,
    updated_at  TEXT    NOT NULL
) STRICT;
CREATE INDEX idx_sites_owner ON sites(owner_id);
