-- migration: 20260809191657_add_path
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE sites ADD COLUMN path TEXT NOT NULL DEFAULT '';
