-- migration: 20260811233853_create_completions
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

CREATE TABLE completions (
  id             TEXT PRIMARY KEY,
  consumer       TEXT NOT NULL,
  origin         TEXT NOT NULL,
  key            TEXT NOT NULL,
  context        TEXT NOT NULL DEFAULT '',
  name           TEXT NOT NULL,
  group_id       TEXT NOT NULL DEFAULT '',
  correlation_id TEXT NOT NULL DEFAULT '',
  attempt        INTEGER NOT NULL DEFAULT 1,
  request        TEXT NOT NULL,
  status         TEXT NOT NULL CHECK (status IN ('queued','running','done','failed')),
  result         TEXT NOT NULL DEFAULT '',
  error          TEXT NOT NULL DEFAULT '',
  usage_json     TEXT NOT NULL DEFAULT '',
  cost_usd       REAL NOT NULL DEFAULT 0,
  created_at     TEXT NOT NULL,
  started_at     TEXT NOT NULL DEFAULT '',
  finished_at    TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX completions_consumer_key ON completions (consumer, key);
CREATE INDEX completions_status_created ON completions (status, created_at);
CREATE INDEX completions_consumer_status ON completions (consumer, status, created_at);
