-- migration: 20260712192403_trigger_filters
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

DROP TABLE prompt_triggers;
CREATE TABLE prompt_triggers (
    prompt_id  TEXT NOT NULL,
    source     TEXT NOT NULL,
    filter     TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (prompt_id, filter)
);
CREATE INDEX idx_prompt_triggers_lookup ON prompt_triggers(source);

CREATE TABLE runs_new (
    id TEXT PRIMARY KEY, prompt_id TEXT NOT NULL, owner_email TEXT NOT NULL,
    prompt_name TEXT, status TEXT NOT NULL, started_at TEXT NOT NULL,
    ended_at TEXT, usage_json TEXT, error TEXT, trigger_source TEXT,
    trigger_kind TEXT, trigger_subject TEXT, trigger_event_id TEXT, log_path TEXT NOT NULL
);
INSERT INTO runs_new (id, prompt_id, owner_email, prompt_name, status, started_at, ended_at, usage_json, error, trigger_source, trigger_kind, trigger_subject, trigger_event_id, log_path)
SELECT id, prompt_id, owner_email, prompt_name, status, started_at, ended_at, usage_json, error, trigger_source, trigger_type, NULL, trigger_event_id, log_path FROM runs;
DROP TABLE runs;
ALTER TABLE runs_new RENAME TO runs;
CREATE INDEX idx_runs_prompt ON runs(prompt_id, started_at);
CREATE INDEX idx_runs_status ON runs(status);
