-- migration: 20260804154533_correlation_id
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE runs ADD COLUMN correlation_id TEXT NOT NULL DEFAULT '';
ALTER TABLE calls ADD COLUMN correlation_id TEXT NOT NULL DEFAULT '';
CREATE INDEX runs_correlation ON runs (correlation_id);
CREATE INDEX calls_correlation ON calls (correlation_id);
