-- migration: 20260621232236_backfill_provider_and_model_aliases
-- Generated by bin/new-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

-- Older prompt configs predate the explicit provider field and allowed a small
-- set of short model aliases. Backfill only rows whose JSON model can be mapped
-- unambiguously, preserving all unrelated config keys verbatim.
UPDATE prompts
SET config_json = json_set(
    config_json,
    '$.provider',
    CASE
        WHEN COALESCE(json_extract(config_json, '$.provider'), '') <> ''
            THEN json_extract(config_json, '$.provider')
        WHEN json_extract(config_json, '$.model') IN (
            'haiku',
            'sonnet',
            'opus',
            'claude-haiku-4-5',
            'claude-sonnet-4-6',
            'claude-opus-4-8'
        )
            THEN 'anthropic'
        WHEN json_extract(config_json, '$.model') LIKE 'gpt-%'
            THEN 'openai'
        WHEN json_extract(config_json, '$.model') IN (
            'pro',
            'gemini-3.1-pro',
            'gemini-3.1-pro-preview'
        )
            THEN 'google'
        WHEN json_extract(config_json, '$.model') LIKE 'gemini-%'
            THEN 'google'
        WHEN json_extract(config_json, '$.model') LIKE 'glm-%'
            THEN 'zai'
        ELSE json_extract(config_json, '$.provider')
    END,
    '$.model',
    CASE json_extract(config_json, '$.model')
        WHEN 'haiku' THEN 'claude-haiku-4-5'
        WHEN 'sonnet' THEN 'claude-sonnet-4-6'
        WHEN 'opus' THEN 'claude-opus-4-8'
        WHEN 'pro' THEN 'gemini-3.1-pro-preview'
        WHEN 'gemini-3.1-pro' THEN 'gemini-3.1-pro-preview'
        ELSE json_extract(config_json, '$.model')
    END
)
WHERE json_valid(config_json)
  AND json_type(config_json, '$.model') = 'text'
  AND (
      json_extract(config_json, '$.model') IN (
          'haiku',
          'sonnet',
          'opus',
          'pro',
          'gemini-3.1-pro'
      )
      OR (
          COALESCE(json_extract(config_json, '$.provider'), '') = ''
          AND (
              json_extract(config_json, '$.model') IN (
                  'claude-haiku-4-5',
                  'claude-sonnet-4-6',
                  'claude-opus-4-8',
                  'gemini-3.1-pro-preview'
              )
              OR json_extract(config_json, '$.model') LIKE 'gpt-%'
              OR json_extract(config_json, '$.model') LIKE 'gemini-%'
              OR json_extract(config_json, '$.model') LIKE 'glm-%'
          )
      )
  );
