-- migration: 20260809022005_retire_content_columns
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE prompts DROP COLUMN user_prompt;
ALTER TABLE prompts DROP COLUMN system_prompt;
ALTER TABLE prompts DROP COLUMN config_json;
