-- migration: 20260809010927_name_key_and_definition_sha
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE prompts ADD COLUMN name_key TEXT;
CREATE UNIQUE INDEX idx_prompts_name_key ON prompts(name_key) WHERE name_key IS NOT NULL;
ALTER TABLE runs ADD COLUMN definition_sha TEXT;
