-- migration: 20260720015430_owner_id_keying
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- TODO: write the forward-only schema change below.
DROP TABLE runs;
DROP TABLE prompts;

CREATE TABLE prompts (
    id            TEXT PRIMARY KEY,
    owner_id      TEXT NOT NULL,
    owner_email   TEXT NOT NULL,
    name          TEXT,
    user_prompt   TEXT NOT NULL,
    system_prompt TEXT,
    config_json   TEXT NOT NULL,
    source_path   TEXT,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL
);
CREATE INDEX idx_prompts_owner ON prompts(owner_id);
CREATE UNIQUE INDEX idx_prompts_source ON prompts(owner_id, source_path) WHERE source_path IS NOT NULL;

CREATE TABLE runs (
    id               TEXT PRIMARY KEY,
    prompt_id        TEXT NOT NULL,
    owner_id         TEXT NOT NULL,
    owner_email      TEXT NOT NULL,
    prompt_name      TEXT,
    status           TEXT NOT NULL,
    started_at       TEXT NOT NULL,
    ended_at         TEXT,
    usage_json       TEXT,
    error            TEXT,
    trigger_source   TEXT,
    trigger_kind     TEXT,
    trigger_subject  TEXT,
    trigger_event_id TEXT,
    log_path         TEXT NOT NULL
);
CREATE INDEX idx_runs_owner ON runs(owner_id);
CREATE INDEX idx_runs_prompt ON runs(prompt_id, started_at);
CREATE INDEX idx_runs_status ON runs(status);
