-- migration: 20260812154923_add_completion_lease
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE completions ADD COLUMN owner TEXT NOT NULL DEFAULT '';
ALTER TABLE completions ADD COLUMN lease_expires_at TEXT NOT NULL DEFAULT '';
ALTER TABLE completions ADD COLUMN reclaims INTEGER NOT NULL DEFAULT 0;
ALTER TABLE completions ADD COLUMN error_code TEXT NOT NULL DEFAULT '';

CREATE INDEX completions_lease ON completions (status, lease_expires_at);
