-- migration: 20260719185449_create_calls
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

CREATE TABLE calls (
  id            TEXT PRIMARY KEY,
  class         TEXT NOT NULL CHECK (class IN ('session','completion','embedding')),
  origin        TEXT NOT NULL,
  name          TEXT NOT NULL,
  group_id      TEXT NOT NULL DEFAULT '',
  attempt       INTEGER NOT NULL DEFAULT 1,
  owner_email   TEXT NOT NULL DEFAULT '',
  provider      TEXT NOT NULL,
  model         TEXT NOT NULL,
  input_tokens  INTEGER NOT NULL DEFAULT 0,
  output_tokens INTEGER NOT NULL DEFAULT 0,
  total_tokens  INTEGER NOT NULL DEFAULT 0,
  usage_json    TEXT NOT NULL DEFAULT '',
  cost_usd      REAL NOT NULL DEFAULT 0,
  error         TEXT NOT NULL DEFAULT '',
  request_body  TEXT,
  response_body TEXT,
  started_at    TEXT NOT NULL,
  ended_at      TEXT NOT NULL
);
CREATE INDEX calls_name_started ON calls (name, started_at);
CREATE INDEX calls_group ON calls (group_id);
CREATE INDEX calls_started ON calls (started_at);
