-- migration: 20260804115341_add_correlation_id_to_outbox
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE outbox ADD COLUMN correlation_id TEXT NOT NULL DEFAULT '';
