package cli_test

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/ikigenba/ikigenba/opsctl/internal/cli"
	"github.com/ikigenba/ikigenba/opsctl/internal/config"
	"github.com/ikigenba/ikigenba/opsctl/internal/host"
)

const wantNginxUsage = `Usage: opsctl nginx <subcommand>

Generate /etc/nginx/conf.d/ikigenba.conf from the configuration store and the
services under /opt. The file is generated, never edited; opsctl writes no
other file under /etc/nginx.

Subcommands:
  show   print the configuration opsctl would write
  apply  write the file, test it, and reload nginx

Configuration keys:
  host.name  the fully-qualified name this host answers at

A service is any /opt/<name>/ with an etc/ or state/ directory. One with an
etc/manifest.toml naming a port answers at <name>.<host.name>, and the one
whose manifest sets default answers at <host.name> as well. Its own
etc/nginx.conf, if it ships one, is included in its server block.
`

const wantNginxShow = `# Generated by opsctl. Do not edit; run 'opsctl nginx apply'.

server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    server_name _;
    return      301 https://$host$request_uri;
}

server {
    listen              443 ssl default_server;
    listen              [::]:443 ssl default_server;
    ssl_reject_handshake on;
}

server {
    listen              443 ssl;
    server_name         *.example.test;
    ssl_certificate     /etc/letsencrypt/live/example.test/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.test/privkey.pem;
    return              404;
}

server {
    listen              443 ssl;
    server_name         api.example.test example.test;
    ssl_certificate     /etc/letsencrypt/live/example.test/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.test/privkey.pem;

    include /opt/api/etc/nginx.conf*;

    location / {
        proxy_pass       http://127.0.0.1:8123;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
`

func TestNginxHelpIsExactAndInert(t *testing.T) {
	// R-58DF-B1B4
	for _, uid := range []int{0, 1000} {
		for _, option := range []string{"-h", "--help"} {
			called := false
			root := filepath.Join(t.TempDir(), "absent")
			stdout, stderr, code := invoke([]string{"nginx", option}, cli.Deps{
				Root: root, EUID: uid,
				Execute: func(context.Context, host.Command) (host.Result, error) {
					called = true
					return host.Result{}, errors.New("unexpected execution")
				},
			})
			if code != 0 || stdout != wantNginxUsage || stderr != "" || called {
				t.Fatalf("uid %d %s: exit %d stdout %q stderr %q executed %t", uid, option, code, stdout, stderr, called)
			}
			if _, err := os.Stat(root); !os.IsNotExist(err) {
				t.Fatalf("help changed host root: %v", err)
			}
		}
	}
}

func TestNginxGrammarPrecedesConfigurationAndHostWork(t *testing.T) {
	// R-54PQ-5Q31
	// R-FSNN-9FKB
	root := t.TempDir()
	writeCorruptCLIConfigFile(t, root)
	marker := filepath.Join(root, "marker")
	if err := os.WriteFile(marker, []byte("unchanged"), 0o600); err != nil {
		t.Fatal(err)
	}
	before := treeState(t, root)
	called := 0
	deps := cli.Deps{Root: root, EUID: 0, Execute: func(context.Context, host.Command) (host.Result, error) {
		called++
		return host.Result{}, nil
	}}
	tests := []struct {
		args []string
		want string
	}{
		{[]string{"nginx"}, "opsctl: no nginx subcommand given\n\nsee 'opsctl nginx --help' for usage\n"},
		{[]string{"nginx", "reload"}, "opsctl: unknown nginx subcommand 'reload'\n\nsee 'opsctl nginx --help' for usage\n"},
		{[]string{"nginx", "bad\r\nname"}, "opsctl: unknown nginx subcommand 'bad\\r\\nname'\n\nsee 'opsctl nginx --help' for usage\n"},
		{[]string{"nginx", "show", "extra"}, "opsctl: nginx show takes no arguments\n\nsee 'opsctl nginx --help' for usage\n"},
		{[]string{"nginx", "show", "--force"}, "opsctl: nginx show takes no arguments\n\nsee 'opsctl nginx --help' for usage\n"},
		{[]string{"nginx", "apply", "extra"}, "opsctl: nginx apply takes no arguments\n\nsee 'opsctl nginx --help' for usage\n"},
		{[]string{"nginx", "apply", "--force"}, "opsctl: nginx apply takes no arguments\n\nsee 'opsctl nginx --help' for usage\n"},
	}
	for _, test := range tests {
		stdout, stderr, code := invoke(test.args, deps)
		if code != 2 || stdout != "" || stderr != test.want {
			t.Errorf("%v: exit %d stdout %q stderr %q, want %q", test.args, code, stdout, stderr, test.want)
		}
	}
	if called != 0 || !reflect.DeepEqual(treeState(t, root), before) {
		t.Fatal("invalid invocation read configuration, executed a command, or changed host state")
	}
}

func TestNginxRequiresHostNameBeforeDomainWork(t *testing.T) {
	// R-5AT8-2KSI
	for _, command := range []string{"show", "apply"} {
		for _, configured := range []bool{false, true} {
			state := "missing"
			if configured {
				state = "empty"
			}
			t.Run(command+"/"+state, func(t *testing.T) {
				root := t.TempDir()
				if configured {
					if err := (config.Store{Root: root}).Set("host.name", ""); err != nil {
						t.Fatal(err)
					}
				}
				before := treeState(t, root)
				called := false
				stdout, stderr, code := invoke([]string{"nginx", command}, cli.Deps{Root: root, EUID: 0, Execute: func(context.Context, host.Command) (host.Result, error) {
					called = true
					return host.Result{}, nil
				}})
				if code != 1 || stdout != "" || stderr != "opsctl: host.name not set\n" || called {
					t.Fatalf("exit %d stdout %q stderr %q executed %t", code, stdout, stderr, called)
				}
				if after := treeState(t, root); !reflect.DeepEqual(after, before) {
					t.Fatalf("missing host.name changed state: before %#v after %#v", before, after)
				}
			})
		}
	}
}

func TestNginxConfigurationReadFailureIsDiagnosticAndReadOnly(t *testing.T) {
	// R-FTVJ-N7B0
	for _, command := range []string{"show", "apply"} {
		t.Run(command, func(t *testing.T) {
			root := t.TempDir()
			writeCorruptCLIConfigFile(t, root)
			before := treeState(t, root)
			called := false
			stdout, stderr, code := invoke([]string{"nginx", command}, cli.Deps{Root: root, EUID: 0, Execute: func(context.Context, host.Command) (host.Result, error) {
				called = true
				return host.Result{}, nil
			}})
			want := "opsctl: " + filepath.Join(root, "etc", "ikigenba", "config.json") + " is corrupt\n"
			if code != 1 || stdout != "" || stderr != want || called {
				t.Fatalf("exit %d stdout %q stderr %q executed %t, want %q", code, stdout, stderr, called, want)
			}
			if after := treeState(t, root); !reflect.DeepEqual(after, before) {
				t.Fatalf("corrupt config changed: before %#v after %#v", before, after)
			}
		})
	}
}

func TestNginxShowPrintsRenderedConfiguration(t *testing.T) {
	// R-5GWP-ZFHZ
	root := configuredNginxRoot(t)
	writeNginxManifest(t, root, "api", "app = \"api\"\nport = 8123\ndefault = true\n")
	before := treeState(t, root)
	called := false
	stdout, stderr, code := invoke([]string{"nginx", "show"}, cli.Deps{Root: root, EUID: 0, Execute: func(context.Context, host.Command) (host.Result, error) {
		called = true
		return host.Result{}, nil
	}})
	if code != 0 || stdout != wantNginxShow || stderr != "" || called {
		t.Fatalf("exit %d stdout %q stderr %q executed %t", code, stdout, stderr, called)
	}
	if after := treeState(t, root); !reflect.DeepEqual(after, before) {
		t.Fatal("nginx show changed host state")
	}
}

func TestNginxApplyUsesHostEnvironmentAndSuppressesSuccessOutput(t *testing.T) {
	// R-W6Y4-9GMN
	root := configuredNginxRoot(t)
	if err := os.MkdirAll(filepath.Join(root, "etc", "nginx", "conf.d"), 0o750); err != nil {
		t.Fatal(err)
	}
	writeNginxManifest(t, root, "api", "app = \"api\"\nport = 8123\n")
	var commands []host.Command
	stdout, stderr, code := invoke([]string{"nginx", "apply"}, cli.Deps{Root: root, EUID: 0, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
		commands = append(commands, command)
		return host.Result{Stdout: []byte("success stdout\n"), Stderr: []byte("success stderr\n")}, nil
	}})
	wantCommands := []host.Command{{Name: "nginx", Args: []string{"-t"}}, {Name: "systemctl", Args: []string{"reload", "nginx"}}}
	if code != 0 || stdout != "" || stderr != "" || !reflect.DeepEqual(commands, wantCommands) {
		t.Fatalf("exit %d stdout %q stderr %q commands %#v", code, stdout, stderr, commands)
	}
	rootFS, err := os.OpenRoot(root)
	if err != nil {
		t.Fatal(err)
	}
	contents, err := rootFS.ReadFile("etc/nginx/conf.d/ikigenba.conf")
	closeErr := rootFS.Close()
	if err != nil {
		t.Fatal(err)
	}
	if closeErr != nil {
		t.Fatal(closeErr)
	}
	if !strings.Contains(string(contents), "api.example.test") || !strings.Contains(string(contents), "127.0.0.1:8123") {
		t.Fatalf("published configuration = %q", contents)
	}
}

func TestNginxExternalFailuresUseCommandDiagnostics(t *testing.T) {
	// R-W5Q7-VOVY
	// R-W6Y4-9GMN
	for _, test := range []struct {
		name        string
		failCommand string
		result      host.Result
		err         error
		want        string
	}{
		{name: "test", failCommand: "nginx", result: host.Result{ExitCode: 23, Stdout: []byte("bad stdout\n"), Stderr: []byte("bad stderr")}, want: "opsctl: nginx -t: exit status 23\n\n> bad stdout\n> bad stderr\n"},
		{name: "reload", failCommand: "systemctl", result: host.Result{Stdout: []byte("reload stdout"), Stderr: []byte("reload stderr\n")}, err: errors.New("cannot execute"), want: "opsctl: systemctl reload nginx: cannot execute\n\n> reload stdout\n> reload stderr\n"},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := configuredNginxRoot(t)
			if err := os.MkdirAll(filepath.Join(root, "etc", "nginx", "conf.d"), 0o750); err != nil {
				t.Fatal(err)
			}
			stdout, stderr, code := invoke([]string{"nginx", "apply"}, cli.Deps{Root: root, EUID: 0, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
				if command.Name == test.failCommand {
					return test.result, test.err
				}
				return host.Result{Stdout: []byte("suppressed"), Stderr: []byte("suppressed")}, nil
			}})
			if code != 1 || stdout != "" || stderr != test.want {
				t.Fatalf("exit %d stdout %q stderr %q, want %q", code, stdout, stderr, test.want)
			}
		})
	}
}

func TestNginxStandaloneRenderAndApplyFailures(t *testing.T) {
	// R-5GWP-ZFHZ
	// R-W6Y4-9GMN
	// R-G0B8-HTXJ
	// R-G1J4-VLO8
	tests := []struct {
		name    string
		command string
		setup   func(*testing.T, string)
		want    []string
	}{
		{name: "show discovery failure", command: "show", setup: func(t *testing.T, root string) {
			if err := os.WriteFile(filepath.Join(root, "opt"), []byte("not a directory"), 0o600); err != nil {
				t.Fatal(err)
			}
		}, want: []string{"discover services", "read /opt"}},
		{name: "show malformed manifest", command: "show", setup: func(t *testing.T, root string) {
			writeNginxManifest(t, root, "broken", "port = [\n")
		}, want: []string{"broken", "manifest"}},
		{name: "apply conflicting defaults", command: "apply", setup: func(t *testing.T, root string) {
			writeNginxManifest(t, root, "alpha", "app = \"alpha\"\nport = 1\ndefault = true\n")
			writeNginxManifest(t, root, "zeta", "app = \"zeta\"\nport = 2\ndefault = true\n")
		}, want: []string{"conflicting default services", "alpha", "zeta"}},
		{name: "apply preparation failure", command: "apply", want: []string{"publish nginx configuration", "no such file or directory"}},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := configuredNginxRoot(t)
			if test.setup != nil {
				test.setup(t, root)
			}
			before := treeState(t, root)
			called := false
			stdout, stderr, code := invoke([]string{"nginx", test.command}, cli.Deps{Root: root, EUID: 0, Execute: func(context.Context, host.Command) (host.Result, error) {
				called = true
				return host.Result{}, nil
			}})
			if code != 1 || stdout != "" || called {
				t.Fatalf("exit %d stdout %q stderr %q executed %t", code, stdout, stderr, called)
			}
			for _, part := range test.want {
				if !strings.Contains(stderr, part) {
					t.Errorf("stderr %q does not contain %q", stderr, part)
				}
			}
			if after := treeState(t, root); !reflect.DeepEqual(after, before) {
				t.Fatalf("failed operation changed state: before %#v after %#v", before, after)
			}
		})
	}
}

func configuredNginxRoot(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	if err := (config.Store{Root: root}).Set("host.name", "example.test"); err != nil {
		t.Fatal(err)
	}
	return root
}

func writeNginxManifest(t *testing.T, root, name, contents string) {
	t.Helper()
	directory := filepath.Join(root, "opt", name, "etc")
	if err := os.MkdirAll(directory, 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(directory, "manifest.toml"), []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}
}
