package cli_test

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/ikigenba/ikigenba/opsctl/internal/cli"
	"github.com/ikigenba/ikigenba/opsctl/internal/config"
	"github.com/ikigenba/ikigenba/opsctl/internal/host"
	"github.com/ikigenba/ikigenba/opsctl/internal/nginx"
)

const wantNginxUsage = `Usage: opsctl nginx <subcommand>

Generate /etc/nginx/conf.d/ikigenba.conf from the configuration store, the
services under /opt, and which apps systemd reports disabled. The file is generated, never edited; opsctl writes no
other file under /etc/nginx.

Subcommands:
  show   print the configuration opsctl would write
  apply  write the file, test it, and reload nginx

Configuration keys:
  host.name  the fully-qualified name this host answers at
  host.apex  the app that answers at the parent of host.name; unset means none

A service is any /opt/<name>/ with an etc/ or state/ directory. One with an
etc/manifest.toml naming its app answers at <name>.<host.name>, proxied to
its socket /run/ikigenba/<name>.sock, and the one whose manifest sets default
answers at <host.name> as well. Its own etc/nginx.conf, if it ships one, is
included in its server block. An app whose socket unit systemd reports
disabled keeps its names, and its block answers 503. Every proxied request
carries X-Request-Id set to nginx's own request id, which also ends its
access-log line. The app
host.apex names also answers at the parent of host.name; until that app is
routed, the parent answers 404. A routed app named auth is the authenticator:
every other app's block then requires a valid session, checked against auth's
/check, while auth's own name is not gated.
`

const wantNginxShow = `# Generated by opsctl. Do not edit; run 'opsctl nginx apply'.

log_format ikigenba '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" $request_id';

server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    server_name _;
    access_log  /var/log/nginx/access.log ikigenba;
    return      301 https://$host$request_uri;
}

server {
    listen              443 ssl default_server;
    listen              [::]:443 ssl default_server;
    ssl_reject_handshake on;
}

server {
    listen              443 ssl;
    server_name         *.example.test;
    ssl_certificate     /etc/letsencrypt/live/example.test/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.test/privkey.pem;
    access_log          /var/log/nginx/access.log ikigenba;
    return              404;
}

server {
    listen              443 ssl;
    server_name         api.example.test example.test;
    ssl_certificate     /etc/letsencrypt/live/example.test/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.test/privkey.pem;
    access_log          /var/log/nginx/access.log ikigenba;

    include /opt/api/etc/nginx.conf*;

    location / {
        proxy_pass       http://unix:/run/ikigenba/api.sock:;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Request-Id      $request_id;
    }
}
`

func TestNginxHelpIsExactAndInert(t *testing.T) {
	// R-WG5P-IJXB
	for _, uid := range []int{0, 1000} {
		for _, option := range []string{"-h", "--help"} {
			called := false
			root := filepath.Join(t.TempDir(), "absent")
			stdout, stderr, code := invoke([]string{"nginx", option}, cli.Deps{
				Root: root, EUID: uid,
				Execute: func(context.Context, host.Command) (host.Result, error) {
					called = true
					return host.Result{}, errors.New("unexpected execution")
				},
			})
			if code != 0 || stdout != wantNginxUsage || stderr != "" || called {
				t.Fatalf("uid %d %s: exit %d stdout %q stderr %q executed %t", uid, option, code, stdout, stderr, called)
			}
			if _, err := os.Stat(root); !os.IsNotExist(err) {
				t.Fatalf("help changed host root: %v", err)
			}
		}
	}
}

func TestNginxGrammarPrecedesConfigurationAndHostWork(t *testing.T) {
	// R-54PQ-5Q31
	// R-FSNN-9FKB
	root := t.TempDir()
	writeCorruptCLIConfigFile(t, root)
	marker := filepath.Join(root, "marker")
	if err := os.WriteFile(marker, []byte("unchanged"), 0o600); err != nil {
		t.Fatal(err)
	}
	before := treeState(t, root)
	called := 0
	deps := cli.Deps{Root: root, EUID: 0, Execute: func(context.Context, host.Command) (host.Result, error) {
		called++
		return host.Result{}, nil
	}}
	tests := []struct {
		args []string
		want string
	}{
		{[]string{"nginx"}, "opsctl: no nginx subcommand given\n\nsee 'opsctl nginx --help' for usage\n"},
		{[]string{"nginx", "reload"}, "opsctl: unknown nginx subcommand 'reload'\n\nsee 'opsctl nginx --help' for usage\n"},
		{[]string{"nginx", "bad\r\nname"}, "opsctl: unknown nginx subcommand 'bad\\r\\nname'\n\nsee 'opsctl nginx --help' for usage\n"},
		{[]string{"nginx", "show", "extra"}, "opsctl: nginx show takes no arguments\n\nsee 'opsctl nginx --help' for usage\n"},
		{[]string{"nginx", "show", "--force"}, "opsctl: nginx show takes no arguments\n\nsee 'opsctl nginx --help' for usage\n"},
		{[]string{"nginx", "apply", "extra"}, "opsctl: nginx apply takes no arguments\n\nsee 'opsctl nginx --help' for usage\n"},
		{[]string{"nginx", "apply", "--force"}, "opsctl: nginx apply takes no arguments\n\nsee 'opsctl nginx --help' for usage\n"},
	}
	for _, test := range tests {
		stdout, stderr, code := invoke(test.args, deps)
		if code != 2 || stdout != "" || stderr != test.want {
			t.Errorf("%v: exit %d stdout %q stderr %q, want %q", test.args, code, stdout, stderr, test.want)
		}
	}
	if called != 0 || !reflect.DeepEqual(treeState(t, root), before) {
		t.Fatal("invalid invocation read configuration, executed a command, or changed host state")
	}
}

func TestNginxRequiresHostNameBeforeDomainWork(t *testing.T) {
	// R-O1UL-2JBJ
	for _, command := range []string{"show", "apply"} {
		for _, test := range []struct {
			name       string
			hostName   string
			configured bool
		}{
			{name: "missing"},
			{name: "empty", configured: true},
			{name: "normalizes empty", hostName: ".", configured: true},
		} {
			t.Run(command+"/"+test.name, func(t *testing.T) {
				root := t.TempDir()
				store := config.Store{Root: root}
				if err := store.Set("host.apex", "notes"); err != nil {
					t.Fatal(err)
				}
				if test.configured {
					if err := store.Set("host.name", test.hostName); err != nil {
						t.Fatal(err)
					}
				}
				before := treeState(t, root)
				called := false
				stdout, stderr, code := invoke([]string{"nginx", command}, cli.Deps{Root: root, EUID: 0, Execute: func(context.Context, host.Command) (host.Result, error) {
					called = true
					return host.Result{}, nil
				}})
				if code != 1 || stdout != "" || stderr != "opsctl: host.name not set\n" || called {
					t.Fatalf("exit %d stdout %q stderr %q executed %t", code, stdout, stderr, called)
				}
				if after := treeState(t, root); !reflect.DeepEqual(after, before) {
					t.Fatalf("missing host.name changed state: before %#v after %#v", before, after)
				}
			})
		}
	}
}

func TestNginxConfigurationReadFailureIsDiagnosticAndReadOnly(t *testing.T) {
	// R-NUMG-A877
	for _, command := range []string{"show", "apply"} {
		t.Run(command, func(t *testing.T) {
			root := t.TempDir()
			writeCorruptCLIConfigFile(t, root)
			before := treeState(t, root)
			called := false
			stdout, stderr, code := invoke([]string{"nginx", command}, cli.Deps{Root: root, EUID: 0, Execute: func(context.Context, host.Command) (host.Result, error) {
				called = true
				return host.Result{}, nil
			}})
			want := "opsctl: " + filepath.Join(root, "etc", "ikigenba", "config.json") + " is corrupt\n"
			if code != 1 || stdout != "" || stderr != want || called {
				t.Fatalf("exit %d stdout %q stderr %q executed %t, want %q", code, stdout, stderr, called, want)
			}
			if after := treeState(t, root); !reflect.DeepEqual(after, before) {
				t.Fatalf("corrupt config changed: before %#v after %#v", before, after)
			}
		})
	}
}

func TestNginxShowPrintsRenderedConfiguration(t *testing.T) {
	// R-5H6Q-PYQB
	// R-O1UL-2JBJ
	// R-O32H-GB28
	root := configuredNginxRoot(t)
	writeNginxManifest(t, root, "api", "app = \"api\"\ndefault = true\n")
	before := treeState(t, root)
	var commands []host.Command
	stdout, stderr, code := invoke([]string{"nginx", "show"}, cli.Deps{Root: root, EUID: 0, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
		commands = append(commands, command)
		return host.Result{Stdout: []byte("LoadState=loaded\nUnitFileState=enabled\n")}, nil
	}})
	wantCommands := []host.Command{{Name: "systemctl", Args: []string{"show", "--property=LoadState", "--property=UnitFileState", "ikigenba-api.socket"}}}
	if code != 0 || stdout != wantNginxShow || stderr != "" || !reflect.DeepEqual(commands, wantCommands) {
		t.Fatalf("exit %d stdout %q stderr %q commands %#v", code, stdout, stderr, commands)
	}
	if after := treeState(t, root); !reflect.DeepEqual(after, before) {
		t.Fatal("nginx show changed host state")
	}
}

func TestNginxApplyUsesHostEnvironmentAndSuppressesSuccessOutput(t *testing.T) {
	// R-O1UL-2JBJ
	// R-O4AD-U2SX
	root := t.TempDir()
	store := config.Store{Root: root}
	if err := store.Set("host.name", "SBX.Example.Test."); err != nil {
		t.Fatal(err)
	}
	if err := store.Set("host.apex", "api"); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(root, "etc", "nginx", "conf.d"), 0o750); err != nil {
		t.Fatal(err)
	}
	writeNginxManifest(t, root, "api", "app = \"api\"\n")
	var commands []host.Command
	stdout, stderr, code := invoke([]string{"nginx", "apply"}, cli.Deps{Root: root, EUID: 0, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
		commands = append(commands, command)
		if command.Name == "systemctl" && len(command.Args) > 0 && command.Args[0] == "show" {
			return host.Result{Stdout: []byte("LoadState=loaded\nUnitFileState=enabled\n")}, nil
		}
		return host.Result{Stdout: []byte("success stdout\n"), Stderr: []byte("success stderr\n")}, nil
	}})
	wantCommands := []host.Command{{Name: "systemctl", Args: []string{"show", "--property=LoadState", "--property=UnitFileState", "ikigenba-api.socket"}}, {Name: "nginx", Args: []string{"-t"}}, {Name: "systemctl", Args: []string{"reload-or-restart", "nginx"}}}
	if code != 0 || stdout != "" || stderr != "" || !reflect.DeepEqual(commands, wantCommands) {
		t.Fatalf("exit %d stdout %q stderr %q commands %#v", code, stdout, stderr, commands)
	}
	rootFS, err := os.OpenRoot(root)
	if err != nil {
		t.Fatal(err)
	}
	contents, err := rootFS.ReadFile("etc/nginx/conf.d/ikigenba.conf")
	closeErr := rootFS.Close()
	if err != nil {
		t.Fatal(err)
	}
	if closeErr != nil {
		t.Fatal(closeErr)
	}
	if !strings.Contains(string(contents), "server_name         api.sbx.example.test example.test;") ||
		!strings.Contains(string(contents), "http://unix:/run/ikigenba/api.sock:") {
		t.Fatalf("published configuration = %q", contents)
	}
}

func TestNginxApplyRepeatsEvenWhenConfigurationIsUnchanged(t *testing.T) {
	// R-WW0E-HKKC: standalone apply keeps Apply's unconditional test and reload.
	root := configuredNginxRoot(t)
	if err := os.MkdirAll(filepath.Join(root, "etc", "nginx", "conf.d"), 0o750); err != nil {
		t.Fatal(err)
	}
	var commands []host.Command
	deps := cli.Deps{Root: root, EUID: 0, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
		commands = append(commands, command)
		return host.Result{}, nil
	}}
	for attempt := 0; attempt < 2; attempt++ {
		stdout, stderr, code := invoke([]string{"nginx", "apply"}, deps)
		if code != 0 || stdout != "" || stderr != "" {
			t.Fatalf("apply %d: exit %d stdout %q stderr %q", attempt+1, code, stdout, stderr)
		}
	}
	want := []host.Command{
		{Name: "nginx", Args: []string{"-t"}},
		{Name: "systemctl", Args: []string{"reload-or-restart", "nginx"}},
		{Name: "nginx", Args: []string{"-t"}},
		{Name: "systemctl", Args: []string{"reload-or-restart", "nginx"}},
	}
	if !reflect.DeepEqual(commands, want) {
		t.Fatalf("repeated apply commands = %#v, want %#v", commands, want)
	}
}

func TestEnablementUpdatesNginxOnlyWhenRenderedBytesChange(t *testing.T) {
	// R-WW0E-HKKC: both lifecycle commands use Update, including its unchanged path.
	for _, test := range []struct {
		command   string
		unitState string
		active    string
	}{
		{command: "disable", unitState: "disabled", active: "inactive"},
		{command: "enable", unitState: "enabled", active: "active"},
	} {
		t.Run(test.command, func(t *testing.T) {
			root := t.TempDir()
			store := config.Store{Root: root}
			if err := store.Set("host.name", "SBX.Example.Test."); err != nil {
				t.Fatal(err)
			}
			if err := store.Set("host.apex", "api"); err != nil {
				t.Fatal(err)
			}
			writeNginxManifest(t, root, "api", "app = \"api\"\ndefault = true\n")
			for _, name := range []string{
				"opt/api/bin/api",
				"etc/systemd/system/ikigenba-api.socket",
				"etc/systemd/system/ikigenba-api.service",
			} {
				path := filepath.Join(root, filepath.FromSlash(name))
				if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(path, []byte("fixture\n"), 0o600); err != nil {
					t.Fatal(err)
				}
			}
			configurationPath := filepath.Join(root, "etc/nginx/conf.d/ikigenba.conf")
			if err := os.MkdirAll(filepath.Dir(configurationPath), 0o750); err != nil {
				t.Fatal(err)
			}
			var reloads []host.Command
			execute := func(_ context.Context, command host.Command) (host.Result, error) {
				if command.Name == "nginx" || (command.Name == "systemctl" && reflect.DeepEqual(command.Args, []string{"reload-or-restart", "nginx"})) {
					reloads = append(reloads, command)
				}
				if command.Name == "systemctl" && len(command.Args) > 0 && command.Args[0] == "show" {
					return host.Result{Stdout: []byte("LoadState=loaded\nActiveState=" + test.active + "\nUnitFileState=" + test.unitState + "\n")}, nil
				}
				if command.Name == "systemctl" && reflect.DeepEqual(command.Args, []string{"is-active", "ikigenba-api.service"}) {
					if test.active == "active" {
						return host.Result{Stdout: []byte("active\n")}, nil
					}
					return host.Result{Stdout: []byte("inactive\n"), ExitCode: 3}, nil
				}
				if strings.HasSuffix(command.Name, "/opt/api/bin/api") {
					return host.Result{Stdout: []byte("v1\n")}, nil
				}
				return host.Result{}, nil
			}
			candidate, err := nginx.Render(context.Background(), host.Env{Root: root, Execute: execute}, "sbx.example.test", "api")
			if err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(configurationPath, []byte("stale configuration\n"), 0o600); err != nil {
				t.Fatal(err)
			}
			deps := cli.Deps{Root: root, EUID: 0, Execute: execute}
			for attempt := 0; attempt < 2; attempt++ {
				stdout, stderr, code := invoke([]string{test.command, "api"}, deps)
				if code != 0 || stderr != "" || !strings.Contains(stdout, "nginx: ok (") {
					t.Fatalf("%s attempt %d: exit %d stdout %q stderr %q", test.command, attempt+1, code, stdout, stderr)
				}
				if attempt == 1 && !strings.Contains(stdout, "nginx: ok (unchanged)\n") {
					t.Fatalf("%s unchanged report = %q", test.command, stdout)
				}
			}
			wantReloads := []host.Command{
				{Name: "nginx", Args: []string{"-t"}},
				{Name: "systemctl", Args: []string{"reload-or-restart", "nginx"}},
			}
			if !reflect.DeepEqual(reloads, wantReloads) {
				t.Fatalf("%s nginx commands = %#v, want %#v", test.command, reloads, wantReloads)
			}
			rootFS, err := os.OpenRoot(root)
			if err != nil {
				t.Fatal(err)
			}
			contents, err := rootFS.ReadFile("etc/nginx/conf.d/ikigenba.conf")
			closeErr := rootFS.Close()
			if closeErr != nil {
				t.Fatal(closeErr)
			}
			if err != nil || !reflect.DeepEqual(contents, candidate) {
				t.Fatalf("%s published configuration = %q, %v", test.command, contents, err)
			}
		})
	}
}

func TestNginxApexAppIsIndependentOfManifestDefault(t *testing.T) {
	// R-5H6Q-PYQB
	root := t.TempDir()
	store := config.Store{Root: root}
	if err := store.Set("host.name", "SPACE.Example.Test."); err != nil {
		t.Fatal(err)
	}
	if err := store.Set("host.apex", "notes"); err != nil {
		t.Fatal(err)
	}
	writeNginxManifest(t, root, "api", "app = \"api\"\ndefault = true\n")
	writeNginxManifest(t, root, "notes", "app = \"notes\"\n")

	readEnabled := func(context.Context, host.Command) (host.Result, error) {
		return host.Result{Stdout: []byte("LoadState=loaded\nUnitFileState=enabled\n")}, nil
	}
	stdout, stderr, code := invoke([]string{"nginx", "show"}, cli.Deps{Root: root, EUID: 0, Execute: readEnabled})
	if code != 0 || stderr != "" {
		t.Fatalf("exit %d stderr %q", code, stderr)
	}
	for _, serverName := range []string{
		"server_name         *.space.example.test;",
		"server_name         api.space.example.test space.example.test;",
		"server_name         notes.space.example.test example.test;",
	} {
		if !strings.Contains(stdout, serverName) {
			t.Errorf("configuration does not contain %q:\n%s", serverName, stdout)
		}
	}

	emptyRoot := configuredNginxRoot(t)
	if err := (config.Store{Root: emptyRoot}).Set("host.apex", ""); err != nil {
		t.Fatal(err)
	}
	writeNginxManifest(t, emptyRoot, "api", "app = \"api\"\ndefault = true\n")
	stdout, stderr, code = invoke([]string{"nginx", "show"}, cli.Deps{Root: emptyRoot, EUID: 0, Execute: readEnabled})
	if code != 0 || stdout != wantNginxShow || stderr != "" {
		t.Fatalf("empty host.apex: exit %d stdout %q stderr %q", code, stdout, stderr)
	}
}

func TestNginxRejectsApexWithoutParentBeforeDomainWork(t *testing.T) {
	// R-O5IA-7UJM
	for _, command := range []string{"show", "apply"} {
		t.Run(command, func(t *testing.T) {
			root := t.TempDir()
			store := config.Store{Root: root}
			if err := store.Set("host.name", "LOCALHOST."); err != nil {
				t.Fatal(err)
			}
			if err := store.Set("host.apex", "notes"); err != nil {
				t.Fatal(err)
			}
			if err := os.MkdirAll(filepath.Join(root, "etc", "nginx", "conf.d"), 0o750); err != nil {
				t.Fatal(err)
			}
			configuration := filepath.Join(root, "etc", "nginx", "conf.d", "ikigenba.conf")
			if err := os.WriteFile(configuration, []byte("unchanged\n"), 0o600); err != nil {
				t.Fatal(err)
			}
			before := treeState(t, root)
			executed := false
			stdout, stderr, code := invoke([]string{"nginx", command}, cli.Deps{
				Root: root, EUID: 0,
				Execute: func(context.Context, host.Command) (host.Result, error) {
					executed = true
					return host.Result{}, nil
				},
			})
			if code != 1 || stdout != "" || stderr != "opsctl: host.apex is set but host.name 'localhost' has no parent domain\n" || executed {
				t.Fatalf("exit %d stdout %q stderr %q executed %t", code, stdout, stderr, executed)
			}
			if after := treeState(t, root); !reflect.DeepEqual(after, before) {
				t.Fatalf("refusal changed host state: before %#v after %#v", before, after)
			}
		})
	}
}

func TestNginxExternalFailuresUseCommandDiagnostics(t *testing.T) {
	// R-2P2U-ULPL
	// R-O4AD-U2SX
	for _, test := range []struct {
		name        string
		failCommand string
		result      host.Result
		err         error
		want        string
	}{
		{name: "test", failCommand: "nginx", result: host.Result{ExitCode: 23, Stdout: []byte("bad stdout\n"), Stderr: []byte("bad stderr")}, want: "opsctl: nginx -t: exit status 23\n\n> bad stdout\n> bad stderr\n"},
		{name: "reload-or-restart", failCommand: "systemctl", result: host.Result{Stdout: []byte("reload stdout"), Stderr: []byte("reload stderr\n")}, err: errors.New("cannot execute"), want: "opsctl: systemctl reload-or-restart nginx: cannot execute\n\n> reload stdout\n> reload stderr\n"},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := configuredNginxRoot(t)
			if err := os.MkdirAll(filepath.Join(root, "etc", "nginx", "conf.d"), 0o750); err != nil {
				t.Fatal(err)
			}
			stdout, stderr, code := invoke([]string{"nginx", "apply"}, cli.Deps{Root: root, EUID: 0, Execute: func(_ context.Context, command host.Command) (host.Result, error) {
				if command.Name == test.failCommand {
					return test.result, test.err
				}
				return host.Result{Stdout: []byte("suppressed"), Stderr: []byte("suppressed")}, nil
			}})
			if code != 1 || stdout != "" || stderr != test.want {
				t.Fatalf("exit %d stdout %q stderr %q, want %q", code, stdout, stderr, test.want)
			}
		})
	}
}

func TestNginxStandaloneRenderAndApplyFailures(t *testing.T) {
	// R-G0B8-HTXJ
	// R-G1J4-VLO8
	// R-O32H-GB28
	// R-O4AD-U2SX
	tests := []struct {
		name    string
		command string
		setup   func(*testing.T, string)
		want    []string
	}{
		{name: "show discovery failure", command: "show", setup: func(t *testing.T, root string) {
			if err := os.WriteFile(filepath.Join(root, "opt"), []byte("not a directory"), 0o600); err != nil {
				t.Fatal(err)
			}
		}, want: []string{"discover services", "read /opt"}},
		{name: "show malformed manifest", command: "show", setup: func(t *testing.T, root string) {
			writeNginxManifest(t, root, "broken", "app = [\n")
		}, want: []string{"broken", "manifest"}},
		{name: "apply conflicting defaults", command: "apply", setup: func(t *testing.T, root string) {
			writeNginxManifest(t, root, "alpha", "app = \"alpha\"\ndefault = true\n")
			writeNginxManifest(t, root, "zeta", "app = \"zeta\"\ndefault = true\n")
		}, want: []string{"conflicting default services", "alpha", "zeta"}},
		{name: "apply preparation failure", command: "apply", want: []string{"publish nginx configuration", "no such file or directory"}},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			root := configuredNginxRoot(t)
			if test.setup != nil {
				test.setup(t, root)
			}
			before := treeState(t, root)
			called := false
			stdout, stderr, code := invoke([]string{"nginx", test.command}, cli.Deps{Root: root, EUID: 0, Execute: func(context.Context, host.Command) (host.Result, error) {
				called = true
				return host.Result{}, nil
			}})
			if code != 1 || stdout != "" || called {
				t.Fatalf("exit %d stdout %q stderr %q executed %t", code, stdout, stderr, called)
			}
			for _, part := range test.want {
				if !strings.Contains(stderr, part) {
					t.Errorf("stderr %q does not contain %q", stderr, part)
				}
			}
			if after := treeState(t, root); !reflect.DeepEqual(after, before) {
				t.Fatalf("failed operation changed state: before %#v after %#v", before, after)
			}
		})
	}
}

func configuredNginxRoot(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	if err := (config.Store{Root: root}).Set("host.name", "EXAMPLE.Test."); err != nil {
		t.Fatal(err)
	}
	return root
}

func writeNginxManifest(t *testing.T, root, name, contents string) {
	t.Helper()
	directory := filepath.Join(root, "opt", name, "etc")
	if err := os.MkdirAll(directory, 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(directory, "manifest.toml"), []byte(contents), 0o600); err != nil {
		t.Fatal(err)
	}
}
