-- migration: 20260815004804_corrections
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE claims ADD COLUMN kind TEXT NOT NULL DEFAULT 'claim'
    CHECK (kind IN ('claim', 'correction'));

-- Claim relationships are intentionally documented rather than enforced with
-- foreign keys, matching the rest of the wiki schema. Domain stores remove
-- both-endpoint edges in the same transaction as their claims.
CREATE TABLE suppressions (
    correction TEXT NOT NULL,
    suppressed TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    PRIMARY KEY (correction, suppressed)
);

CREATE INDEX suppressions_suppressed ON suppressions (suppressed);

-- TODO: write the forward-only schema change below.
