-- migration: 20260719214051_drop_llm_calls
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

DROP TABLE llm_calls;
