-- migration: 20260811013422_scope_instructions
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE scopes ADD COLUMN instructions TEXT NOT NULL DEFAULT ''
  CHECK (length(instructions) <= 4000);
