-- migration: 20260720021521_owner_id_columns
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

CREATE TABLE jobs_owner_id (
    id          TEXT PRIMARY KEY,
    status      TEXT NOT NULL,
    owner_id    TEXT NOT NULL,
    owner_email TEXT NOT NULL,
    source_text TEXT NOT NULL DEFAULT '',
    title       TEXT NOT NULL DEFAULT '',
    tags        TEXT NOT NULL DEFAULT '[]',
    source_hash TEXT NOT NULL DEFAULT '',
    received_at TEXT NOT NULL DEFAULT '',
    started_at  TEXT NOT NULL DEFAULT '',
    finished_at TEXT NOT NULL DEFAULT '',
    error       TEXT NOT NULL DEFAULT ''
);

DROP TABLE jobs;
ALTER TABLE jobs_owner_id RENAME TO jobs;

CREATE INDEX jobs_status ON jobs (status);
CREATE INDEX jobs_pending_received ON jobs (status, received_at, id);

CREATE TABLE aliases_owner_id (
    norm_name   TEXT NOT NULL UNIQUE,
    subject_id  TEXT NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
    name        TEXT NOT NULL,
    owner_id    TEXT NOT NULL,
    owner_email TEXT NOT NULL,
    created_at  TEXT NOT NULL
);

DROP TABLE aliases;
ALTER TABLE aliases_owner_id RENAME TO aliases;

CREATE INDEX aliases_subject ON aliases (subject_id);
