-- migration: 20260811003911_porter_stemmed_pages_fts
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

DROP TABLE pages_fts;

CREATE VIRTUAL TABLE pages_fts USING fts5(
    title,
    body,
    content='pages',
    content_rowid='rowid',
    tokenize = 'porter unicode61'
);

INSERT INTO pages_fts(pages_fts) VALUES('rebuild');
