-- migration: 20260812051346_add_job_phase
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE jobs ADD COLUMN phase TEXT NOT NULL DEFAULT ''
  CHECK (phase IN ('', 'extract', 'compile'));
