-- migration: 20260812010921_create_job_staging
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

CREATE TABLE job_staging (
    job_id TEXT NOT NULL,
    stage TEXT NOT NULL,
    unit TEXT NOT NULL DEFAULT '',
    payload TEXT NOT NULL,
    units INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (job_id, stage, unit)
);
