-- migration: 20260622075642_subjects_name_id_index
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

CREATE INDEX subjects_name_id ON subjects (name, id);
