-- migration: 20260620185852_phase_02_data_model
-- Generated by bin/new-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

-- Phase-1 wiki jobs. Claims refer to this table by jobs.id; the relationship is
-- intentionally documented here rather than enforced with FOREIGN KEY.
CREATE TABLE jobs (
    id     TEXT PRIMARY KEY,
    status TEXT NOT NULL
);

CREATE INDEX jobs_status ON jobs (status);

-- Subjects are the canonical entities, events, and concepts in a wiki.
CREATE TABLE subjects (
    id        TEXT PRIMARY KEY,
    name      TEXT NOT NULL,
    norm_name TEXT NOT NULL UNIQUE,
    type      TEXT NOT NULL CHECK (type IN ('entity', 'event', 'concept'))
);

-- Claims are extracted statements about a subject, produced by a job. The
-- subject_id and job_id columns reference subjects.id and jobs.id by convention.
CREATE TABLE claims (
    id         TEXT PRIMARY KEY,
    subject_id TEXT NOT NULL,
    job_id     TEXT NOT NULL,
    body       TEXT NOT NULL
);

CREATE INDEX claims_subject ON claims (subject_id);
CREATE INDEX claims_job ON claims (job_id);

-- Pages are generated wiki pages for a subject; subject_id references
-- subjects.id by convention. FTS synchronization is performed explicitly by the
-- domain store in the same transaction as each page write.
CREATE TABLE pages (
    id         TEXT PRIMARY KEY,
    subject_id TEXT NOT NULL,
    title      TEXT NOT NULL,
    body       TEXT NOT NULL CHECK (length(body) <= 12000)
);

CREATE VIRTUAL TABLE pages_fts USING fts5(
    title,
    body,
    content='pages',
    content_rowid='rowid'
);
