-- migration: 20260812045516_create_ingest_lease
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

CREATE TABLE ingest_lease (
    scope TEXT PRIMARY KEY,
    job_id TEXT NOT NULL,
    acquired_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
);
