-- migration: 20260614050737_producer_outbox
-- Generated by bin/new-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

-- Event-plane producer outbox (design §8, §12.1). The old wiki was consumer-only
-- and carries no outbox table; the rewrite is an eventplane PRODUCER (emits
-- wiki.row_dead_lettered and wiki.ingest_refused). The DDL is OWNED by the
-- eventplane library (outbox.SchemaSQL); this file must stay byte-identical to
-- that constant — migrations_outbox_test.go asserts it. wiki's own migration
-- runner applies it so there is a single migration authority per DB file, even
-- though the schema's source of truth lives in the library.
CREATE TABLE outbox (
  seq        INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id   TEXT    NOT NULL,
  type       TEXT    NOT NULL,
  payload    TEXT    NOT NULL,
  created_at TEXT    NOT NULL
);
CREATE INDEX idx_outbox_created_at ON outbox(created_at);
