-- migration: 20260614050738_consolidated_schema
-- Generated by bin/new-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

-- Consolidated schema, transcribed table-for-table from design §12.2 (the
-- authoritative schema final). This migration does NOT re-derive the DDL from the
-- scattered prose riders; §12 is the single source. Relationships are documented
-- in comments rather than enforced with FOREIGN KEY (the suite's
-- app-level-invariant style); UNIQUE and CHECK are the constraints the design
-- relies on the database to enforce.

-- inbox — accepted-but-not-yet-integrated arrivals (§2.2)
CREATE TABLE inbox (
  id               TEXT PRIMARY KEY,            -- ULID; identifies the ARRIVAL
  owner            TEXT NOT NULL,               -- X-Owner-Email, or 'system@ikigenba' (consumer doors); attribution, never isolation
  kind             TEXT NOT NULL,               -- 'document' | 'event'
  source           TEXT NOT NULL,               -- one prefixed string: url:… dropbox:… mcp:… crm:… cron:…
  sha256           TEXT NOT NULL,               -- content identity, always computed (both storage paths)
  size             INTEGER NOT NULL,
  mime             TEXT NOT NULL DEFAULT '',
  content          BLOB,                        -- inline payload (≤ WIKI_INBOX_INLINE_MAX); NULL if spilled
  blob             INTEGER NOT NULL DEFAULT 0,  -- 1 = bytes at blobs/<aa>/<sha256>
  title            TEXT NOT NULL DEFAULT '',
  tags             TEXT NOT NULL DEFAULT '[]',  -- JSON array, caller-supplied
  received_at      INTEGER NOT NULL,            -- epoch ms; the ONLY inbox timestamp
  integrated_by    TEXT NOT NULL DEFAULT '',    -- run id; '' = pending; permanent once set (never cleared)
  ineligible_until INTEGER,                     -- nullable epoch-ms; backoff (failure policy §7)
  dead_at          INTEGER,                     -- nullable epoch-ms; dead-letter mark
  requeued_at      INTEGER                      -- nullable epoch-ms; retry-counter scope (§7)
);
CREATE INDEX inbox_integrated_by ON inbox (integrated_by);  -- pending scan; no owner-scoped variant exists
CREATE INDEX inbox_sha256        ON inbox (sha256);
-- No UNIQUE on sha256: two arrivals of identical content are two rows (§2.2).

-- subjects — the registry: every subject ever minted (§4.1)
CREATE TABLE subjects (
  id             TEXT PRIMARY KEY,          -- ULID
  type           TEXT NOT NULL,             -- 'entity' | 'event' | 'concept' (closed set, §4.1)
  kind           TEXT NOT NULL DEFAULT '',  -- freeform, prompt-anchored subtype
  canonical_name TEXT NOT NULL,             -- chosen by lint on merge
  created_by_run TEXT NOT NULL,             -- → runs.id; the run that minted this subject
  occurred_at    TEXT                       -- nullable ISO-8601 prefix; type='event' only; first-writer-wins (§4.1)
);

-- aliases — every name a subject has been known by (§4.3)
CREATE TABLE aliases (
  type       TEXT NOT NULL,   -- = subjects.type of subject_id (required by the lookup and the UNIQUE)
  norm       TEXT NOT NULL,   -- normalize(name): NFKC, casefold, trim, collapse ws, strip diacritics
  subject_id TEXT NOT NULL,   -- → subjects.id
  UNIQUE (type, norm)         -- duplicate-mint guard (§3); also the per-name lookup key
);
-- Resolution: SELECT DISTINCT subject_id FROM aliases WHERE type=? AND norm IN (keys)

-- pages — one prose page per subject (§4.1, §4.4)
CREATE TABLE pages (
  subject TEXT PRIMARY KEY,           -- = subjects.id (the page's true key)
  title   TEXT NOT NULL DEFAULT '',   -- frontmatter title; denormalized for the search verb + FTS5
  body    TEXT NOT NULL,              -- full page markdown: thin frontmatter + prose, inline [inbox-id] citations
  version INTEGER NOT NULL DEFAULT 0  -- optimistic-commit guard (§3); bumped on every write
);
-- type/kind are NOT stored here — they live on subjects (joined when a whole page is returned, §9.3).

-- pages_fts — FTS5 over page text (§9.3); kept current inside the end-of-run commit
CREATE VIRTUAL TABLE pages_fts USING fts5(
  title, body,
  content='pages', content_rowid='rowid'  -- external-content; synced in the commit (no automatic triggers)
);

-- runs — one execution of one job (§4.5); the provenance key
CREATE TABLE runs (
  id          TEXT PRIMARY KEY,           -- ULID
  job         TEXT NOT NULL,              -- 'document-pass' | 'crm-digest' | 'lint-dups' | … (renamed from 'integrator')
  caused_by   TEXT NOT NULL,              -- → inbox.id of the causing row
  status      TEXT NOT NULL,              -- 'running' | 'succeeded' | 'failed' | 'crashed'
  started_at  INTEGER NOT NULL,           -- epoch ms
  finished_at INTEGER,                    -- epoch ms; nullable until terminal
  usage       TEXT,                       -- token/cost accounting (JSON); nullable
  conflicts   INTEGER NOT NULL DEFAULT 0, -- optimistic-commit retries within this run (§3)
  error       TEXT NOT NULL DEFAULT ''
);
CREATE INDEX runs_caused_by ON runs (caused_by);  -- provenance + the §7 since-requeue COUNT(*)

-- dup_flags — candidate duplicate pairs (§6); evidence, never a verdict
CREATE TABLE dup_flags (
  subject_a        TEXT NOT NULL,                -- always the smaller ULID
  subject_b        TEXT NOT NULL,                -- always the larger ULID
  status           TEXT NOT NULL DEFAULT 'open', -- 'open' | 'merged' | 'dismissed'
  judged_version_a INTEGER,                      -- nullable; pages.version of A at last judge (re-judge gate, §6)
  judged_version_b INTEGER,                      -- nullable; pages.version of B at last judge
  run_id           TEXT,                         -- nullable; the lint-dups run that decided merge/dismiss
  UNIQUE (subject_a, subject_b),                 -- one row per pair; FlagDup is the only inserter
  CHECK (subject_a < subject_b)                  -- mis-ordered insert crashes, never silently duplicates
);

-- stale_notes — staleness side channel (§6); flag-only writers, lint-stale repairs
CREATE TABLE stale_notes (
  id      TEXT PRIMARY KEY,             -- ULID (addresses each note for its per-note disposition)
  subject TEXT NOT NULL,                -- whose page looks stale
  note    TEXT NOT NULL,                -- what the writer observed (a sentence or two)
  cites   TEXT NOT NULL,                -- inbox id(s) of the new evidence that makes the repair legal
  run_id  TEXT NOT NULL,                -- → runs.id; who noticed
  status  TEXT NOT NULL DEFAULT 'open'  -- 'open' | 'repaired' | 'dismissed'
);
-- No UNIQUE: notes aren't canonical pairs; per-subject batching merges duplicates at repair time (§6).

-- page_vectors — embedding lane (§9.3); async catch-up, brute-force cosine in Go
CREATE TABLE page_vectors (
  subject          TEXT PRIMARY KEY,  -- = pages.subject
  embedded_version INTEGER NOT NULL,  -- pages.version at embed time (drives the catch-up work list only)
  model            TEXT NOT NULL,     -- provider/model id + dims, e.g. text-embedding-3-large@1024
  vector           BLOB NOT NULL      -- float32 array
);

-- asks — read-side ask accounting (§9.2); deliberately separate from runs
CREATE TABLE asks (
  id          TEXT PRIMARY KEY,  -- ULID
  owner       TEXT NOT NULL,     -- who asked (attribution; golden candidates)
  question    TEXT NOT NULL,
  status      TEXT NOT NULL,     -- 'running' | 'succeeded' | 'failed' | 'crashed'
  started_at  INTEGER NOT NULL,  -- epoch ms
  finished_at INTEGER,
  usage       TEXT,              -- token/cost accounting (JSON); nullable
  error       TEXT NOT NULL DEFAULT ''
);
