-- migration: 20260812053158_add_job_liveness
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE jobs ADD COLUMN deadline_at TEXT NOT NULL DEFAULT '';
