-- migration: 20260810003052_scope_registry
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- Scopes are logical content partitions. Relationships to scopes.name are
-- intentionally documented rather than enforced with foreign keys.
CREATE TABLE scopes (
    name       TEXT PRIMARY KEY,
    visibility TEXT NOT NULL DEFAULT 'private',
    created_at INTEGER NOT NULL,
    CHECK (visibility IN ('private', 'public'))
);

INSERT INTO scopes (name, visibility, created_at)
VALUES ('default', 'private', unixepoch());

-- Existing content cannot be assigned to a scope without guessing, so rebuild
-- the content schema empty. Defaults keep existing internal callers on the
-- reserved scope while their public seams become explicitly scoped.
DROP TRIGGER subjects_restrict_claims_before_delete;
DROP TABLE pages_fts;
DROP TABLE page_embeddings;
DROP TABLE aliases;
DROP TABLE subject_merges;
DROP TABLE claims;
DROP TABLE pages;
DROP TABLE subjects;
DROP TABLE jobs;

CREATE TABLE jobs (
    id             TEXT PRIMARY KEY,
    scope          TEXT NOT NULL DEFAULT 'default',
    status         TEXT NOT NULL,
    owner_id       TEXT NOT NULL,
    owner_email    TEXT NOT NULL,
    source_text    TEXT NOT NULL DEFAULT '',
    title          TEXT NOT NULL DEFAULT '',
    tags           TEXT NOT NULL DEFAULT '[]',
    source_hash    TEXT NOT NULL DEFAULT '',
    received_at    TEXT NOT NULL DEFAULT '',
    started_at     TEXT NOT NULL DEFAULT '',
    finished_at    TEXT NOT NULL DEFAULT '',
    error          TEXT NOT NULL DEFAULT '',
    correlation_id TEXT NOT NULL DEFAULT ''
);

CREATE INDEX jobs_status ON jobs (status);
CREATE INDEX jobs_pending_received ON jobs (status, received_at, id);

CREATE TABLE subjects (
    id        TEXT PRIMARY KEY,
    scope     TEXT NOT NULL DEFAULT 'default',
    name      TEXT NOT NULL,
    norm_name TEXT NOT NULL,
    type      TEXT NOT NULL CHECK (type IN ('entity', 'event', 'concept')),
    UNIQUE (scope, norm_name)
);

CREATE INDEX subjects_name_id ON subjects (name, id);

CREATE TABLE claims (
    id         TEXT PRIMARY KEY,
    subject_id TEXT NOT NULL,
    job_id     TEXT NOT NULL,
    body       TEXT NOT NULL
);

CREATE INDEX claims_subject ON claims (subject_id);
CREATE INDEX claims_job ON claims (job_id);

CREATE TABLE pages (
    id         TEXT PRIMARY KEY,
    subject_id TEXT NOT NULL,
    title      TEXT NOT NULL,
    body       TEXT NOT NULL CHECK (length(body) <= 12000)
);

CREATE VIRTUAL TABLE pages_fts USING fts5(
    title,
    body,
    content='pages',
    content_rowid='rowid'
);

CREATE TABLE page_embeddings (
    subject_id   TEXT PRIMARY KEY,
    model        TEXT NOT NULL,
    dims         INTEGER NOT NULL CHECK (dims >= 0),
    vec          BLOB NOT NULL CHECK (length(vec) = dims * 4),
    content_hash TEXT NOT NULL,
    updated_at   INTEGER NOT NULL
);

CREATE TABLE aliases (
    scope       TEXT NOT NULL DEFAULT 'default',
    norm_name   TEXT NOT NULL,
    subject_id  TEXT NOT NULL REFERENCES subjects(id) ON DELETE RESTRICT,
    name        TEXT NOT NULL,
    owner_id    TEXT NOT NULL,
    owner_email TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    UNIQUE (scope, norm_name)
);

CREATE INDEX aliases_subject ON aliases (subject_id);

CREATE TABLE subject_merges (
    job_id          TEXT PRIMARY KEY REFERENCES jobs(id) ON DELETE CASCADE,
    from_subject_id TEXT NOT NULL,
    to_subject_id   TEXT NOT NULL,
    CHECK (from_subject_id <> to_subject_id)
);

CREATE INDEX subject_merges_from_to ON subject_merges (from_subject_id, to_subject_id);

CREATE TRIGGER subjects_restrict_claims_before_delete
BEFORE DELETE ON subjects
WHEN EXISTS (SELECT 1 FROM claims WHERE subject_id = OLD.id)
BEGIN
    SELECT RAISE(ABORT, 'subject has claims');
END;
