-- migration: 20260622001058_drop_pages_fts
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

DROP TABLE IF EXISTS pages_fts;
