-- migration: 20260815011110_add_match_job_phase
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

CREATE TABLE jobs_match_phase (
    id             TEXT PRIMARY KEY,
    scope          TEXT NOT NULL DEFAULT 'default',
    status         TEXT NOT NULL,
    owner_id       TEXT NOT NULL,
    owner_email    TEXT NOT NULL,
    source_text    TEXT NOT NULL DEFAULT '',
    title          TEXT NOT NULL DEFAULT '',
    tags           TEXT NOT NULL DEFAULT '[]',
    source_hash    TEXT NOT NULL DEFAULT '',
    received_at    TEXT NOT NULL DEFAULT '',
    started_at     TEXT NOT NULL DEFAULT '',
    finished_at    TEXT NOT NULL DEFAULT '',
    error          TEXT NOT NULL DEFAULT '',
    correlation_id TEXT NOT NULL DEFAULT '',
    phase          TEXT NOT NULL DEFAULT '' CHECK (phase IN ('', 'extract', 'match', 'compile')),
    deadline_at    TEXT NOT NULL DEFAULT ''
);

INSERT INTO jobs_match_phase
SELECT id, scope, status, owner_id, owner_email, source_text, title, tags,
       source_hash, received_at, started_at, finished_at, error,
       correlation_id, phase, deadline_at
FROM jobs;

CREATE TABLE subject_merges_match_phase (
    job_id          TEXT PRIMARY KEY REFERENCES jobs_match_phase(id) ON DELETE CASCADE,
    from_subject_id TEXT NOT NULL,
    to_subject_id   TEXT NOT NULL,
    CHECK (from_subject_id <> to_subject_id)
);

INSERT INTO subject_merges_match_phase SELECT * FROM subject_merges;
DROP TABLE subject_merges;
DROP TABLE jobs;
ALTER TABLE jobs_match_phase RENAME TO jobs;
ALTER TABLE subject_merges_match_phase RENAME TO subject_merges;

CREATE INDEX jobs_status ON jobs (status);
CREATE INDEX jobs_pending_received ON jobs (status, received_at, id);
CREATE INDEX subject_merges_from_to ON subject_merges (from_subject_id, to_subject_id);
