-- migration: 20260620201638_phase_07_ingest_jobs
-- Generated by bin/new-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

ALTER TABLE jobs ADD COLUMN owner TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN source_text TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN title TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';
ALTER TABLE jobs ADD COLUMN source_hash TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN received_at TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN started_at TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN finished_at TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN error TEXT NOT NULL DEFAULT '';

CREATE INDEX jobs_pending_received
	ON jobs (status, received_at, id);
