-- migration: 20260804114457_outbox_correlation_id
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE outbox ADD COLUMN correlation_id TEXT NOT NULL DEFAULT '';
