-- migration: 20260817170912_contact_tokens
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- TODO: write the forward-only schema change below.
CREATE TABLE contact_tokens (
    id          TEXT PRIMARY KEY,
    contact_id  TEXT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    token       TEXT NOT NULL,
    campaign    TEXT NULL,
    created_at  TEXT NOT NULL,
    deleted_at  TEXT NULL
);

CREATE UNIQUE INDEX uq_contact_tokens_token_live
    ON contact_tokens(token) WHERE deleted_at IS NULL;

CREATE INDEX idx_contact_tokens_contact_live
    ON contact_tokens(contact_id) WHERE deleted_at IS NULL;
