-- migration: 20260817170129_sales_funnel_vocabularies
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- Keep copies of every table that references contacts or deals. Rebuilding the
-- complete FK boundary avoids relying on connection-level PRAGMA changes (which
-- SQLite ignores once the migration transaction has begun).
CREATE TEMP TABLE phase24_contact_emails AS SELECT * FROM contact_emails;
CREATE TEMP TABLE phase24_contact_phones AS SELECT * FROM contact_phones;
CREATE TEMP TABLE phase24_contact_tags AS SELECT * FROM contact_tags;
CREATE TEMP TABLE phase24_deal_contacts AS SELECT * FROM deal_contacts;
CREATE TEMP TABLE phase24_interactions AS SELECT * FROM interactions;
CREATE TEMP TABLE phase24_tasks AS SELECT * FROM tasks;

DROP TABLE contact_emails;
DROP TABLE contact_phones;
DROP TABLE contact_tags;
DROP TABLE deal_contacts;
DROP TABLE interactions;
DROP TABLE tasks;

CREATE TABLE contacts_new (
    id            TEXT PRIMARY KEY,
    given_name    TEXT NULL,
    family_name   TEXT NULL,
    display_name  TEXT NOT NULL,
    org_id        TEXT NULL REFERENCES organizations(id),
    title         TEXT NULL,
    lifecycle     TEXT NOT NULL DEFAULT 'prospect'
        CHECK (lifecycle IN ('prospect','customer')),
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    deleted_at    TEXT NULL
);
INSERT INTO contacts_new
    (id, given_name, family_name, display_name, org_id, title, lifecycle, created_at, updated_at, deleted_at)
SELECT id, given_name, family_name, display_name, org_id, title,
       CASE lifecycle
           WHEN 'customer' THEN 'customer'
           ELSE 'prospect'
       END,
       created_at, updated_at, deleted_at
FROM contacts;

CREATE TABLE deals_new (
    id            TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    org_id        TEXT NULL REFERENCES organizations(id),
    stage         TEXT NOT NULL DEFAULT 'contacted'
        CHECK (stage IN ('contacted','interested','proposal','won','lost')),
    amount_cents  INTEGER NULL,
    currency      TEXT NOT NULL DEFAULT 'USD',
    close_date    TEXT NULL,
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    deleted_at    TEXT NULL
);
INSERT INTO deals_new
    (id, name, org_id, stage, amount_cents, currency, close_date, created_at, updated_at, deleted_at)
SELECT id, name, org_id,
       CASE stage
           WHEN 'lead' THEN 'contacted'
           WHEN 'qualified' THEN 'interested'
           WHEN 'negotiation' THEN 'proposal'
           ELSE stage
       END,
       amount_cents, currency, close_date, created_at, updated_at, deleted_at
FROM deals;

DROP TABLE deals;
DROP TABLE contacts;
ALTER TABLE contacts_new RENAME TO contacts;
ALTER TABLE deals_new RENAME TO deals;

CREATE INDEX idx_contacts_live
    ON contacts(id) WHERE deleted_at IS NULL;
CREATE INDEX idx_contacts_display_name_nocase
    ON contacts(display_name COLLATE NOCASE) WHERE deleted_at IS NULL;
CREATE INDEX idx_contacts_org
    ON contacts(org_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_deals_live
    ON deals(id) WHERE deleted_at IS NULL;
CREATE INDEX idx_deals_org
    ON deals(org_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_deals_stage
    ON deals(stage) WHERE deleted_at IS NULL;
CREATE INDEX idx_deals_open
    ON deals(id) WHERE deleted_at IS NULL AND stage NOT IN ('won','lost');

CREATE TABLE contact_emails (
    id          TEXT PRIMARY KEY,
    contact_id  TEXT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    email       TEXT NOT NULL,
    label       TEXT NULL,
    is_primary  INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT NOT NULL,
    deleted_at  TEXT NULL
);
INSERT INTO contact_emails SELECT * FROM phase24_contact_emails;
CREATE INDEX idx_contact_emails_contact_live ON contact_emails(contact_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_contact_emails_contact_email_live ON contact_emails(contact_id, email) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_contact_emails_primary_live ON contact_emails(contact_id) WHERE is_primary = 1 AND deleted_at IS NULL;
CREATE INDEX idx_contact_emails_primary_email ON contact_emails(email) WHERE is_primary = 1 AND deleted_at IS NULL;

CREATE TABLE contact_phones (
    id          TEXT PRIMARY KEY,
    contact_id  TEXT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    phone       TEXT NOT NULL,
    label       TEXT NULL,
    is_primary  INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT NOT NULL,
    deleted_at  TEXT NULL
);
INSERT INTO contact_phones SELECT * FROM phase24_contact_phones;
CREATE INDEX idx_contact_phones_contact_live ON contact_phones(contact_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_contact_phones_contact_phone_live ON contact_phones(contact_id, phone) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_contact_phones_primary_live ON contact_phones(contact_id) WHERE is_primary = 1 AND deleted_at IS NULL;

CREATE TABLE contact_tags (
    id          TEXT PRIMARY KEY,
    contact_id  TEXT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    tag         TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    deleted_at  TEXT NULL
);
INSERT INTO contact_tags SELECT * FROM phase24_contact_tags;
CREATE UNIQUE INDEX uq_contact_tags_contact_tag_live ON contact_tags(contact_id, tag) WHERE deleted_at IS NULL;
CREATE INDEX idx_contact_tags_tag_live ON contact_tags(tag) WHERE deleted_at IS NULL;

CREATE TABLE deal_contacts (
    id          TEXT PRIMARY KEY,
    deal_id     TEXT NOT NULL REFERENCES deals(id) ON DELETE CASCADE,
    contact_id  TEXT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
    role        TEXT NULL,
    created_at  TEXT NOT NULL,
    deleted_at  TEXT NULL
);
INSERT INTO deal_contacts SELECT * FROM phase24_deal_contacts;
CREATE UNIQUE INDEX uq_deal_contacts_pair_live ON deal_contacts(deal_id, contact_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_deal_contacts_deal_live ON deal_contacts(deal_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_deal_contacts_contact_live ON deal_contacts(contact_id) WHERE deleted_at IS NULL;

CREATE TABLE interactions (
    id          TEXT PRIMARY KEY,
    kind        TEXT NOT NULL CHECK (kind IN ('note','call','email','meeting')),
    body        TEXT NOT NULL DEFAULT '',
    occurred_at TEXT NOT NULL,
    contact_id  TEXT NULL REFERENCES contacts(id),
    org_id      TEXT NULL REFERENCES organizations(id),
    deal_id     TEXT NULL REFERENCES deals(id),
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL,
    deleted_at  TEXT NULL,
    CHECK (contact_id IS NOT NULL OR org_id IS NOT NULL OR deal_id IS NOT NULL)
);
INSERT INTO interactions SELECT * FROM phase24_interactions;
CREATE INDEX idx_interactions_live ON interactions(id) WHERE deleted_at IS NULL;
CREATE INDEX idx_interactions_contact ON interactions(contact_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_interactions_org ON interactions(org_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_interactions_deal ON interactions(deal_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_interactions_occurred ON interactions(occurred_at) WHERE deleted_at IS NULL;

CREATE TABLE tasks (
    id          TEXT PRIMARY KEY,
    title       TEXT NOT NULL,
    status      TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','done')),
    due_at      TEXT NULL,
    done_at     TEXT NULL,
    contact_id  TEXT NULL REFERENCES contacts(id),
    org_id      TEXT NULL REFERENCES organizations(id),
    deal_id     TEXT NULL REFERENCES deals(id),
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL,
    deleted_at  TEXT NULL
);
INSERT INTO tasks SELECT * FROM phase24_tasks;
CREATE INDEX idx_tasks_live ON tasks(id) WHERE deleted_at IS NULL;
CREATE INDEX idx_tasks_contact ON tasks(contact_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_tasks_org ON tasks(org_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_tasks_deal ON tasks(deal_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_tasks_open ON tasks(id) WHERE deleted_at IS NULL AND status = 'open';

DROP TABLE phase24_contact_emails;
DROP TABLE phase24_contact_phones;
DROP TABLE phase24_contact_tags;
DROP TABLE phase24_deal_contacts;
DROP TABLE phase24_interactions;
DROP TABLE phase24_tasks;
