// Package render formats the address-prefixed agent transcript.
package render

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strings"
	"sync"

	"github.com/ikigenba/ikigenba/agentkit"
)

// Trace writes the transcript. Conversation goes to stdout and terminal errors
// go to stderr.
type Trace struct {
	mu       sync.Mutex
	stdout   io.Writer
	stderr   io.Writer
	toolName map[toolCallKey]string
}

type toolCallKey struct {
	address string
	id      string
}

// NewTrace constructs a transcript writer.
func NewTrace(stdout, stderr io.Writer) *Trace {
	return &Trace{
		stdout:   stdout,
		stderr:   stderr,
		toolName: make(map[toolCallKey]string),
	}
}

// OneLine replaces line feeds, including CRLF pairs, with spaces.
func OneLine(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "\r\n", "\n"), "\n", " ")
}

// Event renders one live conversation event.
func (t *Trace) Event(address string, ev agentkit.Event) {
	t.mu.Lock()
	defer t.mu.Unlock()

	switch ev := ev.(type) {
	case agentkit.MessageDone:
		text := messageText(ev.Message)
		if text == "" && !hasText(ev.Message) {
			return
		}
		// Message line breaks are transcript content: continuation lines remain
		// verbatim and intentionally carry no repeated address prefix.
		t.write(t.stdout, address, "assistant", text)
	case agentkit.ToolCall:
		t.toolName[toolCallKey{address: address, id: ev.Use.ID}] = ev.Use.Name
		// The tool name is canonical transcript vocabulary and remains verbatim.
		t.write(t.stdout, address, "tool", ev.Use.Name+" "+compactInput(ev.Use.Input))
	case agentkit.ToolReturn:
		name := t.toolName[toolCallKey{address: address, id: ev.Result.ToolUseID}]
		if name == "" {
			name = ev.Result.ToolUseID
		}
		result := name + " "
		if ev.Result.IsError {
			result += "error: "
		}
		t.write(t.stdout, address, "result", result+OneLine(ev.Result.Content))
	case agentkit.OutputDone:
		return
	}
}

// Error renders a terminal conversation error.
func (t *Trace) Error(address string, err error) {
	t.mu.Lock()
	defer t.mu.Unlock()

	// Addresses are generated by the agent tree, not supplied by a provider or
	// prompt, and are the stable identity readers use to follow the transcript.
	t.write(t.stderr, address, "error", OneLine(err.Error()))
}

// Record formats the searchable text for a durable log record.
func (t *Trace) Record(rec agentkit.LogRecord) string {
	t.mu.Lock()
	defer t.mu.Unlock()

	switch rec.Type {
	case agentkit.RecordMessage:
		if rec.Message == nil {
			return ""
		}
		var role string
		switch rec.Message.Role {
		case agentkit.RoleUser:
			role = "user"
		case agentkit.RoleAssistant:
			role = "assistant"
		default:
			return ""
		}
		return role + " › " + messageText(*rec.Message)
	case agentkit.RecordToolUse:
		if rec.ToolUse == nil {
			return ""
		}
		return "tool › " + rec.ToolUse.Name + " " + compactInput(rec.ToolUse.Input)
	case agentkit.RecordToolResult:
		if rec.ToolResult == nil {
			return ""
		}
		prefix := "result › "
		if rec.ToolResult.IsError {
			prefix += "error: "
		}
		return prefix + OneLine(rec.ToolResult.Content)
	default:
		return ""
	}
}

// Summary writes the pass usage, price, and resumable session identifier.
func (t *Trace) Summary(usage agentkit.Usage, cost agentkit.Cost, session string) {
	t.mu.Lock()
	defer t.mu.Unlock()

	cacheWrite := usage.CacheWrite5mTokens + usage.CacheWrite1hTokens
	total := usage.InputTokens + usage.CachedTokens + cacheWrite +
		usage.OutputTokens + usage.ReasoningTokens
	mustWrite(t.stdout, fmt.Sprintf(
		"summary\n· tokens   in=%d cache(r=%d w=%d) out=%d reasoning=%d total=%d\n· cost     $%.6f pass\n· session  %s\n",
		usage.InputTokens, usage.CachedTokens, cacheWrite, usage.OutputTokens,
		usage.ReasoningTokens, total, float64(cost)/1_000_000_000, session))
}

func (t *Trace) write(w io.Writer, address, label, body string) {
	// Address and label are transcript structure. Body sanitization is
	// field-specific and therefore belongs to each caller; assistant text, in
	// particular, deliberately preserves embedded newlines.
	mustWrite(w, fmt.Sprintf("%s %s › %s\n\n", address, label, body))
}

func mustWrite(w io.Writer, output string) {
	n, err := io.WriteString(w, output)
	if err != nil {
		panic(fmt.Errorf("render trace: %w", err))
	}
	if n != len(output) {
		panic(fmt.Errorf("render trace: %w", io.ErrShortWrite))
	}
}

func compactInput(input json.RawMessage) string {
	var compact bytes.Buffer
	if err := json.Compact(&compact, input); err != nil {
		return OneLine(string(input))
	}
	return compact.String()
}

func messageText(message agentkit.Message) string {
	texts := make([]string, 0, len(message.Blocks))
	for _, block := range message.Blocks {
		if text, ok := block.(agentkit.Text); ok {
			texts = append(texts, text.Text)
		}
	}
	return strings.Join(texts, "\n")
}

func hasText(message agentkit.Message) bool {
	for _, block := range message.Blocks {
		if _, ok := block.(agentkit.Text); ok {
			return true
		}
	}
	return false
}
