-- migration: 20260720020257_owner_id_keying
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

DELETE FROM script_triggers;
DELETE FROM runs;
DROP TABLE scripts;

CREATE TABLE scripts (
    id          TEXT PRIMARY KEY,
    owner_id    TEXT NOT NULL,
    owner_email TEXT NOT NULL,
    name        TEXT,
    body        TEXT NOT NULL,
    config_json TEXT NOT NULL,
    source_path TEXT,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);
CREATE INDEX idx_scripts_owner ON scripts(owner_id);
CREATE UNIQUE INDEX idx_scripts_source
    ON scripts(owner_id, source_path) WHERE source_path IS NOT NULL;

-- TODO: write the forward-only schema change below.
