-- migration: 20260809050143_outbox_correlation
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

DROP INDEX IF EXISTS idx_outbox_created_at;
DROP TABLE IF EXISTS outbox;

CREATE TABLE outbox (
  seq            INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id       TEXT    NOT NULL,
  kind           TEXT    NOT NULL,
  subject        TEXT    NOT NULL DEFAULT '',
  payload        TEXT    NOT NULL,
  created_at     TEXT    NOT NULL,
  correlation_id TEXT    NOT NULL DEFAULT ''
);
CREATE INDEX idx_outbox_created_at ON outbox(created_at);
