-- migration: 20260712190612_trigger_filters
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

DROP TABLE script_triggers;

CREATE TABLE script_triggers (
    script_id  TEXT NOT NULL REFERENCES scripts(id) ON DELETE CASCADE,
    source     TEXT NOT NULL,
    filter     TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (script_id, filter)
);
CREATE INDEX idx_script_triggers_source ON script_triggers(source);

ALTER TABLE runs RENAME TO runs_old;
CREATE TABLE runs (
    id              TEXT PRIMARY KEY,
    script_id       TEXT NOT NULL REFERENCES scripts(id),
    status          TEXT NOT NULL,
    exit_code       INTEGER,
    started_at      TEXT NOT NULL,
    ended_at        TEXT,
    error           TEXT,
    trigger_source  TEXT,
    trigger_kind    TEXT,
    trigger_subject TEXT,
    trigger_event_id TEXT,
    stdout_path     TEXT NOT NULL,
    stderr_path     TEXT NOT NULL
);
INSERT INTO runs (id, script_id, status, exit_code, started_at, ended_at, error,
                  trigger_source, trigger_event_id, stdout_path, stderr_path)
SELECT id, script_id, status, exit_code, started_at, ended_at, error,
       trigger_source, trigger_event_id, stdout_path, stderr_path
FROM runs_old;
DROP TABLE runs_old;
CREATE INDEX idx_runs_script ON runs(script_id, started_at);
CREATE INDEX idx_runs_status ON runs(status);

ALTER TABLE outbox RENAME TO outbox_old;
CREATE TABLE outbox (
  seq        INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id   TEXT    NOT NULL,
  kind       TEXT    NOT NULL,
  subject    TEXT    NOT NULL,
  payload    TEXT    NOT NULL,
  created_at TEXT    NOT NULL
);
INSERT INTO outbox (seq, event_id, kind, subject, payload, created_at)
SELECT seq, event_id, type, '', payload, created_at FROM outbox_old;
DROP TABLE outbox_old;
CREATE INDEX idx_outbox_created_at ON outbox(created_at);
