-- migration: 20260809004748_retire_body
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

-- Refuse to discard the legacy body backup until every row has reached the
-- version plane. The CHECK failure aborts and rolls back this migration.
CREATE TABLE _seed_guard (ok INTEGER NOT NULL CHECK (ok = 1));
INSERT INTO _seed_guard(ok)
  SELECT CASE WHEN EXISTS (SELECT 1 FROM scripts WHERE repo_seeded_at IS NULL)
              THEN 0 ELSE 1 END;
DROP TABLE _seed_guard;

ALTER TABLE scripts DROP COLUMN body;
