-- migration: 20260809000848_version_plane
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.

ALTER TABLE scripts ADD COLUMN name_key TEXT;
ALTER TABLE scripts ADD COLUMN repo_seeded_at TEXT;
ALTER TABLE runs ADD COLUMN repo_sha TEXT NOT NULL DEFAULT '';

CREATE UNIQUE INDEX idx_scripts_name_key
    ON scripts(name_key) WHERE name_key IS NOT NULL;
