-- migration: 20260609135007_add_source_path
-- Generated by bin/create-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

-- Records the originating Dropbox mirror path an import-managed script was pulled
-- from (NULL for hand-authored scripts). The partial unique index makes the
-- import upsert a schema invariant: re-importing the same (owner, source_path)
-- updates the same row rather than piling up duplicates, while NULL (hand-authored)
-- rows are exempt and may repeat. See docs/adr-dropbox-import-sync.md (Decision 2).
ALTER TABLE scripts ADD COLUMN source_path TEXT;
CREATE UNIQUE INDEX idx_scripts_source
    ON scripts(owner_email, source_path) WHERE source_path IS NOT NULL;
