package tools

import "github.com/ikigenba/ikigenba/appkit/mcp"

// Register registers the seven catalog tools in their advertised order.
func Register(srv *mcp.Server, cfg Config) {
	mcp.AddTool(srv, mcp.Tool[ListArgs, SiteList]{Name: "list", Description: "The sites you own, by name.\n\nTakes no arguments. Each site has its id, name, slug, url (the address it answers at), visibility (public or private), listed, and commit (the sha it is published at, absent before the first publish). Use show for one site's repository and ref.", Effect: mcp.Read, Handler: cfg.list})
	mcp.AddTool(srv, mcp.Tool[ShowArgs, Site]{Name: "show", Description: "One of your sites, with its URL, its repository, and what is published.\n\nPass name, the site's name. The result has its id, name, slug, url, repo (the id of the repos repository it is served from), ref (the ref it tracks), visibility, listed, commit (the sha it is published at), created, and published (when it was last published); commit and published are absent before the first publish.", Effect: mcp.Read, Handler: cfg.show})
	mcp.AddTool(srv, mcp.Tool[CreateArgs, Site]{Name: "create", Description: "Create a site from one of your repositories and return it; publish it to make it live.\n\nname is 1 to 64 lowercase letters, digits, or '-', starting with a letter or digit, is neither about nor mcp, and must not already name a site in the space: names are shared by every user, because a listed site answers at its name. repo is the id of one of your repositories in repos. ref is the branch, tag, or commit the site tracks, main unless given. visibility is public, served to anyone, or private, served only to users signed in to the space; public unless given. listed is true unless given: a listed site answers at its name and is on the landing page; an unlisted one answers at its name followed by '-' and 8 random hexadecimal digits, and is on the landing page only for you. The site serves nothing until you publish it. The result is what show returns.", Effect: mcp.Additive, Handler: cfg.create})
	mcp.AddTool(srv, mcp.Tool[PublishArgs, Site]{Name: "publish", Description: "Publish one of your sites at a commit of its repository: the ref it tracks, or a ref or commit you name.\n\nPass name, and ref to publish a branch, tag, or commit sha other than the one the site tracks; a ref given here is used for this publish only and does not change the site's ref. The site serves the files of that commit exactly as git holds them, from the moment publish returns, and what it served before until then. Push to the repository, then publish again, to change what a site serves. The result is what show returns, with the new commit.", Effect: mcp.Additive, Handler: cfg.publish})
	mcp.AddTool(srv, mcp.Tool[UpdateArgs, Site]{Name: "update", Description: "Change one of your sites' visibility, whether it is listed, or the ref it tracks.\n\nPass name and at least one of visibility, listed, and ref, under the rules of create. Changing ref does not publish: call publish to serve the new ref. Changing listed never changes the slug, so a site keeps answering at the address it was created with. The apex site must stay public. The result is what show returns.", Effect: mcp.Additive, Handler: cfg.update})
	mcp.AddTool(srv, mcp.Tool[DeleteArgs, Deleted]{Name: "delete", Description: "Delete one of your sites; its repository is untouched.\n\nPass name. The site stops answering at once, its name is free for anyone to take, and if it was the apex site the apex is cleared. The repository and its history stay in repos. The result is the id of the deleted site.", Effect: mcp.Destructive, Handler: cfg.delete})
	mcp.AddRawTool(srv, mcp.RawTool[ApexArgs]{Name: "apex", Description: "Show, set or clear the site the space's apex domain redirects to.\n\nWith no arguments, the result is the apex site, or null when there is none. Pass name to make one of your public sites the apex, or clear true to clear it, whoever set it; not both. The result is the apex after the call.", Effect: mcp.Additive, Handler: cfg.apex})
}
