-- migration: 20260614050728_drop_legacy
-- Generated by bin/new-migration. This migration is IMMUTABLE: never edit or
-- delete it once committed — change schema by adding a new migration.
-- See docs/adr-migration-timestamps.md.

-- Legacy teardown (design §12.1). The frozen 002_wiki.sql still replays forward
-- on every database — including a freshly-wiped box DB — so wiping data alone
-- does not clean the schema. This is the first NEW migration (timestamp sorts
-- after the frozen 00N_* files and before the consolidated DDL); it drops what
-- the dead, wiki-specific legacy tables created. The wiki holds no data worth
-- keeping (the int box DB is disposable), so the teardown is unconditional.
--
-- feed_offset is NOT dropped — it is the eventplane consumer cursor store the new
-- design still depends on (owned by the library, applied by the frozen
-- 003_feed_offset.sql). Dropping it would break the consume side (§12.1).
DROP TABLE IF EXISTS wiki_ingest;   -- 002_wiki.sql; superseded by inbox (§2.2)
DROP TABLE IF EXISTS wiki_jobs;     -- 002_wiki.sql; superseded by runs + asks (§4.5, §9.2)
-- indexes drop automatically with their parent table (SQLite); no explicit DROP INDEX needed.
